In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottle

In [3]:
df1 = pd.read_excel('birth_df.xlsx')
df1

million      98      99     100     101     102     103     104  \
0  New Taipei City   32255   32093   27617   34323   22854   35915   38604   
1      Taipei City   20691   19403   18530   25132   22258   26710   29024   
2     Taoyuan City   19180   18515   15838   18041   16856   16757   17360   
3    Taichung City   23647   22601   19537   24027   20499   24555   26194   
4      Tainan City   14773   14196   11612   14208   17752   14788   15426   
5   Kaohsiung City   22182   11116   18684   21411   24963   21626   22520   
6           Taiwan  191310  166886  196627  229481  199113  210383  213598   

      105     106     107  108  
0   36313   34331   31611  NaN  
1   28987   27992   25042  NaN  
2   22384   23786   23356  NaN  
3   26313   25655   24338  NaN  
4   22469   14698   13773  NaN  
5   12044   21757   20260  NaN  
6  208440  193844  181601  NaN

In [4]:
df1.index = df1['million']

In [5]:
df1.columns

Index(['million', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [6]:
df1

million      98      99     100     101     102  \
million                                                                    
New Taipei City  New Taipei City   32255   32093   27617   34323   22854   
Taipei City          Taipei City   20691   19403   18530   25132   22258   
Taoyuan City        Taoyuan City   19180   18515   15838   18041   16856   
Taichung City      Taichung City   23647   22601   19537   24027   20499   
Tainan City          Tainan City   14773   14196   11612   14208   17752   
Kaohsiung City    Kaohsiung City   22182   11116   18684   21411   24963   
Taiwan                    Taiwan  191310  166886  196627  229481  199113   

                    103     104     105     106     107  108  
million                                                       
New Taipei City   35915   38604   36313   34331   31611  NaN  
Taipei City       26710   29024   28987   27992   25042  NaN  
Taoyuan City      16757   17360   22384   23786   23356  NaN  
Taichung City     24555   26194   26313   25655   24338  NaN  
Tainan City       14788   15426   22469   14698   13773  NaN  
Kaohsiung City    21626   22520   12044   21757   20260  NaN  
Taiwan           210383  213598  208440  193844  181601  NaN

In [7]:
df1 = df1.iloc[:-1, 1:-1]
df1

98     99     100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107  
million                        
New Taipei City  34331  31611  
Taipei City      27992  25042  
Taoyuan City     23786  23356  
Taichung City    25655  24338  
Tainan City      14698  13773  
Kaohsiung City   21757  20260

In [8]:
col = []
for i in df1.columns:
    col.append(str(i))
col

['98', '99', '100', '101', '102', '103', '104', '105', '106', '107']

In [9]:
df1.columns = col
df1

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107  
million                        
New Taipei City  34331  31611  
Taipei City      27992  25042  
Taoyuan City     23786  23356  
Taichung City    25655  24338  
Tainan City      14698  13773  
Kaohsiung City   21757  20260

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, New Taipei City to Kaohsiung City
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   98      6 non-null      int64
 1   99      6 non-null      int64
 2   100     6 non-null      int64
 3   101     6 non-null      int64
 4   102     6 non-null      int64
 5   103     6 non-null      int64
 6   104     6 non-null      int64
 7   105     6 non-null      int64
 8   106     6 non-null      int64
 9   107     6 non-null      int64
dtypes: int64(10)
memory usage: 528.0+ bytes


### input為n維

In [11]:
d = int(input('輸入的維度：'))
x_train = []
y_train = []


for i in range(10-d):
    x_train.append([])
    y_train.append([])
    
for j in range(10-d):
    x_train[j] = (df1.iloc[:, j:d+j].values)
    y_train[j] = (df1.iloc[:, d+j].values)

輸入的維度：5


In [12]:
x_train = np.array(x_train)
y_train = np.array(y_train)

In [13]:
x_train

array([[[32255, 32093, 27617, 34323, 22854],
        [20691, 19403, 18530, 25132, 22258],
        [19180, 18515, 15838, 18041, 16856],
        [23647, 22601, 19537, 24027, 20499],
        [14773, 14196, 11612, 14208, 17752],
        [22182, 11116, 18684, 21411, 24963]],

       [[32093, 27617, 34323, 22854, 35915],
        [19403, 18530, 25132, 22258, 26710],
        [18515, 15838, 18041, 16856, 16757],
        [22601, 19537, 24027, 20499, 24555],
        [14196, 11612, 14208, 17752, 14788],
        [11116, 18684, 21411, 24963, 21626]],

       [[27617, 34323, 22854, 35915, 38604],
        [18530, 25132, 22258, 26710, 29024],
        [15838, 18041, 16856, 16757, 17360],
        [19537, 24027, 20499, 24555, 26194],
        [11612, 14208, 17752, 14788, 15426],
        [18684, 21411, 24963, 21626, 22520]],

       [[34323, 22854, 35915, 38604, 36313],
        [25132, 22258, 26710, 29024, 28987],
        [18041, 16856, 16757, 17360, 22384],
        [24027, 20499, 24555, 26194, 26313],
    

In [14]:
x_train.shape

(5, 6, 5)

In [15]:
y_train

array([[35915, 26710, 16757, 24555, 14788, 21626],
       [38604, 29024, 17360, 26194, 15426, 22520],
       [36313, 28987, 22384, 26313, 22469, 12044],
       [34331, 27992, 23786, 25655, 14698, 21757],
       [31611, 25042, 23356, 24338, 13773, 20260]], dtype=int64)

In [16]:
y_train.shape

(5, 6)

In [17]:
x_train = x_train.reshape(-1, d)
y_train = y_train.ravel()

In [18]:
x_train

array([[32255, 32093, 27617, 34323, 22854],
       [20691, 19403, 18530, 25132, 22258],
       [19180, 18515, 15838, 18041, 16856],
       [23647, 22601, 19537, 24027, 20499],
       [14773, 14196, 11612, 14208, 17752],
       [22182, 11116, 18684, 21411, 24963],
       [32093, 27617, 34323, 22854, 35915],
       [19403, 18530, 25132, 22258, 26710],
       [18515, 15838, 18041, 16856, 16757],
       [22601, 19537, 24027, 20499, 24555],
       [14196, 11612, 14208, 17752, 14788],
       [11116, 18684, 21411, 24963, 21626],
       [27617, 34323, 22854, 35915, 38604],
       [18530, 25132, 22258, 26710, 29024],
       [15838, 18041, 16856, 16757, 17360],
       [19537, 24027, 20499, 24555, 26194],
       [11612, 14208, 17752, 14788, 15426],
       [18684, 21411, 24963, 21626, 22520],
       [34323, 22854, 35915, 38604, 36313],
       [25132, 22258, 26710, 29024, 28987],
       [18041, 16856, 16757, 17360, 22384],
       [24027, 20499, 24555, 26194, 26313],
       [14208, 17752, 14788, 154

In [19]:
y_train

array([35915, 26710, 16757, 24555, 14788, 21626, 38604, 29024, 17360,
       26194, 15426, 22520, 36313, 28987, 22384, 26313, 22469, 12044,
       34331, 27992, 23786, 25655, 14698, 21757, 31611, 25042, 23356,
       24338, 13773, 20260], dtype=int64)

In [20]:
from xgboost import XGBRegressor
xgbr = XGBRegressor(n_estimators=100 , max_depth=3 , learning_rate=0.1, subsample=1, colsample_bynode=0.8, reg_lambda=1e-05)
xgbr.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.8, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1e-05, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [21]:
# 計算各個城市的MAPE
box1 = []
for i in range(len(y_train)):
    MAPE = abs((xgbr.predict(x_train)[i]-y_train[i])/y_train[i])
    box1.append(MAPE)

box2 = []
for j in range(6):
    num = 0
    for k in range(j, len(y_train), 6):
        num += box1[k]
    num = num/(len(y_train)/6)
    box2.append(num)

for a in range(6):
    print('MAPE為', box2[a])

MAPE為 0.0006394091379886707
MAPE為 0.001741132119304575
MAPE為 0.0027683201072654278
MAPE為 0.0021761332267445158
MAPE為 0.0025209682303528125
MAPE為 0.002186260049454324


In [22]:
num = 0
for i in range(6):
    num += box2[i]
num /= 6
print('平均MAPE為', num)

平均MAPE為 0.0020053704785183875


```
輸入為1D的平均MAPE為0.037999859623224705
輸入為2D的平均MAPE為0.023461558098226046
輸入為3D的平均MAPE為0.013099736929332438
輸入為4D的平均MAPE為0.0072488503762277315
輸入為5D的平均MAPE為0.0020053704785183875
```

In [23]:
## 根據不同feature之間的權衡最後選出最佳的input維度，發現五維最好

## 選擇5D！！！

In [24]:
df2 = df1.copy()
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107  
million                        
New Taipei City  34331  31611  
Taipei City      27992  25042  
Taoyuan City     23786  23356  
Taichung City    25655  24338  
Tainan City      14698  13773  
Kaohsiung City   21757  20260

In [25]:
df2.iloc[:, -d:].values

array([[35915, 38604, 36313, 34331, 31611],
       [26710, 29024, 28987, 27992, 25042],
       [16757, 17360, 22384, 23786, 23356],
       [24555, 26194, 26313, 25655, 24338],
       [14788, 15426, 22469, 14698, 13773],
       [21626, 22520, 12044, 21757, 20260]], dtype=int64)

In [26]:
xgbr.predict(df2.iloc[:, -d:].values)

array([35363.516, 37196.324, 24272.77 , 25474.81 , 18385.697, 17494.678],
      dtype=float32)

In [27]:
df2['108'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107           108  
million                                      
New Taipei City  34331  31611  35363.515625  
Taipei City      27992  25042  37196.324219  
Taoyuan City     23786  23356  24272.769531  
Taichung City    25655  24338  25474.810547  
Tainan City      14698  13773  18385.697266  
Kaohsiung City   21757  20260  17494.677734

In [28]:
df2['109'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['110'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['111'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['112'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['113'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['114'] = xgbr.predict(df2.iloc[:, -d:].values)

In [29]:
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107           108           109           110  \
million                                                                   
New Taipei City  34331  31611  35363.515625  35822.960938  36036.343750   
Taipei City      27992  25042  37196.324219  38327.386719  36756.281250   
Taoyuan City     23786  23356  24272.769531  23737.636719  25254.189453   
Taichung City    25655  24338  25474.810547  25298.687500  25766.683594   
Tainan City      14698  13773  18385.697266  15532.900391  16977.578125   
Kaohsiung City   21757  20260  17494.677734  19564.041016  20813.103516   

                          111           112           113           114  
million                                                                  
New Taipei City  36036.343750  36741.578125  36028.308594  36044.027344  
Taipei City      34361.878906  31571.513672  35363.515625  35822.960938  
Taoyuan City     25442.130859  25624.519531  25458.158203  25427.363281  
Taichung City    25591.109375  25381.955078  25606.845703  25591.109375  
Tainan City      18991.488281  16432.630859  19138.019531  21694.060547  
Kaohsiung City   22424.445312  21640.830078  20386.470703  19878.912109

In [30]:
df3 = df2.iloc[:, 5:]

df3['103'] = xgbr.predict(df1.iloc[:, :5].values)
df3['104'] = xgbr.predict(df1.iloc[:, 1:6].values)
df3['105'] = xgbr.predict(df1.iloc[:, 2:7].values)
df3['106'] = xgbr.predict(df1.iloc[:, 3:8].values)
df3['107'] = xgbr.predict(df1.iloc[:, 4:9].values)

df3 = df3.T
df3.index = list(range(2014, 2026))

df1 = df1.T
df1.index = list(range(2009, 2019))

outputpath='C:/Users/Steven/Desktop/折線圖/birth_predict.xlsx'
df3.to_excel(outputpath,index=True,header=True)

outputpath='C:/Users/Steven/Desktop/折線圖/birth_origin.xlsx'
df1.to_excel(outputpath,index=True,header=True)