In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottle

In [3]:
df1 = pd.read_excel('city_annual_expend_df.xlsx')
df1

million             98             99            100  \
0  New Taipei City   96578.611019   98880.514918  101597.893147   
1      Taipei City  148192.887258  155531.416179  162280.646270   
2     Taoyuan City   45593.320794   48076.080794   48577.653444   
3    Taichung City   75788.780000   74185.000000   77484.420000   
4      Tainan City   58714.480000   59532.477000   64737.220000   
5   Kaohsiung City  102063.120000  117931.345000  115951.800000   
6           Taiwan  807522.000000  867824.000000  882066.000000   

             101            102            103            104           105  \
0  145899.009050  149866.518605  146754.099649  154473.463926  1.516608e+05   
1  173139.571548  176075.234609  169580.238024  167504.327527  1.541876e+05   
2   57174.898426   58093.627307   57736.471325   62760.000000  8.497782e+04   
3   96887.312546   99883.362462  109538.016083  104869.032822  1.131774e+05   
4   77578.825927   82584.343311   77916.851738   73521.376929  6.949806e+04   
5  126711.535220  124889.951539  122071.850246  126265.671271  1.199338e+05   
6  986397.000000  998285.000000  987590.000000  999547.000000  1.002236e+06   

          106           107       108  
0   148828.44  1.488284e+05  166966.0  
1   162256.23  1.622562e+05  165546.0  
2    95094.42  9.509442e+04  115998.0  
3   123807.59  1.238076e+05  124657.0  
4    74696.14  7.469614e+04   86319.0  
5   121757.81  1.217580e+05  133542.0  
6  1014904.00  1.036507e+06       NaN

In [4]:
df1.index = df1['million']

In [5]:
df1.columns

Index(['million', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [6]:
df1

million             98             99            100  \
million                                                                         
New Taipei City  New Taipei City   96578.611019   98880.514918  101597.893147   
Taipei City          Taipei City  148192.887258  155531.416179  162280.646270   
Taoyuan City        Taoyuan City   45593.320794   48076.080794   48577.653444   
Taichung City      Taichung City   75788.780000   74185.000000   77484.420000   
Tainan City          Tainan City   58714.480000   59532.477000   64737.220000   
Kaohsiung City    Kaohsiung City  102063.120000  117931.345000  115951.800000   
Taiwan                    Taiwan  807522.000000  867824.000000  882066.000000   

                           101            102            103            104  \
million                                                                       
New Taipei City  145899.009050  149866.518605  146754.099649  154473.463926   
Taipei City      173139.571548  176075.234609  169580.238024  167504.327527   
Taoyuan City      57174.898426   58093.627307   57736.471325   62760.000000   
Taichung City     96887.312546   99883.362462  109538.016083  104869.032822   
Tainan City       77578.825927   82584.343311   77916.851738   73521.376929   
Kaohsiung City   126711.535220  124889.951539  122071.850246  126265.671271   
Taiwan           986397.000000  998285.000000  987590.000000  999547.000000   

                          105         106           107       108  
million                                                            
New Taipei City  1.516608e+05   148828.44  1.488284e+05  166966.0  
Taipei City      1.541876e+05   162256.23  1.622562e+05  165546.0  
Taoyuan City     8.497782e+04    95094.42  9.509442e+04  115998.0  
Taichung City    1.131774e+05   123807.59  1.238076e+05  124657.0  
Tainan City      6.949806e+04    74696.14  7.469614e+04   86319.0  
Kaohsiung City   1.199338e+05   121757.81  1.217580e+05  133542.0  
Taiwan           1.002236e+06  1014904.00  1.036507e+06       NaN

In [7]:
df1 = df1.iloc[:-1, 1:-1]
df1

98             99             100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107  
million                                    
New Taipei City  148828.44  148828.437264  
Taipei City      162256.23  162256.234058  
Taoyuan City      95094.42   95094.418061  
Taichung City    123807.59  123807.590957  
Tainan City       74696.14   74696.140442  
Kaohsiung City   121757.81  121758.000000

In [8]:
col = []
for i in df1.columns:
    col.append(str(i))
col

['98', '99', '100', '101', '102', '103', '104', '105', '106', '107']

In [9]:
df1.columns = col
df1

98             99            100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107  
million                                    
New Taipei City  148828.44  148828.437264  
Taipei City      162256.23  162256.234058  
Taoyuan City      95094.42   95094.418061  
Taichung City    123807.59  123807.590957  
Tainan City       74696.14   74696.140442  
Kaohsiung City   121757.81  121758.000000

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, New Taipei City to Kaohsiung City
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   98      6 non-null      float64
 1   99      6 non-null      float64
 2   100     6 non-null      float64
 3   101     6 non-null      float64
 4   102     6 non-null      float64
 5   103     6 non-null      float64
 6   104     6 non-null      float64
 7   105     6 non-null      float64
 8   106     6 non-null      float64
 9   107     6 non-null      float64
dtypes: float64(10)
memory usage: 528.0+ bytes


### input為n維

In [11]:
d = int(input('輸入的維度：'))
x_train = []
y_train = []


for i in range(10-d):
    x_train.append([])
    y_train.append([])
    
for j in range(10-d):
    x_train[j] = (df1.iloc[:, j:d+j].values)
    y_train[j] = (df1.iloc[:, d+j].values)

輸入的維度：5


In [12]:
x_train = np.array(x_train)
y_train = np.array(y_train)

In [13]:
x_train

array([[[ 96578.611019,  98880.514918, 101597.893147, 145899.00905 ,
         149866.518605],
        [148192.887258, 155531.416179, 162280.64627 , 173139.571548,
         176075.234609],
        [ 45593.320794,  48076.080794,  48577.653444,  57174.898426,
          58093.627307],
        [ 75788.78    ,  74185.      ,  77484.42    ,  96887.312546,
          99883.362462],
        [ 58714.48    ,  59532.477   ,  64737.22    ,  77578.825927,
          82584.343311],
        [102063.12    , 117931.345   , 115951.8     , 126711.53522 ,
         124889.951539]],

       [[ 98880.514918, 101597.893147, 145899.00905 , 149866.518605,
         146754.099649],
        [155531.416179, 162280.64627 , 173139.571548, 176075.234609,
         169580.238024],
        [ 48076.080794,  48577.653444,  57174.898426,  58093.627307,
          57736.471325],
        [ 74185.      ,  77484.42    ,  96887.312546,  99883.362462,
         109538.016083],
        [ 59532.477   ,  64737.22    ,  77578.825927,  825

In [14]:
x_train.shape

(5, 6, 5)

In [15]:
y_train

array([[146754.099649, 169580.238024,  57736.471325, 109538.016083,
         77916.851738, 122071.850246],
       [154473.463926, 167504.327527,  62760.      , 104869.032822,
         73521.376929, 126265.671271],
       [151660.814378, 154187.639168,  84977.820413, 113177.438775,
         69498.060327, 119933.785777],
       [148828.44    , 162256.23    ,  95094.42    , 123807.59    ,
         74696.14    , 121757.81    ],
       [148828.437264, 162256.234058,  95094.418061, 123807.590957,
         74696.140442, 121758.      ]])

In [16]:
y_train.shape

(5, 6)

In [17]:
x_train = x_train.reshape(-1, d)
y_train = y_train.ravel()

In [18]:
x_train

array([[ 96578.611019,  98880.514918, 101597.893147, 145899.00905 ,
        149866.518605],
       [148192.887258, 155531.416179, 162280.64627 , 173139.571548,
        176075.234609],
       [ 45593.320794,  48076.080794,  48577.653444,  57174.898426,
         58093.627307],
       [ 75788.78    ,  74185.      ,  77484.42    ,  96887.312546,
         99883.362462],
       [ 58714.48    ,  59532.477   ,  64737.22    ,  77578.825927,
         82584.343311],
       [102063.12    , 117931.345   , 115951.8     , 126711.53522 ,
        124889.951539],
       [ 98880.514918, 101597.893147, 145899.00905 , 149866.518605,
        146754.099649],
       [155531.416179, 162280.64627 , 173139.571548, 176075.234609,
        169580.238024],
       [ 48076.080794,  48577.653444,  57174.898426,  58093.627307,
         57736.471325],
       [ 74185.      ,  77484.42    ,  96887.312546,  99883.362462,
        109538.016083],
       [ 59532.477   ,  64737.22    ,  77578.825927,  82584.343311,
         779

In [19]:
y_train

array([146754.099649, 169580.238024,  57736.471325, 109538.016083,
        77916.851738, 122071.850246, 154473.463926, 167504.327527,
        62760.      , 104869.032822,  73521.376929, 126265.671271,
       151660.814378, 154187.639168,  84977.820413, 113177.438775,
        69498.060327, 119933.785777, 148828.44    , 162256.23    ,
        95094.42    , 123807.59    ,  74696.14    , 121757.81    ,
       148828.437264, 162256.234058,  95094.418061, 123807.590957,
        74696.140442, 121758.      ])

In [20]:
from xgboost import XGBRegressor
xgbr = XGBRegressor(n_estimators=100 , max_depth=3 , learning_rate=0.1, subsample=1, colsample_bynode=0.8, reg_lambda=1e-05)
xgbr.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.8, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1e-05, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [21]:
# 計算各個城市的MAPE
box1 = []
for i in range(len(y_train)):
    MAPE = abs((xgbr.predict(x_train)[i]-y_train[i])/y_train[i])
    box1.append(MAPE)

box2 = []
for j in range(6):
    num = 0
    for k in range(j, len(y_train), 6):
        num += box1[k]
    num = num/(len(y_train)/6)
    box2.append(num)

for a in range(6):
    print('MAPE為', box2[a])

MAPE為 0.0007554134070595819
MAPE為 0.00037588049876504515
MAPE為 0.0009476840357042623
MAPE為 0.0008399805442047298
MAPE為 0.0007389773252813939
MAPE為 0.0004554096645130484


In [22]:
num = 0
for i in range(6):
    num += box2[i]
num /= 6
print('平均MAPE為', num)

平均MAPE為 0.0006855575792546769


```
輸入為1D的平均MAPE為0.00863580583041417
輸入為2D的平均MAPE為0.007332458905659592
輸入為3D的平均MAPE為0.003963531121280252
輸入為4D的平均MAPE為0.0017871561885410621
輸入為5D的平均MAPE為0.0006855575792546769
```

In [23]:
## 根據不同feature之間的權衡最後選出最佳的input維度，發現五維最好

## 選擇5D！！！

In [24]:
df2 = df1.copy()
df2

98             99            100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107  
million                                    
New Taipei City  148828.44  148828.437264  
Taipei City      162256.23  162256.234058  
Taoyuan City      95094.42   95094.418061  
Taichung City    123807.59  123807.590957  
Tainan City       74696.14   74696.140442  
Kaohsiung City   121757.81  121758.000000

In [25]:
df2.iloc[:, -d:].values

array([[146754.099649, 154473.463926, 151660.814378, 148828.44    ,
        148828.437264],
       [169580.238024, 167504.327527, 154187.639168, 162256.23    ,
        162256.234058],
       [ 57736.471325,  62760.      ,  84977.820413,  95094.42    ,
         95094.418061],
       [109538.016083, 104869.032822, 113177.438775, 123807.59    ,
        123807.590957],
       [ 77916.851738,  73521.376929,  69498.060327,  74696.14    ,
         74696.140442],
       [122071.850246, 126265.671271, 119933.785777, 121757.81    ,
        121758.      ]])

In [26]:
xgbr.predict(df2.iloc[:, -d:].values)

array([156720.69, 160503.6 ,  97088.1 , 124657.34,  74990.07, 120018.3 ],
      dtype=float32)

In [27]:
df2['108'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98             99            100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107            108  
million                                                   
New Taipei City  148828.44  148828.437264  156720.687500  
Taipei City      162256.23  162256.234058  160503.593750  
Taoyuan City      95094.42   95094.418061   97088.101562  
Taichung City    123807.59  123807.590957  124657.343750  
Tainan City       74696.14   74696.140442   74990.070312  
Kaohsiung City   121757.81  121758.000000  120018.296875

In [28]:
df2['109'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['110'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['111'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['112'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['113'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['114'] = xgbr.predict(df2.iloc[:, -d:].values)

In [29]:
df2

98             99            100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107            108            109  \
million                                                                   
New Taipei City  148828.44  148828.437264  156720.687500  151405.500000   
Taipei City      162256.23  162256.234058  160503.593750  160854.359375   
Taoyuan City      95094.42   95094.418061   97088.101562   97632.562500   
Taichung City    123807.59  123807.590957  124657.343750  124296.687500   
Tainan City       74696.14   74696.140442   74990.070312   74701.578125   
Kaohsiung City   121757.81  121758.000000  120018.296875  121550.406250   

                           110            111            112            113  \
million                                                                       
New Taipei City  148971.140625  148971.140625  156720.687500  151405.500000   
Taipei City      160854.359375  160854.359375  160854.359375  160854.359375   
Taoyuan City     112349.367188  121935.484375  122014.335938  123413.882812   
Taichung City    121762.359375  121747.242188  121107.398438  121269.804688   
Tainan City       74499.812500   74701.578125   74701.578125   75233.554688   
Kaohsiung City   121607.023438  121550.406250  121550.406250  121550.406250   

                           114  
million                         
New Taipei City  148971.140625  
Taipei City      160854.359375  
Taoyuan City     123872.851562  
Taichung City    121550.406250  
Tainan City       74701.578125  
Kaohsiung City   121550.406250

In [30]:
df3 = df2.iloc[:, 5:]

df3['103'] = xgbr.predict(df1.iloc[:, :5].values)
df3['104'] = xgbr.predict(df1.iloc[:, 1:6].values)
df3['105'] = xgbr.predict(df1.iloc[:, 2:7].values)
df3['106'] = xgbr.predict(df1.iloc[:, 3:8].values)
df3['107'] = xgbr.predict(df1.iloc[:, 4:9].values)

df3 = df3.T
df3.index = list(range(2014, 2026))

df1 = df1.T
df1.index = list(range(2009, 2019))

outputpath='C:/Users/Steven/Desktop/折線圖/city_annual_predict.xlsx'
df3.to_excel(outputpath,index=True,header=True)

outputpath='C:/Users/Steven/Desktop/折線圖/city_annual_origin.xlsx'
df1.to_excel(outputpath,index=True,header=True)