In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottle

In [3]:
df1 = pd.read_excel('death_df.xlsx')
df1

million      98      99     100     101     102     103     104  \
0  New Taipei City   17882   17959   18404   19774   20280   20746   21935   
1      Taipei City   15606   15260   15398   15988   16579   16379   17177   
2     Taoyuan City    9677    9790   10183   10878   10977   10972   11854   
3    Taichung City   13826   13805   14340   14915   15017   15138   15968   
4      Tainan City   13040   12990   13206   13941   13871   14021   14390   
5   Kaohsiung City   17517   18189   18001   18845   18945   19277   20282   
6           Taiwan  143582  145772  152915  154251  155908  163929  163858   

      105     106     107  108  
0   22175   23256   23525  NaN  
1   17106   17982   17467  NaN  
2   11600   12637   12620  NaN  
3   16070   16921   16904  NaN  
4   20508   15234   14996  NaN  
5   12779   21365   21368  NaN  
6  172405  171242  172784  NaN

In [4]:
df1.index = df1['million']

In [5]:
df1.columns

Index(['million', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [6]:
df1

million      98      99     100     101     102  \
million                                                                    
New Taipei City  New Taipei City   17882   17959   18404   19774   20280   
Taipei City          Taipei City   15606   15260   15398   15988   16579   
Taoyuan City        Taoyuan City    9677    9790   10183   10878   10977   
Taichung City      Taichung City   13826   13805   14340   14915   15017   
Tainan City          Tainan City   13040   12990   13206   13941   13871   
Kaohsiung City    Kaohsiung City   17517   18189   18001   18845   18945   
Taiwan                    Taiwan  143582  145772  152915  154251  155908   

                    103     104     105     106     107  108  
million                                                       
New Taipei City   20746   21935   22175   23256   23525  NaN  
Taipei City       16379   17177   17106   17982   17467  NaN  
Taoyuan City      10972   11854   11600   12637   12620  NaN  
Taichung City     15138   15968   16070   16921   16904  NaN  
Tainan City       14021   14390   20508   15234   14996  NaN  
Kaohsiung City    19277   20282   12779   21365   21368  NaN  
Taiwan           163929  163858  172405  171242  172784  NaN

In [7]:
df1 = df1.iloc[:-1, 1:-1]
df1

98     99     100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107  
million                        
New Taipei City  23256  23525  
Taipei City      17982  17467  
Taoyuan City     12637  12620  
Taichung City    16921  16904  
Tainan City      15234  14996  
Kaohsiung City   21365  21368

In [8]:
col = []
for i in df1.columns:
    col.append(str(i))
col

['98', '99', '100', '101', '102', '103', '104', '105', '106', '107']

In [9]:
df1.columns = col
df1

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107  
million                        
New Taipei City  23256  23525  
Taipei City      17982  17467  
Taoyuan City     12637  12620  
Taichung City    16921  16904  
Tainan City      15234  14996  
Kaohsiung City   21365  21368

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, New Taipei City to Kaohsiung City
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   98      6 non-null      int64
 1   99      6 non-null      int64
 2   100     6 non-null      int64
 3   101     6 non-null      int64
 4   102     6 non-null      int64
 5   103     6 non-null      int64
 6   104     6 non-null      int64
 7   105     6 non-null      int64
 8   106     6 non-null      int64
 9   107     6 non-null      int64
dtypes: int64(10)
memory usage: 528.0+ bytes


### input為n維

In [11]:
d = int(input('輸入的維度：'))
x_train = []
y_train = []


for i in range(10-d):
    x_train.append([])
    y_train.append([])
    
for j in range(10-d):
    x_train[j] = (df1.iloc[:, j:d+j].values)
    y_train[j] = (df1.iloc[:, d+j].values)

輸入的維度：5


In [12]:
x_train = np.array(x_train)
y_train = np.array(y_train)

In [13]:
x_train

array([[[17882, 17959, 18404, 19774, 20280],
        [15606, 15260, 15398, 15988, 16579],
        [ 9677,  9790, 10183, 10878, 10977],
        [13826, 13805, 14340, 14915, 15017],
        [13040, 12990, 13206, 13941, 13871],
        [17517, 18189, 18001, 18845, 18945]],

       [[17959, 18404, 19774, 20280, 20746],
        [15260, 15398, 15988, 16579, 16379],
        [ 9790, 10183, 10878, 10977, 10972],
        [13805, 14340, 14915, 15017, 15138],
        [12990, 13206, 13941, 13871, 14021],
        [18189, 18001, 18845, 18945, 19277]],

       [[18404, 19774, 20280, 20746, 21935],
        [15398, 15988, 16579, 16379, 17177],
        [10183, 10878, 10977, 10972, 11854],
        [14340, 14915, 15017, 15138, 15968],
        [13206, 13941, 13871, 14021, 14390],
        [18001, 18845, 18945, 19277, 20282]],

       [[19774, 20280, 20746, 21935, 22175],
        [15988, 16579, 16379, 17177, 17106],
        [10878, 10977, 10972, 11854, 11600],
        [14915, 15017, 15138, 15968, 16070],
    

In [14]:
x_train.shape

(5, 6, 5)

In [15]:
y_train

array([[20746, 16379, 10972, 15138, 14021, 19277],
       [21935, 17177, 11854, 15968, 14390, 20282],
       [22175, 17106, 11600, 16070, 20508, 12779],
       [23256, 17982, 12637, 16921, 15234, 21365],
       [23525, 17467, 12620, 16904, 14996, 21368]], dtype=int64)

In [16]:
y_train.shape

(5, 6)

In [17]:
x_train = x_train.reshape(-1, d)
y_train = y_train.ravel()

In [18]:
x_train

array([[17882, 17959, 18404, 19774, 20280],
       [15606, 15260, 15398, 15988, 16579],
       [ 9677,  9790, 10183, 10878, 10977],
       [13826, 13805, 14340, 14915, 15017],
       [13040, 12990, 13206, 13941, 13871],
       [17517, 18189, 18001, 18845, 18945],
       [17959, 18404, 19774, 20280, 20746],
       [15260, 15398, 15988, 16579, 16379],
       [ 9790, 10183, 10878, 10977, 10972],
       [13805, 14340, 14915, 15017, 15138],
       [12990, 13206, 13941, 13871, 14021],
       [18189, 18001, 18845, 18945, 19277],
       [18404, 19774, 20280, 20746, 21935],
       [15398, 15988, 16579, 16379, 17177],
       [10183, 10878, 10977, 10972, 11854],
       [14340, 14915, 15017, 15138, 15968],
       [13206, 13941, 13871, 14021, 14390],
       [18001, 18845, 18945, 19277, 20282],
       [19774, 20280, 20746, 21935, 22175],
       [15988, 16579, 16379, 17177, 17106],
       [10878, 10977, 10972, 11854, 11600],
       [14915, 15017, 15138, 15968, 16070],
       [13941, 13871, 14021, 143

In [19]:
y_train

array([20746, 16379, 10972, 15138, 14021, 19277, 21935, 17177, 11854,
       15968, 14390, 20282, 22175, 17106, 11600, 16070, 20508, 12779,
       23256, 17982, 12637, 16921, 15234, 21365, 23525, 17467, 12620,
       16904, 14996, 21368], dtype=int64)

In [20]:
from xgboost import XGBRegressor
xgbr = XGBRegressor(n_estimators=100 , max_depth=3 , learning_rate=0.1, subsample=1, colsample_bynode=0.8, reg_lambda=1e-05)
xgbr.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.8, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1e-05, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [21]:
# 計算各個城市的MAPE
box1 = []
for i in range(len(y_train)):
    MAPE = abs((xgbr.predict(x_train)[i]-y_train[i])/y_train[i])
    box1.append(MAPE)

box2 = []
for j in range(6):
    num = 0
    for k in range(j, len(y_train), 6):
        num += box1[k]
    num = num/(len(y_train)/6)
    box2.append(num)

for a in range(6):
    print('MAPE為', box2[a])

MAPE為 0.0004281122701244084
MAPE為 0.0006108450192070518
MAPE為 0.0004213488121167436
MAPE為 0.0010411214601281928
MAPE為 0.0006436671082628349
MAPE為 0.0005882537250098032


In [22]:
num = 0
for i in range(6):
    num += box2[i]
num /= 6
print('平均MAPE為', num)

平均MAPE為 0.0006222247324748391


```
輸入為1D的平均MAPE為0.009009997559016235
輸入為2D的平均MAPE為0.004357888094382672
輸入為3D的平均MAPE為0.0020958497249563657
輸入為4D的平均MAPE為0.0010145861350529155
輸入為5D的平均MAPE為0.0006222247324748391
```

In [23]:
## 根據不同feature之間的權衡最後選出最佳的input維度，發現五維最好

## 選擇5D！！！

In [24]:
df2 = df1.copy()
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107  
million                        
New Taipei City  23256  23525  
Taipei City      17982  17467  
Taoyuan City     12637  12620  
Taichung City    16921  16904  
Tainan City      15234  14996  
Kaohsiung City   21365  21368

In [25]:
df2.iloc[:, -d:].values

array([[20746, 21935, 22175, 23256, 23525],
       [16379, 17177, 17106, 17982, 17467],
       [10972, 11854, 11600, 12637, 12620],
       [15138, 15968, 16070, 16921, 16904],
       [14021, 14390, 20508, 15234, 14996],
       [19277, 20282, 12779, 21365, 21368]], dtype=int64)

In [26]:
xgbr.predict(df2.iloc[:, -d:].values)

array([23512.266, 18040.84 , 12627.977, 17146.6  , 16922.5  , 19733.053],
      dtype=float32)

In [27]:
df2['108'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107           108  
million                                      
New Taipei City  23256  23525  23512.265625  
Taipei City      17982  17467  18040.839844  
Taoyuan City     12637  12620  12627.976562  
Taichung City    16921  16904  17146.599609  
Tainan City      15234  14996  16922.500000  
Kaohsiung City   21365  21368  19733.052734

In [28]:
df2['109'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['110'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['111'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['112'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['113'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['114'] = xgbr.predict(df2.iloc[:, -d:].values)

In [29]:
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107           108           109           110  \
million                                                                   
New Taipei City  23256  23525  23512.265625  23512.265625  23512.265625   
Taipei City      17982  17467  18040.839844  19126.949219  19288.501953   
Taoyuan City     12637  12620  12627.976562  12627.976562  12893.833008   
Taichung City    16921  16904  17146.599609  17370.001953  17973.425781   
Tainan City      15234  14996  16922.500000  17018.515625  18944.423828   
Kaohsiung City   21365  21368  19733.052734  20275.867188  19239.363281   

                          111           112           113           114  
million                                                                  
New Taipei City  23512.265625  23512.265625  23512.265625  23512.265625  
Taipei City      15706.207031  17264.308594  18658.095703  18805.523438  
Taoyuan City     14027.185547  14027.185547  14027.185547  13760.317383  
Taichung City    18045.019531  18045.019531  19274.248047  19289.871094  
Tainan City      17007.958984  17393.689453  17624.189453  17813.238281  
Kaohsiung City   22877.269531  19393.363281  22525.826172  19401.835938

In [30]:
df3 = df2.iloc[:, 5:]

df3['103'] = xgbr.predict(df1.iloc[:, :5].values)
df3['104'] = xgbr.predict(df1.iloc[:, 1:6].values)
df3['105'] = xgbr.predict(df1.iloc[:, 2:7].values)
df3['106'] = xgbr.predict(df1.iloc[:, 3:8].values)
df3['107'] = xgbr.predict(df1.iloc[:, 4:9].values)

df3 = df3.T
df3.index = list(range(2014, 2026))

df1 = df1.T
df1.index = list(range(2009, 2019))

outputpath='C:/Users/Steven/Desktop/折線圖/death_predict.xlsx'
df3.to_excel(outputpath,index=True,header=True)

outputpath='C:/Users/Steven/Desktop/折線圖/death_origin.xlsx'
df1.to_excel(outputpath,index=True,header=True)