In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottle

In [3]:
df1 = pd.read_excel('immigration_df.xlsx')
df1

million     98     99    100    101    102    103   104    105  \
0  New Taipei City  21342  25789  14501   4535   2287    455 -4780 -10312   
1      Taipei City -11431 -19638   8212  23052   9339   2959  3952  -9386   
2     Taoyuan City  14215  11371  17623   4082   7967   8077  8799  36668   
3    Taichung City   7457   2893   7461   6863   7192   7351  7948  14367   
4      Tainan City   1211   1195    -18   2899    804    796    40  -2035   
5   Kaohsiung City   -479  -1055   1913  -1579  -1829  -1131 -3123    102   
6           Taiwan  35013  21237  19077  15680  14490  13782  6798  11707   

     106    107     108  
0  -2511   -605  4030.0  
1 -19116 -20022     NaN  
2  30834  29518     NaN  
3  14060  12397     NaN  
4   1028   1712     NaN  
5     61  -1351     NaN  
6   8809   6770     NaN

In [4]:
df1.index = df1['million']

In [5]:
df1.columns

Index(['million', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [6]:
df1

million     98     99    100    101    102    103  \
million                                                                      
New Taipei City  New Taipei City  21342  25789  14501   4535   2287    455   
Taipei City          Taipei City -11431 -19638   8212  23052   9339   2959   
Taoyuan City        Taoyuan City  14215  11371  17623   4082   7967   8077   
Taichung City      Taichung City   7457   2893   7461   6863   7192   7351   
Tainan City          Tainan City   1211   1195    -18   2899    804    796   
Kaohsiung City    Kaohsiung City   -479  -1055   1913  -1579  -1829  -1131   
Taiwan                    Taiwan  35013  21237  19077  15680  14490  13782   

                  104    105    106    107     108  
million                                             
New Taipei City -4780 -10312  -2511   -605  4030.0  
Taipei City      3952  -9386 -19116 -20022     NaN  
Taoyuan City     8799  36668  30834  29518     NaN  
Taichung City    7948  14367  14060  12397     NaN  
Tainan City        40  -2035   1028   1712     NaN  
Kaohsiung City  -3123    102     61  -1351     NaN  
Taiwan           6798  11707   8809   6770     NaN

In [7]:
df1 = df1.iloc[:-1, 1:-1]
df1

98     99     100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107  
million                 
New Taipei City   -605  
Taipei City     -20022  
Taoyuan City     29518  
Taichung City    12397  
Tainan City       1712  
Kaohsiung City   -1351

In [8]:
col = []
for i in df1.columns:
    col.append(str(i))
col

['98', '99', '100', '101', '102', '103', '104', '105', '106', '107']

In [9]:
df1.columns = col
df1

98     99    100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107  
million                 
New Taipei City   -605  
Taipei City     -20022  
Taoyuan City     29518  
Taichung City    12397  
Tainan City       1712  
Kaohsiung City   -1351

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, New Taipei City to Kaohsiung City
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   98      6 non-null      int64
 1   99      6 non-null      int64
 2   100     6 non-null      int64
 3   101     6 non-null      int64
 4   102     6 non-null      int64
 5   103     6 non-null      int64
 6   104     6 non-null      int64
 7   105     6 non-null      int64
 8   106     6 non-null      int64
 9   107     6 non-null      int64
dtypes: int64(10)
memory usage: 528.0+ bytes


### input為n維

In [11]:
d = int(input('輸入的維度：'))
x_train = []
y_train = []


for i in range(10-d):
    x_train.append([])
    y_train.append([])
    
for j in range(10-d):
    x_train[j] = (df1.iloc[:, j:d+j].values)
    y_train[j] = (df1.iloc[:, d+j].values)

輸入的維度：5


In [12]:
x_train = np.array(x_train)
y_train = np.array(y_train)

In [13]:
x_train

array([[[ 21342,  25789,  14501,   4535,   2287],
        [-11431, -19638,   8212,  23052,   9339],
        [ 14215,  11371,  17623,   4082,   7967],
        [  7457,   2893,   7461,   6863,   7192],
        [  1211,   1195,    -18,   2899,    804],
        [  -479,  -1055,   1913,  -1579,  -1829]],

       [[ 25789,  14501,   4535,   2287,    455],
        [-19638,   8212,  23052,   9339,   2959],
        [ 11371,  17623,   4082,   7967,   8077],
        [  2893,   7461,   6863,   7192,   7351],
        [  1195,    -18,   2899,    804,    796],
        [ -1055,   1913,  -1579,  -1829,  -1131]],

       [[ 14501,   4535,   2287,    455,  -4780],
        [  8212,  23052,   9339,   2959,   3952],
        [ 17623,   4082,   7967,   8077,   8799],
        [  7461,   6863,   7192,   7351,   7948],
        [   -18,   2899,    804,    796,     40],
        [  1913,  -1579,  -1829,  -1131,  -3123]],

       [[  4535,   2287,    455,  -4780, -10312],
        [ 23052,   9339,   2959,   3952,  -9

In [14]:
x_train.shape

(5, 6, 5)

In [15]:
y_train

array([[   455,   2959,   8077,   7351,    796,  -1131],
       [ -4780,   3952,   8799,   7948,     40,  -3123],
       [-10312,  -9386,  36668,  14367,  -2035,    102],
       [ -2511, -19116,  30834,  14060,   1028,     61],
       [  -605, -20022,  29518,  12397,   1712,  -1351]], dtype=int64)

In [16]:
y_train.shape

(5, 6)

In [17]:
x_train = x_train.reshape(-1, d)
y_train = y_train.ravel()

In [18]:
x_train

array([[ 21342,  25789,  14501,   4535,   2287],
       [-11431, -19638,   8212,  23052,   9339],
       [ 14215,  11371,  17623,   4082,   7967],
       [  7457,   2893,   7461,   6863,   7192],
       [  1211,   1195,    -18,   2899,    804],
       [  -479,  -1055,   1913,  -1579,  -1829],
       [ 25789,  14501,   4535,   2287,    455],
       [-19638,   8212,  23052,   9339,   2959],
       [ 11371,  17623,   4082,   7967,   8077],
       [  2893,   7461,   6863,   7192,   7351],
       [  1195,    -18,   2899,    804,    796],
       [ -1055,   1913,  -1579,  -1829,  -1131],
       [ 14501,   4535,   2287,    455,  -4780],
       [  8212,  23052,   9339,   2959,   3952],
       [ 17623,   4082,   7967,   8077,   8799],
       [  7461,   6863,   7192,   7351,   7948],
       [   -18,   2899,    804,    796,     40],
       [  1913,  -1579,  -1829,  -1131,  -3123],
       [  4535,   2287,    455,  -4780, -10312],
       [ 23052,   9339,   2959,   3952,  -9386],
       [  4082,   79

In [19]:
y_train

array([   455,   2959,   8077,   7351,    796,  -1131,  -4780,   3952,
         8799,   7948,     40,  -3123, -10312,  -9386,  36668,  14367,
        -2035,    102,  -2511, -19116,  30834,  14060,   1028,     61,
         -605, -20022,  29518,  12397,   1712,  -1351], dtype=int64)

In [20]:
from xgboost import XGBRegressor
xgbr = XGBRegressor(n_estimators=100 , max_depth=3 , learning_rate=0.1, subsample=1, colsample_bynode=0.8, reg_lambda=1e-05)
xgbr.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.8, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1e-05, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [21]:
# 計算各個城市的MAPE
box1 = []
for i in range(len(y_train)):
    MAPE = abs((xgbr.predict(x_train)[i]-y_train[i])/y_train[i])
    box1.append(MAPE)

box2 = []
for j in range(6):
    num = 0
    for k in range(j, len(y_train), 6):
        num += box1[k]
    num = num/(len(y_train)/6)
    box2.append(num)

for a in range(6):
    print('MAPE為', box2[a])

MAPE為 0.05799790316075737
MAPE為 0.007084086357362231
MAPE為 0.0021841581065924665
MAPE為 0.010545778868278784
MAPE為 0.3971985345016662
MAPE為 0.32756797838867946


In [22]:
num = 0
for i in range(6):
    num += box2[i]
num /= 6
print('平均MAPE為', num)

平均MAPE為 0.13376307323055608


```
輸入為1D的平均MAPE為1.1039561391429267
輸入為2D的平均MAPE為0.506269489849788
輸入為3D的平均MAPE為0.42949836463760377
輸入為4D的平均MAPE為0.1128568005866772
輸入為5D的平均MAPE為0.13376307323055608
```

In [23]:
## 根據不同feature之間的權衡最後選出最佳的input維度，發現五維最好

## 選擇5D！！！

In [24]:
df2 = df1.copy()
df2

98     99    100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107  
million                 
New Taipei City   -605  
Taipei City     -20022  
Taoyuan City     29518  
Taichung City    12397  
Tainan City       1712  
Kaohsiung City   -1351

In [25]:
df2.iloc[:, -d:].values

array([[   455,  -4780, -10312,  -2511,   -605],
       [  2959,   3952,  -9386, -19116, -20022],
       [  8077,   8799,  36668,  30834,  29518],
       [  7351,   7948,  14367,  14060,  12397],
       [   796,     40,  -2035,   1028,   1712],
       [ -1131,  -3123,    102,     61,  -1351]], dtype=int64)

In [26]:
xgbr.predict(df2.iloc[:, -d:].values)

array([  -44.268562, -5783.7334  , 28950.07    , 12894.914   ,
         745.8818  , -1001.3824  ], dtype=float32)

In [27]:
df2['108'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107           108  
million                               
New Taipei City   -605    -44.268562  
Taipei City     -20022  -5783.733398  
Taoyuan City     29518  28950.070312  
Taichung City    12397  12894.914062  
Tainan City       1712    745.881775  
Kaohsiung City   -1351  -1001.382385

In [28]:
df2['109'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['110'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['111'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['112'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['113'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['114'] = xgbr.predict(df2.iloc[:, -d:].values)

In [29]:
df2

98     99    100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107           108           109           110  \
million                                                            
New Taipei City   -605    -44.268562  -1235.868774   -931.615662   
Taipei City     -20022  -5783.733398  -2081.816162   -919.074768   
Taoyuan City     29518  28950.070312  27582.150391  33543.054688   
Taichung City    12397  12894.914062  11433.698242  11620.074219   
Tainan City       1712    745.881775   -451.196564  -1010.445679   
Kaohsiung City   -1351  -1001.382385  -1001.303284   -921.642151   

                          111           112           113           114  
million                                                                  
New Taipei City  -1016.919250   -950.728699   -937.258301  -1086.686035  
Taipei City      -1081.014404  -1218.829712   -931.615662  -1016.919250  
Taoyuan City     33543.054688  33543.054688  33543.054688  33543.054688  
Taichung City    12798.934570  12502.767578  11808.082031  11718.594727  
Tainan City      -1251.627930    373.406158    400.795319   -549.970886  
Kaohsiung City    -937.258301   -974.175659  -1086.686035  -1071.069946

In [30]:
df3 = df2.iloc[:, 5:]

df3['103'] = xgbr.predict(df1.iloc[:, :5].values)
df3['104'] = xgbr.predict(df1.iloc[:, 1:6].values)
df3['105'] = xgbr.predict(df1.iloc[:, 2:7].values)
df3['106'] = xgbr.predict(df1.iloc[:, 3:8].values)
df3['107'] = xgbr.predict(df1.iloc[:, 4:9].values)

df3 = df3.T
df3.index = list(range(2014, 2026))

df1 = df1.T
df1.index = list(range(2009, 2019))

outputpath='C:/Users/Steven/Desktop/折線圖/immigration_predict.xlsx'
df3.to_excel(outputpath,index=True,header=True)

outputpath='C:/Users/Steven/Desktop/折線圖/immigration_origin.xlsx'
df1.to_excel(outputpath,index=True,header=True)