In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottle

In [3]:
df1 = pd.read_excel('per_capital_income_df.xlsx')
df1

Unnamed: 0             98      99     100     101     102     103  \
0  New Taipei City  265140.804598  273351  279239  278023  284783  291591   
1      Taipei City  387052.795031  402056  381561  398217  408688  412973   
2     Taoyuan City  268840.571429  272470  273295  287727  288668  314701   
3    Taichung City  263142.638037  279324  265316  271157  282352  303365   
4      Tainan City  263413.109756  252184  245524  242163  261153  266012   
5   Kaohsiung City  291891.194969  311566  270996  283843  295244  300872   
6           Taiwan  473259.000000  524234  527186  537021  565198  607264   

      104     105     106     107     108  
0  305575  326152  337605  350606  371156  
1  426633  440278  436538  436489  458839  
2  311248  325471  327133  346623  357432  
3  311948  322806  337637  343713  352633  
4  269302  286254  293031  293762  305444  
5  319905  304104  321015  328911  331657  
6  633367  650854  667945  678233  687140

In [4]:
df1.columns

Index(['Unnamed: 0', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [5]:
df1.index = df1['Unnamed: 0']

In [6]:
df1.columns

Index(['Unnamed: 0', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [7]:
df1

Unnamed: 0             98      99     100     101  \
Unnamed: 0                                                                
New Taipei City  New Taipei City  265140.804598  273351  279239  278023   
Taipei City          Taipei City  387052.795031  402056  381561  398217   
Taoyuan City        Taoyuan City  268840.571429  272470  273295  287727   
Taichung City      Taichung City  263142.638037  279324  265316  271157   
Tainan City          Tainan City  263413.109756  252184  245524  242163   
Kaohsiung City    Kaohsiung City  291891.194969  311566  270996  283843   
Taiwan                    Taiwan  473259.000000  524234  527186  537021   

                    102     103     104     105     106     107     108  
Unnamed: 0                                                               
New Taipei City  284783  291591  305575  326152  337605  350606  371156  
Taipei City      408688  412973  426633  440278  436538  436489  458839  
Taoyuan City     288668  314701  311248  325471  327133  346623  357432  
Taichung City    282352  303365  311948  322806  337637  343713  352633  
Tainan City      261153  266012  269302  286254  293031  293762  305444  
Kaohsiung City   295244  300872  319905  304104  321015  328911  331657  
Taiwan           565198  607264  633367  650854  667945  678233  687140

In [8]:
df1 = df1.iloc[:-1, 1:-1]
df1

98      99      100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107  
Unnamed: 0                                       
New Taipei City  305575  326152  337605  350606  
Taipei City      426633  440278  436538  436489  
Taoyuan City     311248  325471  327133  346623  
Taichung City    311948  322806  337637  343713  
Tainan City      269302  286254  293031  293762  
Kaohsiung City   319905  304104  321015  328911

In [9]:
col = []
for i in df1.columns:
    col.append(str(i))
col

['98', '99', '100', '101', '102', '103', '104', '105', '106', '107']

In [10]:
df1.columns = col
df1

98      99     100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107  
Unnamed: 0                                       
New Taipei City  305575  326152  337605  350606  
Taipei City      426633  440278  436538  436489  
Taoyuan City     311248  325471  327133  346623  
Taichung City    311948  322806  337637  343713  
Tainan City      269302  286254  293031  293762  
Kaohsiung City   319905  304104  321015  328911

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, New Taipei City to Kaohsiung City
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   98      6 non-null      float64
 1   99      6 non-null      int64  
 2   100     6 non-null      int64  
 3   101     6 non-null      int64  
 4   102     6 non-null      int64  
 5   103     6 non-null      int64  
 6   104     6 non-null      int64  
 7   105     6 non-null      int64  
 8   106     6 non-null      int64  
 9   107     6 non-null      int64  
dtypes: float64(1), int64(9)
memory usage: 528.0+ bytes


### input為n維

In [12]:
d = int(input('輸入的維度：'))
x_train = []
y_train = []


for i in range(10-d):
    x_train.append([])
    y_train.append([])
    
for j in range(10-d):
    x_train[j] = (df1.iloc[:, j:d+j].values)
    y_train[j] = (df1.iloc[:, d+j].values)

輸入的維度：5


In [13]:
x_train = np.array(x_train)
y_train = np.array(y_train)

In [14]:
x_train

array([[[265140.8045977 , 273351.        , 279239.        ,
         278023.        , 284783.        ],
        [387052.79503106, 402056.        , 381561.        ,
         398217.        , 408688.        ],
        [268840.57142857, 272470.        , 273295.        ,
         287727.        , 288668.        ],
        [263142.63803681, 279324.        , 265316.        ,
         271157.        , 282352.        ],
        [263413.1097561 , 252184.        , 245524.        ,
         242163.        , 261153.        ],
        [291891.19496855, 311566.        , 270996.        ,
         283843.        , 295244.        ]],

       [[273351.        , 279239.        , 278023.        ,
         284783.        , 291591.        ],
        [402056.        , 381561.        , 398217.        ,
         408688.        , 412973.        ],
        [272470.        , 273295.        , 287727.        ,
         288668.        , 314701.        ],
        [279324.        , 265316.        , 271157.        ,
  

In [15]:
x_train.shape

(5, 6, 5)

In [16]:
y_train

array([[291591, 412973, 314701, 303365, 266012, 300872],
       [305575, 426633, 311248, 311948, 269302, 319905],
       [326152, 440278, 325471, 322806, 286254, 304104],
       [337605, 436538, 327133, 337637, 293031, 321015],
       [350606, 436489, 346623, 343713, 293762, 328911]], dtype=int64)

In [17]:
y_train.shape

(5, 6)

In [18]:
x_train = x_train.reshape(-1, d)
y_train = y_train.ravel()

In [19]:
x_train

array([[265140.8045977 , 273351.        , 279239.        ,
        278023.        , 284783.        ],
       [387052.79503106, 402056.        , 381561.        ,
        398217.        , 408688.        ],
       [268840.57142857, 272470.        , 273295.        ,
        287727.        , 288668.        ],
       [263142.63803681, 279324.        , 265316.        ,
        271157.        , 282352.        ],
       [263413.1097561 , 252184.        , 245524.        ,
        242163.        , 261153.        ],
       [291891.19496855, 311566.        , 270996.        ,
        283843.        , 295244.        ],
       [273351.        , 279239.        , 278023.        ,
        284783.        , 291591.        ],
       [402056.        , 381561.        , 398217.        ,
        408688.        , 412973.        ],
       [272470.        , 273295.        , 287727.        ,
        288668.        , 314701.        ],
       [279324.        , 265316.        , 271157.        ,
        282352.        

In [20]:
y_train

array([291591, 412973, 314701, 303365, 266012, 300872, 305575, 426633,
       311248, 311948, 269302, 319905, 326152, 440278, 325471, 322806,
       286254, 304104, 337605, 436538, 327133, 337637, 293031, 321015,
       350606, 436489, 346623, 343713, 293762, 328911], dtype=int64)

In [21]:
from xgboost import XGBRegressor
xgbr = XGBRegressor(n_estimators=100 , max_depth=3 , learning_rate=0.1, subsample=1, colsample_bynode=0.8, reg_lambda=1e-05)
xgbr.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.8, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1e-05, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [22]:
# 計算各個城市的MAPE
box1 = []
for i in range(len(y_train)):
    MAPE = abs((xgbr.predict(x_train)[i]-y_train[i])/y_train[i])
    box1.append(MAPE)

box2 = []
for j in range(6):
    num = 0
    for k in range(j, len(y_train), 6):
        num += box1[k]
    num = num/(len(y_train)/6)
    box2.append(num)

for a in range(6):
    print('MAPE為', box2[a])

MAPE為 0.0005558886165721469
MAPE為 0.00012990446652541327
MAPE為 0.0007034141891894665
MAPE為 0.0005852395354242712
MAPE為 0.0003204240487699439
MAPE為 0.0005117453168630491


In [23]:
num = 0
for i in range(6):
    num += box2[i]
num /= 6
print('平均MAPE為', num)

平均MAPE為 0.0004677693622240485


```
輸入為1D的平均MAPE為0.006578524831687808
輸入為2D的平均MAPE為0.003901218265631964
輸入為3D的平均MAPE為0.0014871487434951853
輸入為4D的平均MAPE為0.0007969000200642263
輸入為5D的平均MAPE為0.0004677693622240485
```

In [24]:
## 根據不同feature之間的權衡最後選出最佳的input維度，發現五維最好

## 選擇5D！！！

In [25]:
df2 = df1.copy()
df2

98      99     100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107  
Unnamed: 0                                       
New Taipei City  305575  326152  337605  350606  
Taipei City      426633  440278  436538  436489  
Taoyuan City     311248  325471  327133  346623  
Taichung City    311948  322806  337637  343713  
Tainan City      269302  286254  293031  293762  
Kaohsiung City   319905  304104  321015  328911

In [26]:
df2.iloc[:, -d:].values

array([[291591, 305575, 326152, 337605, 350606],
       [412973, 426633, 440278, 436538, 436489],
       [314701, 311248, 325471, 327133, 346623],
       [303365, 311948, 322806, 337637, 343713],
       [266012, 269302, 286254, 293031, 293762],
       [300872, 319905, 304104, 321015, 328911]], dtype=int64)

In [27]:
xgbr.predict(df2.iloc[:, -d:].values)

array([350481.53, 436446.25, 350505.47, 350505.47, 312373.78, 338959.25],
      dtype=float32)

In [28]:
df2['108'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98      99     100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107           108  
Unnamed: 0                                                     
New Taipei City  305575  326152  337605  350606  350481.53125  
Taipei City      426633  440278  436538  436489  436446.25000  
Taoyuan City     311248  325471  327133  346623  350505.46875  
Taichung City    311948  322806  337637  343713  350505.46875  
Tainan City      269302  286254  293031  293762  312373.78125  
Kaohsiung City   319905  304104  321015  328911  338959.25000

In [29]:
df2['109'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['110'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['111'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['112'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['113'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['114'] = xgbr.predict(df2.iloc[:, -d:].values)

In [30]:
df2

98      99     100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107           108           109  \
Unnamed: 0                                                                    
New Taipei City  305575  326152  337605  350606  350481.53125  350505.46875   
Taipei City      426633  440278  436538  436489  436446.25000  436446.25000   
Taoyuan City     311248  325471  327133  346623  350505.46875  350505.46875   
Taichung City    311948  322806  337637  343713  350505.46875  350505.46875   
Tainan City      269302  286254  293031  293762  312373.78125  309012.37500   
Kaohsiung City   319905  304104  321015  328911  338959.25000  350505.46875   

                          110           111           112           113  \
Unnamed: 0                                                                
New Taipei City  350505.46875  360404.40625  414483.37500  414483.37500   
Taipei City      436446.25000  436446.25000  436446.25000  436446.25000   
Taoyuan City     350505.46875  350537.06250  414483.37500  414483.37500   
Taichung City    350505.46875  355450.84375  361511.03125  414483.37500   
Tainan City      322307.81250  328295.18750  343522.53125  350505.46875   
Kaohsiung City   350505.46875  350505.46875  350505.46875  361526.62500   

                          114  
Unnamed: 0                     
New Taipei City  418004.81250  
Taipei City      436446.25000  
Taoyuan City     418004.81250  
Taichung City    414483.37500  
Tainan City      350505.46875  
Kaohsiung City   414483.37500

In [31]:
outputpath='C:/Users/Steven/Desktop/新增資料夾/income_update.xlsx'
df2.to_excel(outputpath,index=True,header=True)