In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottle

In [3]:
df1 = pd.read_excel('population_df.xlsx')
df1

location        98        99       100       101       102  \
0  New Taipei City   3873653   3897367   3916451   3939305   3954929   
1      Taipei City   2607428   2618772   2650968   2673226   2686516   
2     Taoyuan City   1978782   2002060   2013305   2030161   2044023   
3    Taichung City   2635761   2648419   2664394   2684893   2701661   
4      Tainan City   1875406   1873794   1876960   1881645   1883208   
5   Kaohsiung City   2770887   2773483   2774470   2778659   2779877   
6           Taiwan  23119772  23162123  23224912  23315822  23373517   

        103       104       105       106       107       108  
0   3966818   3970644   3979208   3986689   3995717   4018696  
1   2702315   2704810   2695704   2683257   2668572   2645041  
2   2058328   2105780   2147763   2188017   2220872   2249037  
3   2719835   2744445   2767239   2787070   2803894   2815261  
4   1884284   1885541   1886033   1886522   1883831   1880906  
5   2778992   2778918   2779371   2776912   2773533   2773198  
6  23433753  23492074  23539816  23571227  23588932  23603121

In [4]:
df1.columns

Index(['location', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [5]:
df1.index = df1['location']

In [6]:
df1.columns

Index(['location', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [7]:
df1

location        98        99       100       101  \
location                                                                   
New Taipei City  New Taipei City   3873653   3897367   3916451   3939305   
Taipei City          Taipei City   2607428   2618772   2650968   2673226   
Taoyuan City        Taoyuan City   1978782   2002060   2013305   2030161   
Taichung City      Taichung City   2635761   2648419   2664394   2684893   
Tainan City          Tainan City   1875406   1873794   1876960   1881645   
Kaohsiung City    Kaohsiung City   2770887   2773483   2774470   2778659   
Taiwan                    Taiwan  23119772  23162123  23224912  23315822   

                      102       103       104       105       106       107  \
location                                                                      
New Taipei City   3954929   3966818   3970644   3979208   3986689   3995717   
Taipei City       2686516   2702315   2704810   2695704   2683257   2668572   
Taoyuan City      2044023   2058328   2105780   2147763   2188017   2220872   
Taichung City     2701661   2719835   2744445   2767239   2787070   2803894   
Tainan City       1883208   1884284   1885541   1886033   1886522   1883831   
Kaohsiung City    2779877   2778992   2778918   2779371   2776912   2773533   
Taiwan           23373517  23433753  23492074  23539816  23571227  23588932   

                      108  
location                   
New Taipei City   4018696  
Taipei City       2645041  
Taoyuan City      2249037  
Taichung City     2815261  
Tainan City       1880906  
Kaohsiung City    2773198  
Taiwan           23603121

In [8]:
df1 = df1.iloc[:-1, 1:-1]
df1

98       99       100      101      102      103  \
location                                                                
New Taipei City  3873653  3897367  3916451  3939305  3954929  3966818   
Taipei City      2607428  2618772  2650968  2673226  2686516  2702315   
Taoyuan City     1978782  2002060  2013305  2030161  2044023  2058328   
Taichung City    2635761  2648419  2664394  2684893  2701661  2719835   
Tainan City      1875406  1873794  1876960  1881645  1883208  1884284   
Kaohsiung City   2770887  2773483  2774470  2778659  2779877  2778992   

                     104      105      106      107  
location                                             
New Taipei City  3970644  3979208  3986689  3995717  
Taipei City      2704810  2695704  2683257  2668572  
Taoyuan City     2105780  2147763  2188017  2220872  
Taichung City    2744445  2767239  2787070  2803894  
Tainan City      1885541  1886033  1886522  1883831  
Kaohsiung City   2778918  2779371  2776912  2773533

In [9]:
col = []
for i in df1.columns:
    col.append(str(i))
col

['98', '99', '100', '101', '102', '103', '104', '105', '106', '107']

In [10]:
df1.columns = col
df1

98       99      100      101      102      103  \
location                                                                
New Taipei City  3873653  3897367  3916451  3939305  3954929  3966818   
Taipei City      2607428  2618772  2650968  2673226  2686516  2702315   
Taoyuan City     1978782  2002060  2013305  2030161  2044023  2058328   
Taichung City    2635761  2648419  2664394  2684893  2701661  2719835   
Tainan City      1875406  1873794  1876960  1881645  1883208  1884284   
Kaohsiung City   2770887  2773483  2774470  2778659  2779877  2778992   

                     104      105      106      107  
location                                             
New Taipei City  3970644  3979208  3986689  3995717  
Taipei City      2704810  2695704  2683257  2668572  
Taoyuan City     2105780  2147763  2188017  2220872  
Taichung City    2744445  2767239  2787070  2803894  
Tainan City      1885541  1886033  1886522  1883831  
Kaohsiung City   2778918  2779371  2776912  2773533

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, New Taipei City to Kaohsiung City
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   98      6 non-null      int64
 1   99      6 non-null      int64
 2   100     6 non-null      int64
 3   101     6 non-null      int64
 4   102     6 non-null      int64
 5   103     6 non-null      int64
 6   104     6 non-null      int64
 7   105     6 non-null      int64
 8   106     6 non-null      int64
 9   107     6 non-null      int64
dtypes: int64(10)
memory usage: 528.0+ bytes


### input為n維

In [12]:
d = int(input('輸入的維度：'))
x_train = []
y_train = []


for i in range(10-d):
    x_train.append([])
    y_train.append([])
    
for j in range(10-d):
    x_train[j] = (df1.iloc[:, j:d+j].values)
    y_train[j] = (df1.iloc[:, d+j].values)

輸入的維度：5


In [13]:
x_train = np.array(x_train)
y_train = np.array(y_train)

In [14]:
x_train

array([[[3873653, 3897367, 3916451, 3939305, 3954929],
        [2607428, 2618772, 2650968, 2673226, 2686516],
        [1978782, 2002060, 2013305, 2030161, 2044023],
        [2635761, 2648419, 2664394, 2684893, 2701661],
        [1875406, 1873794, 1876960, 1881645, 1883208],
        [2770887, 2773483, 2774470, 2778659, 2779877]],

       [[3897367, 3916451, 3939305, 3954929, 3966818],
        [2618772, 2650968, 2673226, 2686516, 2702315],
        [2002060, 2013305, 2030161, 2044023, 2058328],
        [2648419, 2664394, 2684893, 2701661, 2719835],
        [1873794, 1876960, 1881645, 1883208, 1884284],
        [2773483, 2774470, 2778659, 2779877, 2778992]],

       [[3916451, 3939305, 3954929, 3966818, 3970644],
        [2650968, 2673226, 2686516, 2702315, 2704810],
        [2013305, 2030161, 2044023, 2058328, 2105780],
        [2664394, 2684893, 2701661, 2719835, 2744445],
        [1876960, 1881645, 1883208, 1884284, 1885541],
        [2774470, 2778659, 2779877, 2778992, 2778918]],

    

In [15]:
x_train.shape

(5, 6, 5)

In [16]:
y_train

array([[3966818, 2702315, 2058328, 2719835, 1884284, 2778992],
       [3970644, 2704810, 2105780, 2744445, 1885541, 2778918],
       [3979208, 2695704, 2147763, 2767239, 1886033, 2779371],
       [3986689, 2683257, 2188017, 2787070, 1886522, 2776912],
       [3995717, 2668572, 2220872, 2803894, 1883831, 2773533]],
      dtype=int64)

In [17]:
y_train.shape

(5, 6)

In [18]:
x_train = x_train.reshape(-1, d)
y_train = y_train.ravel()

In [19]:
x_train

array([[3873653, 3897367, 3916451, 3939305, 3954929],
       [2607428, 2618772, 2650968, 2673226, 2686516],
       [1978782, 2002060, 2013305, 2030161, 2044023],
       [2635761, 2648419, 2664394, 2684893, 2701661],
       [1875406, 1873794, 1876960, 1881645, 1883208],
       [2770887, 2773483, 2774470, 2778659, 2779877],
       [3897367, 3916451, 3939305, 3954929, 3966818],
       [2618772, 2650968, 2673226, 2686516, 2702315],
       [2002060, 2013305, 2030161, 2044023, 2058328],
       [2648419, 2664394, 2684893, 2701661, 2719835],
       [1873794, 1876960, 1881645, 1883208, 1884284],
       [2773483, 2774470, 2778659, 2779877, 2778992],
       [3916451, 3939305, 3954929, 3966818, 3970644],
       [2650968, 2673226, 2686516, 2702315, 2704810],
       [2013305, 2030161, 2044023, 2058328, 2105780],
       [2664394, 2684893, 2701661, 2719835, 2744445],
       [1876960, 1881645, 1883208, 1884284, 1885541],
       [2774470, 2778659, 2779877, 2778992, 2778918],
       [3939305, 3954929, 39

In [20]:
y_train

array([3966818, 2702315, 2058328, 2719835, 1884284, 2778992, 3970644,
       2704810, 2105780, 2744445, 1885541, 2778918, 3979208, 2695704,
       2147763, 2767239, 1886033, 2779371, 3986689, 2683257, 2188017,
       2787070, 1886522, 2776912, 3995717, 2668572, 2220872, 2803894,
       1883831, 2773533], dtype=int64)

In [21]:
from xgboost import XGBRegressor
xgbr = XGBRegressor(n_estimators=100 , max_depth=3 , learning_rate=0.1, subsample=1, colsample_bynode=0.8, reg_lambda=1e-05)
xgbr.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.8, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1e-05, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [22]:
# 計算各個城市的MAPE
box1 = []
for i in range(len(y_train)):
    MAPE = abs((xgbr.predict(x_train)[i]-y_train[i])/y_train[i])
    box1.append(MAPE)

box2 = []
for j in range(6):
    num = 0
    for k in range(j, len(y_train), 6):
        num += box1[k]
    num = num/(len(y_train)/6)
    box2.append(num)

for a in range(6):
    print('MAPE為', box2[a])

MAPE為 4.143547835438007e-05
MAPE為 8.859777125492419e-05
MAPE為 4.5879147122111855e-05
MAPE為 0.00014239131520397906
MAPE為 0.00015176894081620935
MAPE為 4.5840505497645744e-05


In [23]:
num = 0
for i in range(6):
    num += box2[i]
num /= 6
print('平均MAPE為', num)

平均MAPE為 8.598552637487503e-05


```
輸入為1D的平均MAPE為0.00034769577368515357
輸入為2D的平均MAPE為0.0003215915252817078
輸入為3D的平均MAPE為0.0001684424747412501
輸入為4D的平均MAPE為0.00011735776130127511
輸入為5D的平均MAPE為0.00008598552637487503
```

In [24]:
## 根據不同feature之間的權衡最後選出最佳的input維度，發現五維最好

## 選擇5D！！！

In [25]:
df2 = df1.copy()
df2

98       99      100      101      102      103  \
location                                                                
New Taipei City  3873653  3897367  3916451  3939305  3954929  3966818   
Taipei City      2607428  2618772  2650968  2673226  2686516  2702315   
Taoyuan City     1978782  2002060  2013305  2030161  2044023  2058328   
Taichung City    2635761  2648419  2664394  2684893  2701661  2719835   
Tainan City      1875406  1873794  1876960  1881645  1883208  1884284   
Kaohsiung City   2770887  2773483  2774470  2778659  2779877  2778992   

                     104      105      106      107  
location                                             
New Taipei City  3970644  3979208  3986689  3995717  
Taipei City      2704810  2695704  2683257  2668572  
Taoyuan City     2105780  2147763  2188017  2220872  
Taichung City    2744445  2767239  2787070  2803894  
Tainan City      1885541  1886033  1886522  1883831  
Kaohsiung City   2778918  2779371  2776912  2773533

In [26]:
df2.iloc[:, -d:].values

array([[3966818, 3970644, 3979208, 3986689, 3995717],
       [2702315, 2704810, 2695704, 2683257, 2668572],
       [2058328, 2105780, 2147763, 2188017, 2220872],
       [2719835, 2744445, 2767239, 2787070, 2803894],
       [1884284, 1885541, 1886033, 1886522, 1883831],
       [2778992, 2778918, 2779371, 2776912, 2773533]], dtype=int64)

In [27]:
xgbr.predict(df2.iloc[:, -d:].values)

array([3995496.2, 2668510. , 2220990. , 2803773. , 1884398.4, 2776696.5],
      dtype=float32)

In [28]:
df2['108'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98       99      100      101      102      103  \
location                                                                
New Taipei City  3873653  3897367  3916451  3939305  3954929  3966818   
Taipei City      2607428  2618772  2650968  2673226  2686516  2702315   
Taoyuan City     1978782  2002060  2013305  2030161  2044023  2058328   
Taichung City    2635761  2648419  2664394  2684893  2701661  2719835   
Tainan City      1875406  1873794  1876960  1881645  1883208  1884284   
Kaohsiung City   2770887  2773483  2774470  2778659  2779877  2778992   

                     104      105      106      107          108  
location                                                          
New Taipei City  3970644  3979208  3986689  3995717  3995496.250  
Taipei City      2704810  2695704  2683257  2668572  2668510.000  
Taoyuan City     2105780  2147763  2188017  2220872  2220990.000  
Taichung City    2744445  2767239  2787070  2803894  2803773.000  
Tainan City      1885541  1886033  1886522  1883831  1884398.375  
Kaohsiung City   2778918  2779371  2776912  2773533  2776696.500

In [29]:
df2['109'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['110'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['111'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['112'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['113'] = xgbr.predict(df2.iloc[:, -d:].values)
df2['114'] = xgbr.predict(df2.iloc[:, -d:].values)

In [30]:
df2

98       99      100      101      102      103  \
location                                                                
New Taipei City  3873653  3897367  3916451  3939305  3954929  3966818   
Taipei City      2607428  2618772  2650968  2673226  2686516  2702315   
Taoyuan City     1978782  2002060  2013305  2030161  2044023  2058328   
Taichung City    2635761  2648419  2664394  2684893  2701661  2719835   
Tainan City      1875406  1873794  1876960  1881645  1883208  1884284   
Kaohsiung City   2770887  2773483  2774470  2778659  2779877  2778992   

                     104      105      106      107          108          109  \
location                                                                        
New Taipei City  3970644  3979208  3986689  3995717  3995496.250  3995496.250   
Taipei City      2704810  2695704  2683257  2668572  2668510.000  2668510.000   
Taoyuan City     2105780  2147763  2188017  2220872  2220990.000  2220990.000   
Taichung City    2744445  2767239  2787070  2803894  2803773.000  2801937.000   
Tainan City      1885541  1886033  1886522  1883831  1884398.375  1884398.375   
Kaohsiung City   2778918  2779371  2776912  2773533  2776696.500  2776696.500   

                         110          111          112          113  \
location                                                              
New Taipei City  3995496.250  3995496.250  3995496.250  3995496.250   
Taipei City      2669673.500  2669578.750  2669496.500  2668333.000   
Taoyuan City     2220990.000  2220990.000  2220990.000  2220990.000   
Taichung City    2801545.500  2798525.000  2798525.000  2798525.000   
Tainan City      1884398.375  1884398.375  1884398.375  1884398.375   
Kaohsiung City   2774594.250  2777458.500  2778657.750  2777738.250   

                         114  
location                      
New Taipei City  3995496.250  
Taipei City      2668333.000  
Taoyuan City     2220990.000  
Taichung City    2798525.000  
Tainan City      1884398.375  
Kaohsiung City   2777428.750

In [31]:
outputpath='C:/Users/Steven/Desktop/新增資料夾/population_update.xlsx'
df2.to_excel(outputpath,index=True,header=True)