In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottle

In [3]:
df1 = pd.read_excel('birth_df.xlsx')
df1

million      98      99     100     101     102     103     104  \
0  New Taipei City   32255   32093   27617   34323   22854   35915   38604   
1      Taipei City   20691   19403   18530   25132   22258   26710   29024   
2     Taoyuan City   19180   18515   15838   18041   16856   16757   17360   
3    Taichung City   23647   22601   19537   24027   20499   24555   26194   
4      Tainan City   14773   14196   11612   14208   17752   14788   15426   
5   Kaohsiung City   22182   11116   18684   21411   24963   21626   22520   
6           Taiwan  191310  166886  196627  229481  199113  210383  213598   

      105     106     107  108  
0   36313   34331   31611  NaN  
1   28987   27992   25042  NaN  
2   22384   23786   23356  NaN  
3   26313   25655   24338  NaN  
4   22469   14698   13773  NaN  
5   12044   21757   20260  NaN  
6  208440  193844  181601  NaN

In [4]:
df1.index = df1['million']

In [5]:
df1.columns

Index(['million', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [6]:
df1

million      98      99     100     101     102  \
million                                                                    
New Taipei City  New Taipei City   32255   32093   27617   34323   22854   
Taipei City          Taipei City   20691   19403   18530   25132   22258   
Taoyuan City        Taoyuan City   19180   18515   15838   18041   16856   
Taichung City      Taichung City   23647   22601   19537   24027   20499   
Tainan City          Tainan City   14773   14196   11612   14208   17752   
Kaohsiung City    Kaohsiung City   22182   11116   18684   21411   24963   
Taiwan                    Taiwan  191310  166886  196627  229481  199113   

                    103     104     105     106     107  108  
million                                                       
New Taipei City   35915   38604   36313   34331   31611  NaN  
Taipei City       26710   29024   28987   27992   25042  NaN  
Taoyuan City      16757   17360   22384   23786   23356  NaN  
Taichung City     24555   26194   26313   25655   24338  NaN  
Tainan City       14788   15426   22469   14698   13773  NaN  
Kaohsiung City    21626   22520   12044   21757   20260  NaN  
Taiwan           210383  213598  208440  193844  181601  NaN

In [7]:
df1 = df1.iloc[:-1, 1:-1]
df1

98     99     100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107  
million                        
New Taipei City  34331  31611  
Taipei City      27992  25042  
Taoyuan City     23786  23356  
Taichung City    25655  24338  
Tainan City      14698  13773  
Kaohsiung City   21757  20260

In [8]:
col = []
for i in df1.columns:
    col.append(str(i))
col

['98', '99', '100', '101', '102', '103', '104', '105', '106', '107']

In [9]:
df1.columns = col
df1

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107  
million                        
New Taipei City  34331  31611  
Taipei City      27992  25042  
Taoyuan City     23786  23356  
Taichung City    25655  24338  
Tainan City      14698  13773  
Kaohsiung City   21757  20260

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, New Taipei City to Kaohsiung City
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   98      6 non-null      int64
 1   99      6 non-null      int64
 2   100     6 non-null      int64
 3   101     6 non-null      int64
 4   102     6 non-null      int64
 5   103     6 non-null      int64
 6   104     6 non-null      int64
 7   105     6 non-null      int64
 8   106     6 non-null      int64
 9   107     6 non-null      int64
dtypes: int64(10)
memory usage: 528.0+ bytes


In [11]:
df1

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107  
million                        
New Taipei City  34331  31611  
Taipei City      27992  25042  
Taoyuan City     23786  23356  
Taichung City    25655  24338  
Tainan City      14698  13773  
Kaohsiung City   21757  20260

In [12]:
min = df1.min().min()
rangeing = (df1.max().max())-(df1.min().min())
print(min)
print(rangeing)

11116
27488


In [13]:
for i in range(len(df1)):
    for j in range(len(df1.columns)):
        df1.iloc[i, j] = (df1.iloc[i, j]-min)/rangeing

### input為2維

In [14]:
d = int(input('輸入的維度：'))
x_train = []
y_train = []
x_test = []
y_test = []

for a in range(2):
    x_test.append([])
    y_test.append([])

for b in range(8-d):
    x_train.append([])
    y_train.append([])
    
for i in range(2):
    x_test[i] = (df1.iloc[:, -2-d+i:-2+i].values)
    y_test[i] = (df1.iloc[:, -2+i].values)

for j in range(8-d):
    x_train[j] = (df1.iloc[:, j:d+j].values)
    y_train[j] = (df1.iloc[:, d+j].values)

輸入的維度：2


In [15]:
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)

In [16]:
x_train

array([[[0.76902648, 0.763133  ],
        [0.34833382, 0.30147701],
        [0.29336438, 0.269172  ],
        [0.45587165, 0.41781868],
        [0.13303987, 0.11204889],
        [0.40257567, 0.        ]],

       [[0.763133  , 0.60029831],
        [0.30147701, 0.26971769],
        [0.269172  , 0.17178405],
        [0.41781868, 0.30635186],
        [0.11204889, 0.01804424],
        [0.        , 0.27532014]],

       [[0.60029831, 0.84425931],
        [0.26971769, 0.50989523],
        [0.17178405, 0.25192811],
        [0.30635186, 0.46969587],
        [0.01804424, 0.11248545],
        [0.27532014, 0.37452707]],

       [[0.84425931, 0.4270227 ],
        [0.50989523, 0.40534051],
        [0.25192811, 0.20881839],
        [0.46969587, 0.34134895],
        [0.11248545, 0.24141444],
        [0.37452707, 0.50374709]],

       [[0.4270227 , 0.90217549],
        [0.40534051, 0.5673021 ],
        [0.20881839, 0.20521682],
        [0.34134895, 0.48890425],
        [0.24141444, 0.13358556],
      

In [17]:
x_train.shape

(6, 6, 2)

In [18]:
y_train

array([[0.60029831, 0.26971769, 0.17178405, 0.30635186, 0.01804424,
        0.27532014],
       [0.84425931, 0.50989523, 0.25192811, 0.46969587, 0.11248545,
        0.37452707],
       [0.4270227 , 0.40534051, 0.20881839, 0.34134895, 0.24141444,
        0.50374709],
       [0.90217549, 0.5673021 , 0.20521682, 0.48890425, 0.13358556,
        0.38234866],
       [1.        , 0.65148428, 0.22715367, 0.54853027, 0.15679569,
        0.41487194],
       [0.91665454, 0.65013824, 0.40992433, 0.55285943, 0.41301659,
        0.03376019]])

In [19]:
y_train.shape

(6, 6)

In [20]:
x_test

array([[[1.        , 0.91665454],
        [0.65148428, 0.65013824],
        [0.22715367, 0.40992433],
        [0.54853027, 0.55285943],
        [0.15679569, 0.41301659],
        [0.41487194, 0.03376019]],

       [[0.91665454, 0.84455035],
        [0.65013824, 0.61394063],
        [0.40992433, 0.46092841],
        [0.55285943, 0.52892171],
        [0.41301659, 0.13031141],
        [0.03376019, 0.38711438]]])

In [21]:
y_test

array([[0.84455035, 0.61394063, 0.46092841, 0.52892171, 0.13031141,
        0.38711438],
       [0.74559808, 0.50662107, 0.44528522, 0.4810099 , 0.09666036,
        0.33265425]])

In [22]:
x_train = x_train.reshape(-1, d)
y_train = y_train.ravel()
x_test = x_test.reshape(-1, d)
y_test = y_test.ravel()

In [23]:
x_train

array([[0.76902648, 0.763133  ],
       [0.34833382, 0.30147701],
       [0.29336438, 0.269172  ],
       [0.45587165, 0.41781868],
       [0.13303987, 0.11204889],
       [0.40257567, 0.        ],
       [0.763133  , 0.60029831],
       [0.30147701, 0.26971769],
       [0.269172  , 0.17178405],
       [0.41781868, 0.30635186],
       [0.11204889, 0.01804424],
       [0.        , 0.27532014],
       [0.60029831, 0.84425931],
       [0.26971769, 0.50989523],
       [0.17178405, 0.25192811],
       [0.30635186, 0.46969587],
       [0.01804424, 0.11248545],
       [0.27532014, 0.37452707],
       [0.84425931, 0.4270227 ],
       [0.50989523, 0.40534051],
       [0.25192811, 0.20881839],
       [0.46969587, 0.34134895],
       [0.11248545, 0.24141444],
       [0.37452707, 0.50374709],
       [0.4270227 , 0.90217549],
       [0.40534051, 0.5673021 ],
       [0.20881839, 0.20521682],
       [0.34134895, 0.48890425],
       [0.24141444, 0.13358556],
       [0.50374709, 0.38234866],
       [0.

In [24]:
y_train

array([0.60029831, 0.26971769, 0.17178405, 0.30635186, 0.01804424,
       0.27532014, 0.84425931, 0.50989523, 0.25192811, 0.46969587,
       0.11248545, 0.37452707, 0.4270227 , 0.40534051, 0.20881839,
       0.34134895, 0.24141444, 0.50374709, 0.90217549, 0.5673021 ,
       0.20521682, 0.48890425, 0.13358556, 0.38234866, 1.        ,
       0.65148428, 0.22715367, 0.54853027, 0.15679569, 0.41487194,
       0.91665454, 0.65013824, 0.40992433, 0.55285943, 0.41301659,
       0.03376019])

In [25]:
from xgboost import XGBRegressor
xgbr = XGBRegressor(n_estimators=100 , max_depth=3 , learning_rate=0.1, subsample=1, colsample_bynode=0.8, reg_lambda=1e-05)
xgbr.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.8, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1e-05, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [26]:
xgbr.predict(x_test)

array([0.9649656 , 0.57823527, 0.3330757 , 0.62054926, 0.23488021,
       0.42129177, 0.7267354 , 0.57858294, 0.59372246, 0.62054926,
       0.40177584, 0.35444596], dtype=float32)

In [27]:
y_test

array([0.84455035, 0.61394063, 0.46092841, 0.52892171, 0.13031141,
       0.38711438, 0.74559808, 0.50662107, 0.44528522, 0.4810099 ,
       0.09666036, 0.33265425])

In [28]:
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    print('MAPE為', MAPE)

MAPE為 0.08393890499595572
MAPE為 0.1001002339630628
MAPE為 0.30536700961333396
MAPE為 0.23166564109008936
MAPE為 1.9795130271185497
MAPE為 0.07689809101456649


In [29]:
number = 0 
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    number += MAPE
number /= 6
print('平均MAPE為', number)

平均MAPE為 0.4629138179659263


In [30]:
df1

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.769026  0.763133  0.600298  0.844259  0.427023  0.902175   
Taipei City      0.348334  0.301477  0.269718  0.509895  0.405341  0.567302   
Taoyuan City     0.293364  0.269172  0.171784  0.251928  0.208818  0.205217   
Taichung City    0.455872  0.417819  0.306352  0.469696  0.341349  0.488904   
Tainan City      0.133040  0.112049  0.018044  0.112485  0.241414  0.133586   
Kaohsiung City   0.402576  0.000000  0.275320  0.374527  0.503747  0.382349   

                      104       105       106       107  
million                                                  
New Taipei City  1.000000  0.916655  0.844550  0.745598  
Taipei City      0.651484  0.650138  0.613941  0.506621  
Taoyuan City     0.227154  0.409924  0.460928  0.445285  
Taichung City    0.548530  0.552859  0.528922  0.481010  
Tainan City      0.156796  0.413017  0.130311  0.096660  
Kaohsiung City   0.414872  0.033760  0.387114  0.332654

In [31]:
df2 = df1.copy()
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.769026  0.763133  0.600298  0.844259  0.427023  0.902175   
Taipei City      0.348334  0.301477  0.269718  0.509895  0.405341  0.567302   
Taoyuan City     0.293364  0.269172  0.171784  0.251928  0.208818  0.205217   
Taichung City    0.455872  0.417819  0.306352  0.469696  0.341349  0.488904   
Tainan City      0.133040  0.112049  0.018044  0.112485  0.241414  0.133586   
Kaohsiung City   0.402576  0.000000  0.275320  0.374527  0.503747  0.382349   

                      104       105       106       107  
million                                                  
New Taipei City  1.000000  0.916655  0.844550  0.745598  
Taipei City      0.651484  0.650138  0.613941  0.506621  
Taoyuan City     0.227154  0.409924  0.460928  0.445285  
Taichung City    0.548530  0.552859  0.528922  0.481010  
Tainan City      0.156796  0.413017  0.130311  0.096660  
Kaohsiung City   0.414872  0.033760  0.387114  0.332654

In [32]:
df2.iloc[:, -d:].values

array([[0.84455035, 0.74559808],
       [0.61394063, 0.50662107],
       [0.46092841, 0.44528522],
       [0.52892171, 0.4810099 ],
       [0.13031141, 0.09666036],
       [0.38711438, 0.33265425]])

In [33]:
xgbr.predict(df2.iloc[:, -d:].values)

array([0.73383075, 0.55856586, 0.57814324, 0.62661326, 0.03652004,
       0.19684002], dtype=float32)

In [34]:
df2['108'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.769026  0.763133  0.600298  0.844259  0.427023  0.902175   
Taipei City      0.348334  0.301477  0.269718  0.509895  0.405341  0.567302   
Taoyuan City     0.293364  0.269172  0.171784  0.251928  0.208818  0.205217   
Taichung City    0.455872  0.417819  0.306352  0.469696  0.341349  0.488904   
Tainan City      0.133040  0.112049  0.018044  0.112485  0.241414  0.133586   
Kaohsiung City   0.402576  0.000000  0.275320  0.374527  0.503747  0.382349   

                      104       105       106       107       108  
million                                                            
New Taipei City  1.000000  0.916655  0.844550  0.745598  0.733831  
Taipei City      0.651484  0.650138  0.613941  0.506621  0.558566  
Taoyuan City     0.227154  0.409924  0.460928  0.445285  0.578143  
Taichung City    0.548530  0.552859  0.528922  0.481010  0.626613  
Tainan City      0.156796  0.413017  0.130311  0.096660  0.036520  
Kaohsiung City   0.414872  0.033760  0.387114  0.332654  0.196840

In [35]:
df2['109'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.769026  0.763133  0.600298  0.844259  0.427023  0.902175   
Taipei City      0.348334  0.301477  0.269718  0.509895  0.405341  0.567302   
Taoyuan City     0.293364  0.269172  0.171784  0.251928  0.208818  0.205217   
Taichung City    0.455872  0.417819  0.306352  0.469696  0.341349  0.488904   
Tainan City      0.133040  0.112049  0.018044  0.112485  0.241414  0.133586   
Kaohsiung City   0.402576  0.000000  0.275320  0.374527  0.503747  0.382349   

                      104       105       106       107       108       109  
million                                                                      
New Taipei City  1.000000  0.916655  0.844550  0.745598  0.733831  0.675852  
Taipei City      0.651484  0.650138  0.613941  0.506621  0.558566  0.570881  
Taoyuan City     0.227154  0.409924  0.460928  0.445285  0.578143  0.593622  
Taichung City    0.548530  0.552859  0.528922  0.481010  0.626613  0.597496  
Tainan City      0.156796  0.413017  0.130311  0.096660  0.036520  0.109625  
Kaohsiung City   0.414872  0.033760  0.387114  0.332654  0.196840  0.298164

In [36]:
df2['110'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.769026  0.763133  0.600298  0.844259  0.427023  0.902175   
Taipei City      0.348334  0.301477  0.269718  0.509895  0.405341  0.567302   
Taoyuan City     0.293364  0.269172  0.171784  0.251928  0.208818  0.205217   
Taichung City    0.455872  0.417819  0.306352  0.469696  0.341349  0.488904   
Tainan City      0.133040  0.112049  0.018044  0.112485  0.241414  0.133586   
Kaohsiung City   0.402576  0.000000  0.275320  0.374527  0.503747  0.382349   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  1.000000  0.916655  0.844550  0.745598  0.733831  0.675852   
Taipei City      0.651484  0.650138  0.613941  0.506621  0.558566  0.570881   
Taoyuan City     0.227154  0.409924  0.460928  0.445285  0.578143  0.593622   
Taichung City    0.548530  0.552859  0.528922  0.481010  0.626613  0.597496   
Tainan City      0.156796  0.413017  0.130311  0.096660  0.036520  0.109625   
Kaohsiung City   0.414872  0.033760  0.387114  0.332654  0.196840  0.298164   

                      110  
million                    
New Taipei City  0.831620  
Taipei City      0.631529  
Taoyuan City     0.643901  
Taichung City    0.578583  
Tainan City      0.166501  
Kaohsiung City   0.391264

In [37]:
df2['111'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.769026  0.763133  0.600298  0.844259  0.427023  0.902175   
Taipei City      0.348334  0.301477  0.269718  0.509895  0.405341  0.567302   
Taoyuan City     0.293364  0.269172  0.171784  0.251928  0.208818  0.205217   
Taichung City    0.455872  0.417819  0.306352  0.469696  0.341349  0.488904   
Tainan City      0.133040  0.112049  0.018044  0.112485  0.241414  0.133586   
Kaohsiung City   0.402576  0.000000  0.275320  0.374527  0.503747  0.382349   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  1.000000  0.916655  0.844550  0.745598  0.733831  0.675852   
Taipei City      0.651484  0.650138  0.613941  0.506621  0.558566  0.570881   
Taoyuan City     0.227154  0.409924  0.460928  0.445285  0.578143  0.593622   
Taichung City    0.548530  0.552859  0.528922  0.481010  0.626613  0.597496   
Tainan City      0.156796  0.413017  0.130311  0.096660  0.036520  0.109625   
Kaohsiung City   0.414872  0.033760  0.387114  0.332654  0.196840  0.298164   

                      110       111  
million                              
New Taipei City  0.831620  0.439644  
Taipei City      0.631529  0.643553  
Taoyuan City     0.643901  0.578235  
Taichung City    0.578583  0.566211  
Tainan City      0.166501  0.191166  
Kaohsiung City   0.391264  0.431553

In [38]:
df2['112'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.769026  0.763133  0.600298  0.844259  0.427023  0.902175   
Taipei City      0.348334  0.301477  0.269718  0.509895  0.405341  0.567302   
Taoyuan City     0.293364  0.269172  0.171784  0.251928  0.208818  0.205217   
Taichung City    0.455872  0.417819  0.306352  0.469696  0.341349  0.488904   
Tainan City      0.133040  0.112049  0.018044  0.112485  0.241414  0.133586   
Kaohsiung City   0.402576  0.000000  0.275320  0.374527  0.503747  0.382349   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  1.000000  0.916655  0.844550  0.745598  0.733831  0.675852   
Taipei City      0.651484  0.650138  0.613941  0.506621  0.558566  0.570881   
Taoyuan City     0.227154  0.409924  0.460928  0.445285  0.578143  0.593622   
Taichung City    0.548530  0.552859  0.528922  0.481010  0.626613  0.597496   
Tainan City      0.156796  0.413017  0.130311  0.096660  0.036520  0.109625   
Kaohsiung City   0.414872  0.033760  0.387114  0.332654  0.196840  0.298164   

                      110       111       112  
million                                        
New Taipei City  0.831620  0.439644  0.895850  
Taipei City      0.631529  0.643553  0.578235  
Taoyuan City     0.643901  0.578235  0.566211  
Taichung City    0.578583  0.566211  0.631529  
Tainan City      0.166501  0.191166  0.319453  
Kaohsiung City   0.391264  0.431553  0.326815

In [39]:
df2['113'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.769026  0.763133  0.600298  0.844259  0.427023  0.902175   
Taipei City      0.348334  0.301477  0.269718  0.509895  0.405341  0.567302   
Taoyuan City     0.293364  0.269172  0.171784  0.251928  0.208818  0.205217   
Taichung City    0.455872  0.417819  0.306352  0.469696  0.341349  0.488904   
Tainan City      0.133040  0.112049  0.018044  0.112485  0.241414  0.133586   
Kaohsiung City   0.402576  0.000000  0.275320  0.374527  0.503747  0.382349   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  1.000000  0.916655  0.844550  0.745598  0.733831  0.675852   
Taipei City      0.651484  0.650138  0.613941  0.506621  0.558566  0.570881   
Taoyuan City     0.227154  0.409924  0.460928  0.445285  0.578143  0.593622   
Taichung City    0.548530  0.552859  0.528922  0.481010  0.626613  0.597496   
Tainan City      0.156796  0.413017  0.130311  0.096660  0.036520  0.109625   
Kaohsiung City   0.414872  0.033760  0.387114  0.332654  0.196840  0.298164   

                      110       111       112       113  
million                                                  
New Taipei City  0.831620  0.439644  0.895850  0.990576  
Taipei City      0.631529  0.643553  0.578235  0.566211  
Taoyuan City     0.643901  0.578235  0.566211  0.631529  
Taichung City    0.578583  0.566211  0.631529  0.643553  
Tainan City      0.166501  0.191166  0.319453  0.391264  
Kaohsiung City   0.391264  0.431553  0.326815  0.496581

In [40]:
df2['114'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.769026  0.763133  0.600298  0.844259  0.427023  0.902175   
Taipei City      0.348334  0.301477  0.269718  0.509895  0.405341  0.567302   
Taoyuan City     0.293364  0.269172  0.171784  0.251928  0.208818  0.205217   
Taichung City    0.455872  0.417819  0.306352  0.469696  0.341349  0.488904   
Tainan City      0.133040  0.112049  0.018044  0.112485  0.241414  0.133586   
Kaohsiung City   0.402576  0.000000  0.275320  0.374527  0.503747  0.382349   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  1.000000  0.916655  0.844550  0.745598  0.733831  0.675852   
Taipei City      0.651484  0.650138  0.613941  0.506621  0.558566  0.570881   
Taoyuan City     0.227154  0.409924  0.460928  0.445285  0.578143  0.593622   
Taichung City    0.548530  0.552859  0.528922  0.481010  0.626613  0.597496   
Tainan City      0.156796  0.413017  0.130311  0.096660  0.036520  0.109625   
Kaohsiung City   0.414872  0.033760  0.387114  0.332654  0.196840  0.298164   

                      110       111       112       113       114  
million                                                            
New Taipei City  0.831620  0.439644  0.895850  0.990576  0.915389  
Taipei City      0.631529  0.643553  0.578235  0.566211  0.631529  
Taoyuan City     0.643901  0.578235  0.566211  0.631529  0.643553  
Taichung City    0.578583  0.566211  0.631529  0.643553  0.578235  
Tainan City      0.166501  0.191166  0.319453  0.391264  0.357822  
Kaohsiung City   0.391264  0.431553  0.326815  0.496581  0.499075

In [41]:
for i in range(len(df2)):
    for j in range(len(df2.columns)):
        df2.iloc[i, j] = (df2.iloc[i, j]*rangeing+min)
df2

98       99      100      101      102      103  \
million                                                                 
New Taipei City  32255.0  32093.0  27617.0  34323.0  22854.0  35915.0   
Taipei City      20691.0  19403.0  18530.0  25132.0  22258.0  26710.0   
Taoyuan City     19180.0  18515.0  15838.0  18041.0  16856.0  16757.0   
Taichung City    23647.0  22601.0  19537.0  24027.0  20499.0  24555.0   
Tainan City      14773.0  14196.0  11612.0  14208.0  17752.0  14788.0   
Kaohsiung City   22182.0  11116.0  18684.0  21411.0  24963.0  21626.0   

                     104      105      106      107           108  \
million                                                             
New Taipei City  38604.0  36313.0  34331.0  31611.0  31287.539062   
Taipei City      29024.0  28987.0  27992.0  25042.0  26469.857422   
Taoyuan City     17360.0  22384.0  23786.0  23356.0  27008.001953   
Taichung City    26194.0  26313.0  25655.0  24338.0  28340.345703   
Tainan City      15426.0  22469.0  14698.0  13773.0  12119.863281   
Kaohsiung City   22520.0  12044.0  21757.0  20260.0  16526.738281   

                          109           110           111           112  \
million                                                                   
New Taipei City  29693.822266  33975.558594  23200.939453  35741.117188   
Taipei City      26808.382812  28475.476562  28805.992188  27010.531250   
Taoyuan City     27433.476562  28815.548828  27010.531250  26680.015625   
Taichung City    27539.957031  27020.087891  26680.015625  28475.476562   
Tainan City      14129.377930  15692.766602  16370.774414  19897.123047   
Kaohsiung City   19311.925781  21871.050781  22978.519531  20099.496094   

                          113           114  
million                                      
New Taipei City  38344.941406  36278.222656  
Taipei City      26680.015625  28475.476562  
Taoyuan City     28475.476562  28805.992188  
Taichung City    28805.992188  27010.531250  
Tainan City      21871.050781  20951.820312  
Kaohsiung City   24766.011719  24834.560547

In [42]:
outputpath='C:/Users/Steven/Desktop/新增資料夾/birth_update1.xlsx'
df2.to_excel(outputpath,index=True,header=True)