In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottle

In [3]:
df1 = pd.read_excel('city_annual_expend_df.xlsx')
df1

million             98             99            100  \
0  New Taipei City   96578.611019   98880.514918  101597.893147   
1      Taipei City  148192.887258  155531.416179  162280.646270   
2     Taoyuan City   45593.320794   48076.080794   48577.653444   
3    Taichung City   75788.780000   74185.000000   77484.420000   
4      Tainan City   58714.480000   59532.477000   64737.220000   
5   Kaohsiung City  102063.120000  117931.345000  115951.800000   
6           Taiwan  807522.000000  867824.000000  882066.000000   

             101            102            103            104           105  \
0  145899.009050  149866.518605  146754.099649  154473.463926  1.516608e+05   
1  173139.571548  176075.234609  169580.238024  167504.327527  1.541876e+05   
2   57174.898426   58093.627307   57736.471325   62760.000000  8.497782e+04   
3   96887.312546   99883.362462  109538.016083  104869.032822  1.131774e+05   
4   77578.825927   82584.343311   77916.851738   73521.376929  6.949806e+04   
5  126711.535220  124889.951539  122071.850246  126265.671271  1.199338e+05   
6  986397.000000  998285.000000  987590.000000  999547.000000  1.002236e+06   

          106           107       108  
0   148828.44  1.488284e+05  166966.0  
1   162256.23  1.622562e+05  165546.0  
2    95094.42  9.509442e+04  115998.0  
3   123807.59  1.238076e+05  124657.0  
4    74696.14  7.469614e+04   86319.0  
5   121757.81  1.217580e+05  133542.0  
6  1014904.00  1.036507e+06       NaN

In [4]:
df1.index = df1['million']

In [5]:
df1.columns

Index(['million', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [6]:
df1

million             98             99            100  \
million                                                                         
New Taipei City  New Taipei City   96578.611019   98880.514918  101597.893147   
Taipei City          Taipei City  148192.887258  155531.416179  162280.646270   
Taoyuan City        Taoyuan City   45593.320794   48076.080794   48577.653444   
Taichung City      Taichung City   75788.780000   74185.000000   77484.420000   
Tainan City          Tainan City   58714.480000   59532.477000   64737.220000   
Kaohsiung City    Kaohsiung City  102063.120000  117931.345000  115951.800000   
Taiwan                    Taiwan  807522.000000  867824.000000  882066.000000   

                           101            102            103            104  \
million                                                                       
New Taipei City  145899.009050  149866.518605  146754.099649  154473.463926   
Taipei City      173139.571548  176075.234609  169580.238024  167504.327527   
Taoyuan City      57174.898426   58093.627307   57736.471325   62760.000000   
Taichung City     96887.312546   99883.362462  109538.016083  104869.032822   
Tainan City       77578.825927   82584.343311   77916.851738   73521.376929   
Kaohsiung City   126711.535220  124889.951539  122071.850246  126265.671271   
Taiwan           986397.000000  998285.000000  987590.000000  999547.000000   

                          105         106           107       108  
million                                                            
New Taipei City  1.516608e+05   148828.44  1.488284e+05  166966.0  
Taipei City      1.541876e+05   162256.23  1.622562e+05  165546.0  
Taoyuan City     8.497782e+04    95094.42  9.509442e+04  115998.0  
Taichung City    1.131774e+05   123807.59  1.238076e+05  124657.0  
Tainan City      6.949806e+04    74696.14  7.469614e+04   86319.0  
Kaohsiung City   1.199338e+05   121757.81  1.217580e+05  133542.0  
Taiwan           1.002236e+06  1014904.00  1.036507e+06       NaN

In [7]:
df1 = df1.iloc[:-1, 1:-1]
df1

98             99             100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107  
million                                    
New Taipei City  148828.44  148828.437264  
Taipei City      162256.23  162256.234058  
Taoyuan City      95094.42   95094.418061  
Taichung City    123807.59  123807.590957  
Tainan City       74696.14   74696.140442  
Kaohsiung City   121757.81  121758.000000

In [8]:
col = []
for i in df1.columns:
    col.append(str(i))
col

['98', '99', '100', '101', '102', '103', '104', '105', '106', '107']

In [9]:
df1.columns = col
df1

98             99            100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107  
million                                    
New Taipei City  148828.44  148828.437264  
Taipei City      162256.23  162256.234058  
Taoyuan City      95094.42   95094.418061  
Taichung City    123807.59  123807.590957  
Tainan City       74696.14   74696.140442  
Kaohsiung City   121757.81  121758.000000

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, New Taipei City to Kaohsiung City
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   98      6 non-null      float64
 1   99      6 non-null      float64
 2   100     6 non-null      float64
 3   101     6 non-null      float64
 4   102     6 non-null      float64
 5   103     6 non-null      float64
 6   104     6 non-null      float64
 7   105     6 non-null      float64
 8   106     6 non-null      float64
 9   107     6 non-null      float64
dtypes: float64(10)
memory usage: 528.0+ bytes


In [11]:
df1

98             99            100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107  
million                                    
New Taipei City  148828.44  148828.437264  
Taipei City      162256.23  162256.234058  
Taoyuan City      95094.42   95094.418061  
Taichung City    123807.59  123807.590957  
Tainan City       74696.14   74696.140442  
Kaohsiung City   121757.81  121758.000000

In [12]:
min = df1.min().min()
rangeing = (df1.max().max())-(df1.min().min())
print(min)
print(rangeing)

45593.320794
130481.913815


In [13]:
for i in range(len(df1)):
    for j in range(len(df1.columns)):
        df1.iloc[i, j] = (df1.iloc[i, j]-min)/rangeing

### input為4維

In [14]:
d = int(input('輸入的維度：'))
x_train = []
y_train = []
x_test = []
y_test = []

for a in range(2):
    x_test.append([])
    y_test.append([])

for b in range(8-d):
    x_train.append([])
    y_train.append([])
    
for i in range(2):
    x_test[i] = (df1.iloc[:, -2-d+i:-2+i].values)
    y_test[i] = (df1.iloc[:, -2+i].values)

for j in range(8-d):
    x_train[j] = (df1.iloc[:, j:d+j].values)
    y_train[j] = (df1.iloc[:, d+j].values)

輸入的維度：4


In [15]:
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)

In [16]:
x_train

array([[[0.39074603, 0.40838759, 0.4292133 , 0.7687325 ],
        [0.78631255, 0.84255428, 0.89427969, 0.97750138],
        [0.        , 0.01902762, 0.02287162, 0.08876002],
        [0.2314149 , 0.2191237 , 0.24441011, 0.39311189],
        [0.10055922, 0.10682826, 0.14671688, 0.24513363],
        [0.43277875, 0.5543912 , 0.53922017, 0.62168167]],

       [[0.40838759, 0.4292133 , 0.7687325 , 0.79913909],
        [0.84255428, 0.89427969, 0.97750138, 1.        ],
        [0.01902762, 0.02287162, 0.08876002, 0.09580107],
        [0.2191237 , 0.24441011, 0.39311189, 0.41607331],
        [0.10682826, 0.14671688, 0.24513363, 0.2834954 ],
        [0.5543912 , 0.53922017, 0.62168167, 0.60772124]],

       [[0.4292133 , 0.7687325 , 0.79913909, 0.77528583],
        [0.89427969, 0.97750138, 1.        , 0.95022301],
        [0.02287162, 0.08876002, 0.09580107, 0.09306386],
        [0.24441011, 0.39311189, 0.41607331, 0.49006558],
        [0.14671688, 0.24513363, 0.2834954 , 0.24772422],
        [0

In [17]:
x_train.shape

(4, 6, 4)

In [18]:
y_train

array([[0.79913909, 1.        , 0.09580107, 0.41607331, 0.2834954 ,
        0.60772124],
       [0.77528583, 0.95022301, 0.09306386, 0.49006558, 0.24772422,
        0.5861236 ],
       [0.83444625, 0.93431345, 0.13156367, 0.45428298, 0.21403776,
        0.61826462],
       [0.81289039, 0.83225571, 0.30183876, 0.51795775, 0.18320347,
        0.5697377 ]])

In [19]:
y_train.shape

(4, 6)

In [20]:
x_test

array([[[0.79913909, 0.77528583, 0.83444625, 0.81289039],
        [1.        , 0.95022301, 0.93431345, 0.83225571],
        [0.09580107, 0.09306386, 0.13156367, 0.30183876],
        [0.41607331, 0.49006558, 0.45428298, 0.51795775],
        [0.2834954 , 0.24772422, 0.21403776, 0.18320347],
        [0.60772124, 0.5861236 , 0.61826462, 0.5697377 ]],

       [[0.77528583, 0.83444625, 0.81289039, 0.79118336],
        [0.95022301, 0.93431345, 0.83225571, 0.89409257],
        [0.09306386, 0.13156367, 0.30183876, 0.37937135],
        [0.49006558, 0.45428298, 0.51795775, 0.59942613],
        [0.24772422, 0.21403776, 0.18320347, 0.22304102],
        [0.5861236 , 0.61826462, 0.5697377 , 0.58371683]]])

In [21]:
y_test

array([[0.79118336, 0.89409257, 0.37937135, 0.59942613, 0.22304102,
        0.58371683],
       [0.79118334, 0.8940926 , 0.37937133, 0.59942614, 0.22304102,
        0.58371829]])

In [22]:
x_train = x_train.reshape(-1, d)
y_train = y_train.ravel()
x_test = x_test.reshape(-1, d)
y_test = y_test.ravel()

In [23]:
x_train

array([[0.39074603, 0.40838759, 0.4292133 , 0.7687325 ],
       [0.78631255, 0.84255428, 0.89427969, 0.97750138],
       [0.        , 0.01902762, 0.02287162, 0.08876002],
       [0.2314149 , 0.2191237 , 0.24441011, 0.39311189],
       [0.10055922, 0.10682826, 0.14671688, 0.24513363],
       [0.43277875, 0.5543912 , 0.53922017, 0.62168167],
       [0.40838759, 0.4292133 , 0.7687325 , 0.79913909],
       [0.84255428, 0.89427969, 0.97750138, 1.        ],
       [0.01902762, 0.02287162, 0.08876002, 0.09580107],
       [0.2191237 , 0.24441011, 0.39311189, 0.41607331],
       [0.10682826, 0.14671688, 0.24513363, 0.2834954 ],
       [0.5543912 , 0.53922017, 0.62168167, 0.60772124],
       [0.4292133 , 0.7687325 , 0.79913909, 0.77528583],
       [0.89427969, 0.97750138, 1.        , 0.95022301],
       [0.02287162, 0.08876002, 0.09580107, 0.09306386],
       [0.24441011, 0.39311189, 0.41607331, 0.49006558],
       [0.14671688, 0.24513363, 0.2834954 , 0.24772422],
       [0.53922017, 0.62168167,

In [24]:
y_train

array([0.79913909, 1.        , 0.09580107, 0.41607331, 0.2834954 ,
       0.60772124, 0.77528583, 0.95022301, 0.09306386, 0.49006558,
       0.24772422, 0.5861236 , 0.83444625, 0.93431345, 0.13156367,
       0.45428298, 0.21403776, 0.61826462, 0.81289039, 0.83225571,
       0.30183876, 0.51795775, 0.18320347, 0.5697377 ])

In [25]:
from xgboost import XGBRegressor
xgbr = XGBRegressor(n_estimators=100 , max_depth=3 , learning_rate=0.1, subsample=1, colsample_bynode=0.8, reg_lambda=1e-05)
xgbr.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.8, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1e-05, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [26]:
xgbr.predict(x_test)

array([0.85764533, 0.834393  , 0.2833333 , 0.52424914, 0.21131259,
       0.5747641 , 0.83043116, 0.834393  , 0.41622147, 0.5921662 ,
       0.23809132, 0.59810513], dtype=float32)

In [27]:
y_test

array([0.79118336, 0.89409257, 0.37937135, 0.59942613, 0.22304102,
       0.58371683, 0.79118334, 0.8940926 , 0.37937133, 0.59942614,
       0.22304102, 0.58371829])

In [28]:
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    print('MAPE為', MAPE)

MAPE為 0.06680486469247734
MAPE為 0.06677111387949053
MAPE為 0.17514262210412532
MAPE為 0.06876322992107252
MAPE為 0.06003093982722495
MAPE為 0.01999220034804652


In [29]:
number = 0 
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    number += MAPE
number /= 6
print('平均MAPE為', number)

平均MAPE為 0.07625082846207286


In [30]:
df1

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.390746  0.408388  0.429213  0.768733  0.799139  0.775286   
Taipei City      0.786313  0.842554  0.894280  0.977501  1.000000  0.950223   
Taoyuan City     0.000000  0.019028  0.022872  0.088760  0.095801  0.093064   
Taichung City    0.231415  0.219124  0.244410  0.393112  0.416073  0.490066   
Tainan City      0.100559  0.106828  0.146717  0.245134  0.283495  0.247724   
Kaohsiung City   0.432779  0.554391  0.539220  0.621682  0.607721  0.586124   

                      104       105       106       107  
million                                                  
New Taipei City  0.834446  0.812890  0.791183  0.791183  
Taipei City      0.934313  0.832256  0.894093  0.894093  
Taoyuan City     0.131564  0.301839  0.379371  0.379371  
Taichung City    0.454283  0.517958  0.599426  0.599426  
Tainan City      0.214038  0.183203  0.223041  0.223041  
Kaohsiung City   0.618265  0.569738  0.583717  0.583718

In [31]:
df2 = df1.copy()
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.390746  0.408388  0.429213  0.768733  0.799139  0.775286   
Taipei City      0.786313  0.842554  0.894280  0.977501  1.000000  0.950223   
Taoyuan City     0.000000  0.019028  0.022872  0.088760  0.095801  0.093064   
Taichung City    0.231415  0.219124  0.244410  0.393112  0.416073  0.490066   
Tainan City      0.100559  0.106828  0.146717  0.245134  0.283495  0.247724   
Kaohsiung City   0.432779  0.554391  0.539220  0.621682  0.607721  0.586124   

                      104       105       106       107  
million                                                  
New Taipei City  0.834446  0.812890  0.791183  0.791183  
Taipei City      0.934313  0.832256  0.894093  0.894093  
Taoyuan City     0.131564  0.301839  0.379371  0.379371  
Taichung City    0.454283  0.517958  0.599426  0.599426  
Tainan City      0.214038  0.183203  0.223041  0.223041  
Kaohsiung City   0.618265  0.569738  0.583717  0.583718

In [32]:
df2.iloc[:, -d:].values

array([[0.83444625, 0.81289039, 0.79118336, 0.79118334],
       [0.93431345, 0.83225571, 0.89409257, 0.8940926 ],
       [0.13156367, 0.30183876, 0.37937135, 0.37937133],
       [0.45428298, 0.51795775, 0.59942613, 0.59942614],
       [0.21403776, 0.18320347, 0.22304102, 0.22304102],
       [0.61826462, 0.5697377 , 0.58371683, 0.58371829]])

In [33]:
xgbr.predict(df2.iloc[:, -d:].values)

array([0.8453189 , 0.8453189 , 0.47135484, 0.6016651 , 0.25335655,
       0.57159775], dtype=float32)

In [34]:
df2['108'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.390746  0.408388  0.429213  0.768733  0.799139  0.775286   
Taipei City      0.786313  0.842554  0.894280  0.977501  1.000000  0.950223   
Taoyuan City     0.000000  0.019028  0.022872  0.088760  0.095801  0.093064   
Taichung City    0.231415  0.219124  0.244410  0.393112  0.416073  0.490066   
Tainan City      0.100559  0.106828  0.146717  0.245134  0.283495  0.247724   
Kaohsiung City   0.432779  0.554391  0.539220  0.621682  0.607721  0.586124   

                      104       105       106       107       108  
million                                                            
New Taipei City  0.834446  0.812890  0.791183  0.791183  0.845319  
Taipei City      0.934313  0.832256  0.894093  0.894093  0.845319  
Taoyuan City     0.131564  0.301839  0.379371  0.379371  0.471355  
Taichung City    0.454283  0.517958  0.599426  0.599426  0.601665  
Tainan City      0.214038  0.183203  0.223041  0.223041  0.253357  
Kaohsiung City   0.618265  0.569738  0.583717  0.583718  0.571598

In [35]:
df2['109'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.390746  0.408388  0.429213  0.768733  0.799139  0.775286   
Taipei City      0.786313  0.842554  0.894280  0.977501  1.000000  0.950223   
Taoyuan City     0.000000  0.019028  0.022872  0.088760  0.095801  0.093064   
Taichung City    0.231415  0.219124  0.244410  0.393112  0.416073  0.490066   
Tainan City      0.100559  0.106828  0.146717  0.245134  0.283495  0.247724   
Kaohsiung City   0.432779  0.554391  0.539220  0.621682  0.607721  0.586124   

                      104       105       106       107       108       109  
million                                                                      
New Taipei City  0.834446  0.812890  0.791183  0.791183  0.845319  0.857645  
Taipei City      0.934313  0.832256  0.894093  0.894093  0.845319  0.842518  
Taoyuan City     0.131564  0.301839  0.379371  0.379371  0.471355  0.445462  
Taichung City    0.454283  0.517958  0.599426  0.599426  0.601665  0.601478  
Tainan City      0.214038  0.183203  0.223041  0.223041  0.253357  0.254066  
Kaohsiung City   0.618265  0.569738  0.583717  0.583718  0.571598  0.581732

In [36]:
df2['110'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.390746  0.408388  0.429213  0.768733  0.799139  0.775286   
Taipei City      0.786313  0.842554  0.894280  0.977501  1.000000  0.950223   
Taoyuan City     0.000000  0.019028  0.022872  0.088760  0.095801  0.093064   
Taichung City    0.231415  0.219124  0.244410  0.393112  0.416073  0.490066   
Tainan City      0.100559  0.106828  0.146717  0.245134  0.283495  0.247724   
Kaohsiung City   0.432779  0.554391  0.539220  0.621682  0.607721  0.586124   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  0.834446  0.812890  0.791183  0.791183  0.845319  0.857645   
Taipei City      0.934313  0.832256  0.894093  0.894093  0.845319  0.842518   
Taoyuan City     0.131564  0.301839  0.379371  0.379371  0.471355  0.445462   
Taichung City    0.454283  0.517958  0.599426  0.599426  0.601665  0.601478   
Tainan City      0.214038  0.183203  0.223041  0.223041  0.253357  0.254066   
Kaohsiung City   0.618265  0.569738  0.583717  0.583718  0.571598  0.581732   

                      110  
million                    
New Taipei City  0.857645  
Taipei City      0.842518  
Taoyuan City     0.529338  
Taichung City    0.574764  
Tainan City      0.228221  
Kaohsiung City   0.581732

In [37]:
df2['111'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.390746  0.408388  0.429213  0.768733  0.799139  0.775286   
Taipei City      0.786313  0.842554  0.894280  0.977501  1.000000  0.950223   
Taoyuan City     0.000000  0.019028  0.022872  0.088760  0.095801  0.093064   
Taichung City    0.231415  0.219124  0.244410  0.393112  0.416073  0.490066   
Tainan City      0.100559  0.106828  0.146717  0.245134  0.283495  0.247724   
Kaohsiung City   0.432779  0.554391  0.539220  0.621682  0.607721  0.586124   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  0.834446  0.812890  0.791183  0.791183  0.845319  0.857645   
Taipei City      0.934313  0.832256  0.894093  0.894093  0.845319  0.842518   
Taoyuan City     0.131564  0.301839  0.379371  0.379371  0.471355  0.445462   
Taichung City    0.454283  0.517958  0.599426  0.599426  0.601665  0.601478   
Tainan City      0.214038  0.183203  0.223041  0.223041  0.253357  0.254066   
Kaohsiung City   0.618265  0.569738  0.583717  0.583718  0.571598  0.581732   

                      110       111  
million                              
New Taipei City  0.857645  0.857645  
Taipei City      0.842518  0.845319  
Taoyuan City     0.529338  0.536482  
Taichung City    0.574764  0.574764  
Tainan City      0.228221  0.201636  
Kaohsiung City   0.581732  0.581920

In [38]:
df2['112'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.390746  0.408388  0.429213  0.768733  0.799139  0.775286   
Taipei City      0.786313  0.842554  0.894280  0.977501  1.000000  0.950223   
Taoyuan City     0.000000  0.019028  0.022872  0.088760  0.095801  0.093064   
Taichung City    0.231415  0.219124  0.244410  0.393112  0.416073  0.490066   
Tainan City      0.100559  0.106828  0.146717  0.245134  0.283495  0.247724   
Kaohsiung City   0.432779  0.554391  0.539220  0.621682  0.607721  0.586124   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  0.834446  0.812890  0.791183  0.791183  0.845319  0.857645   
Taipei City      0.934313  0.832256  0.894093  0.894093  0.845319  0.842518   
Taoyuan City     0.131564  0.301839  0.379371  0.379371  0.471355  0.445462   
Taichung City    0.454283  0.517958  0.599426  0.599426  0.601665  0.601478   
Tainan City      0.214038  0.183203  0.223041  0.223041  0.253357  0.254066   
Kaohsiung City   0.618265  0.569738  0.583717  0.583718  0.571598  0.581732   

                      110       111       112  
million                                        
New Taipei City  0.857645  0.857645  0.845319  
Taipei City      0.842518  0.845319  0.845319  
Taoyuan City     0.529338  0.536482  0.518337  
Taichung City    0.574764  0.574764  0.571410  
Tainan City      0.228221  0.201636  0.211313  
Kaohsiung City   0.581732  0.581920  0.581732

In [39]:
df2['113'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.390746  0.408388  0.429213  0.768733  0.799139  0.775286   
Taipei City      0.786313  0.842554  0.894280  0.977501  1.000000  0.950223   
Taoyuan City     0.000000  0.019028  0.022872  0.088760  0.095801  0.093064   
Taichung City    0.231415  0.219124  0.244410  0.393112  0.416073  0.490066   
Tainan City      0.100559  0.106828  0.146717  0.245134  0.283495  0.247724   
Kaohsiung City   0.432779  0.554391  0.539220  0.621682  0.607721  0.586124   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  0.834446  0.812890  0.791183  0.791183  0.845319  0.857645   
Taipei City      0.934313  0.832256  0.894093  0.894093  0.845319  0.842518   
Taoyuan City     0.131564  0.301839  0.379371  0.379371  0.471355  0.445462   
Taichung City    0.454283  0.517958  0.599426  0.599426  0.601665  0.601478   
Tainan City      0.214038  0.183203  0.223041  0.223041  0.253357  0.254066   
Kaohsiung City   0.618265  0.569738  0.583717  0.583718  0.571598  0.581732   

                      110       111       112       113  
million                                                  
New Taipei City  0.857645  0.857645  0.845319  0.845319  
Taipei City      0.842518  0.845319  0.845319  0.845319  
Taoyuan City     0.529338  0.536482  0.518337  0.524249  
Taichung City    0.574764  0.574764  0.571410  0.571598  
Tainan City      0.228221  0.201636  0.211313  0.238091  
Kaohsiung City   0.581732  0.581920  0.581732  0.581732

In [40]:
df2['114'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.390746  0.408388  0.429213  0.768733  0.799139  0.775286   
Taipei City      0.786313  0.842554  0.894280  0.977501  1.000000  0.950223   
Taoyuan City     0.000000  0.019028  0.022872  0.088760  0.095801  0.093064   
Taichung City    0.231415  0.219124  0.244410  0.393112  0.416073  0.490066   
Tainan City      0.100559  0.106828  0.146717  0.245134  0.283495  0.247724   
Kaohsiung City   0.432779  0.554391  0.539220  0.621682  0.607721  0.586124   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  0.834446  0.812890  0.791183  0.791183  0.845319  0.857645   
Taipei City      0.934313  0.832256  0.894093  0.894093  0.845319  0.842518   
Taoyuan City     0.131564  0.301839  0.379371  0.379371  0.471355  0.445462   
Taichung City    0.454283  0.517958  0.599426  0.599426  0.601665  0.601478   
Tainan City      0.214038  0.183203  0.223041  0.223041  0.253357  0.254066   
Kaohsiung City   0.618265  0.569738  0.583717  0.583718  0.571598  0.581732   

                      110       111       112       113       114  
million                                                            
New Taipei City  0.857645  0.857645  0.845319  0.845319  0.845319  
Taipei City      0.842518  0.845319  0.845319  0.845319  0.845319  
Taoyuan City     0.529338  0.536482  0.518337  0.524249  0.524249  
Taichung City    0.574764  0.574764  0.571410  0.571598  0.581920  
Tainan City      0.228221  0.201636  0.211313  0.238091  0.252399  
Kaohsiung City   0.581732  0.581920  0.581732  0.581732  0.581732

In [41]:
for i in range(len(df2)):
    for j in range(len(df2.columns)):
        df2.iloc[i, j] = (df2.iloc[i, j]*rangeing+min)
df2

98             99            100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107            108            109  \
million                                                                   
New Taipei City  148828.44  148828.437264  155892.156250  157500.531250   
Taipei City      162256.23  162256.234058  155892.156250  155526.656250   
Taoyuan City      95094.42   95094.418061  107096.601562  103718.007812   
Taichung City    123807.59  123807.590957  124099.734375  124075.289062   
Tainan City       74696.14   74696.140442   78651.765625   78744.367188   
Kaohsiung City   121757.81  121758.000000  120176.492188  121498.882812   

                           110            111            112            113  \
million                                                                       
New Taipei City  157500.531250  157500.531250  155892.156250  155892.156250   
Taipei City      155526.656250  155892.156250  155892.156250  155892.156250   
Taoyuan City     114662.367188  115594.484375  113226.867188  113998.351562   
Taichung City    120589.640625  120589.640625  120152.046875  120176.492188   
Tainan City       75372.007812   71903.195312   73165.789062   76659.929688   
Kaohsiung City   121498.882812  121523.328125  121498.882812  121498.882812   

                           114  
million                         
New Taipei City  155892.156250  
Taipei City      155892.156250  
Taoyuan City     113998.351562  
Taichung City    121523.328125  
Tainan City       78526.804688  
Kaohsiung City   121498.882812

In [42]:
outputpath='C:/Users/Steven/Desktop/新增資料夾/city_annual_update1.xlsx'
df2.to_excel(outputpath,index=True,header=True)