In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottle

In [3]:
df1 = pd.read_excel('death_df.xlsx')
df1

million      98      99     100     101     102     103     104  \
0  New Taipei City   17882   17959   18404   19774   20280   20746   21935   
1      Taipei City   15606   15260   15398   15988   16579   16379   17177   
2     Taoyuan City    9677    9790   10183   10878   10977   10972   11854   
3    Taichung City   13826   13805   14340   14915   15017   15138   15968   
4      Tainan City   13040   12990   13206   13941   13871   14021   14390   
5   Kaohsiung City   17517   18189   18001   18845   18945   19277   20282   
6           Taiwan  143582  145772  152915  154251  155908  163929  163858   

      105     106     107  108  
0   22175   23256   23525  NaN  
1   17106   17982   17467  NaN  
2   11600   12637   12620  NaN  
3   16070   16921   16904  NaN  
4   20508   15234   14996  NaN  
5   12779   21365   21368  NaN  
6  172405  171242  172784  NaN

In [4]:
df1.index = df1['million']

In [5]:
df1.columns

Index(['million', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [6]:
df1

million      98      99     100     101     102  \
million                                                                    
New Taipei City  New Taipei City   17882   17959   18404   19774   20280   
Taipei City          Taipei City   15606   15260   15398   15988   16579   
Taoyuan City        Taoyuan City    9677    9790   10183   10878   10977   
Taichung City      Taichung City   13826   13805   14340   14915   15017   
Tainan City          Tainan City   13040   12990   13206   13941   13871   
Kaohsiung City    Kaohsiung City   17517   18189   18001   18845   18945   
Taiwan                    Taiwan  143582  145772  152915  154251  155908   

                    103     104     105     106     107  108  
million                                                       
New Taipei City   20746   21935   22175   23256   23525  NaN  
Taipei City       16379   17177   17106   17982   17467  NaN  
Taoyuan City      10972   11854   11600   12637   12620  NaN  
Taichung City     15138   15968   16070   16921   16904  NaN  
Tainan City       14021   14390   20508   15234   14996  NaN  
Kaohsiung City    19277   20282   12779   21365   21368  NaN  
Taiwan           163929  163858  172405  171242  172784  NaN

In [7]:
df1 = df1.iloc[:-1, 1:-1]
df1

98     99     100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107  
million                        
New Taipei City  23256  23525  
Taipei City      17982  17467  
Taoyuan City     12637  12620  
Taichung City    16921  16904  
Tainan City      15234  14996  
Kaohsiung City   21365  21368

In [8]:
col = []
for i in df1.columns:
    col.append(str(i))
col

['98', '99', '100', '101', '102', '103', '104', '105', '106', '107']

In [9]:
df1.columns = col
df1

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107  
million                        
New Taipei City  23256  23525  
Taipei City      17982  17467  
Taoyuan City     12637  12620  
Taichung City    16921  16904  
Tainan City      15234  14996  
Kaohsiung City   21365  21368

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, New Taipei City to Kaohsiung City
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   98      6 non-null      int64
 1   99      6 non-null      int64
 2   100     6 non-null      int64
 3   101     6 non-null      int64
 4   102     6 non-null      int64
 5   103     6 non-null      int64
 6   104     6 non-null      int64
 7   105     6 non-null      int64
 8   106     6 non-null      int64
 9   107     6 non-null      int64
dtypes: int64(10)
memory usage: 528.0+ bytes


In [11]:
df1

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107  
million                        
New Taipei City  23256  23525  
Taipei City      17982  17467  
Taoyuan City     12637  12620  
Taichung City    16921  16904  
Tainan City      15234  14996  
Kaohsiung City   21365  21368

In [12]:
min = df1.min().min()
rangeing = (df1.max().max())-(df1.min().min())
print(min)
print(rangeing)

9677
13848


In [13]:
for i in range(len(df1)):
    for j in range(len(df1.columns)):
        df1.iloc[i, j] = (df1.iloc[i, j]-min)/rangeing

### input為5維

In [14]:
d = int(input('輸入的維度：'))
x_train = []
y_train = []
x_test = []
y_test = []

for a in range(2):
    x_test.append([])
    y_test.append([])

for b in range(8-d):
    x_train.append([])
    y_train.append([])
    
for i in range(2):
    x_test[i] = (df1.iloc[:, -2-d+i:-2+i].values)
    y_test[i] = (df1.iloc[:, -2+i].values)

for j in range(8-d):
    x_train[j] = (df1.iloc[:, j:d+j].values)
    y_train[j] = (df1.iloc[:, d+j].values)

輸入的維度：5


In [15]:
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)

In [16]:
x_train

array([[[0.59250433, 0.5980647 , 0.63019931, 0.72913056, 0.76567013],
        [0.42814847, 0.40316291, 0.41312825, 0.45573368, 0.49841132],
        [0.        , 0.00816002, 0.03653957, 0.08672733, 0.09387637],
        [0.29961005, 0.29809359, 0.33672733, 0.37824957, 0.38561525],
        [0.24285095, 0.23924032, 0.25483824, 0.3079145 , 0.30285962],
        [0.56614674, 0.6146736 , 0.60109763, 0.66204506, 0.66926632]],

       [[0.5980647 , 0.63019931, 0.72913056, 0.76567013, 0.7993212 ],
        [0.40316291, 0.41312825, 0.45573368, 0.49841132, 0.4839688 ],
        [0.00816002, 0.03653957, 0.08672733, 0.09387637, 0.09351531],
        [0.29809359, 0.33672733, 0.37824957, 0.38561525, 0.39435298],
        [0.23924032, 0.25483824, 0.3079145 , 0.30285962, 0.31369151],
        [0.6146736 , 0.60109763, 0.66204506, 0.66926632, 0.6932409 ]],

       [[0.63019931, 0.72913056, 0.76567013, 0.7993212 , 0.88518198],
        [0.41312825, 0.45573368, 0.49841132, 0.4839688 , 0.54159445],
        [0.03653

In [17]:
x_train.shape

(3, 6, 5)

In [18]:
y_train

array([[0.7993212 , 0.4839688 , 0.09351531, 0.39435298, 0.31369151,
        0.6932409 ],
       [0.88518198, 0.54159445, 0.15720682, 0.45428943, 0.34033795,
        0.76581456],
       [0.902513  , 0.53646736, 0.13886482, 0.46165511, 0.7821346 ,
        0.22400347]])

In [19]:
y_train.shape

(3, 6)

In [20]:
x_test

array([[[0.72913056, 0.76567013, 0.7993212 , 0.88518198, 0.902513  ],
        [0.45573368, 0.49841132, 0.4839688 , 0.54159445, 0.53646736],
        [0.08672733, 0.09387637, 0.09351531, 0.15720682, 0.13886482],
        [0.37824957, 0.38561525, 0.39435298, 0.45428943, 0.46165511],
        [0.3079145 , 0.30285962, 0.31369151, 0.34033795, 0.7821346 ],
        [0.66204506, 0.66926632, 0.6932409 , 0.76581456, 0.22400347]],

       [[0.76567013, 0.7993212 , 0.88518198, 0.902513  , 0.98057481],
        [0.49841132, 0.4839688 , 0.54159445, 0.53646736, 0.59972559],
        [0.09387637, 0.09351531, 0.15720682, 0.13886482, 0.21374928],
        [0.38561525, 0.39435298, 0.45428943, 0.46165511, 0.52310803],
        [0.30285962, 0.31369151, 0.34033795, 0.7821346 , 0.40128538],
        [0.66926632, 0.6932409 , 0.76581456, 0.22400347, 0.8440208 ]]])

In [21]:
y_test

array([[0.98057481, 0.59972559, 0.21374928, 0.52310803, 0.40128538,
        0.8440208 ],
       [1.        , 0.56253611, 0.21252166, 0.52188042, 0.38409879,
        0.84423744]])

In [22]:
x_train = x_train.reshape(-1, d)
y_train = y_train.ravel()
x_test = x_test.reshape(-1, d)
y_test = y_test.ravel()

In [23]:
x_train

array([[0.59250433, 0.5980647 , 0.63019931, 0.72913056, 0.76567013],
       [0.42814847, 0.40316291, 0.41312825, 0.45573368, 0.49841132],
       [0.        , 0.00816002, 0.03653957, 0.08672733, 0.09387637],
       [0.29961005, 0.29809359, 0.33672733, 0.37824957, 0.38561525],
       [0.24285095, 0.23924032, 0.25483824, 0.3079145 , 0.30285962],
       [0.56614674, 0.6146736 , 0.60109763, 0.66204506, 0.66926632],
       [0.5980647 , 0.63019931, 0.72913056, 0.76567013, 0.7993212 ],
       [0.40316291, 0.41312825, 0.45573368, 0.49841132, 0.4839688 ],
       [0.00816002, 0.03653957, 0.08672733, 0.09387637, 0.09351531],
       [0.29809359, 0.33672733, 0.37824957, 0.38561525, 0.39435298],
       [0.23924032, 0.25483824, 0.3079145 , 0.30285962, 0.31369151],
       [0.6146736 , 0.60109763, 0.66204506, 0.66926632, 0.6932409 ],
       [0.63019931, 0.72913056, 0.76567013, 0.7993212 , 0.88518198],
       [0.41312825, 0.45573368, 0.49841132, 0.4839688 , 0.54159445],
       [0.03653957, 0.08672733, 0.

In [24]:
y_train

array([0.7993212 , 0.4839688 , 0.09351531, 0.39435298, 0.31369151,
       0.6932409 , 0.88518198, 0.54159445, 0.15720682, 0.45428943,
       0.34033795, 0.76581456, 0.902513  , 0.53646736, 0.13886482,
       0.46165511, 0.7821346 , 0.22400347])

In [25]:
from xgboost import XGBRegressor
xgbr = XGBRegressor(n_estimators=100 , max_depth=3 , learning_rate=0.1, subsample=1, colsample_bynode=0.8, reg_lambda=1e-05)
xgbr.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.8, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1e-05, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [26]:
xgbr.predict(x_test)

array([0.902308  , 0.5421907 , 0.15742794, 0.48053557, 0.42441633,
       0.7960658 , 0.902308  , 0.6183089 , 0.15742794, 0.48601758,
       0.66612506, 0.5122641 ], dtype=float32)

In [27]:
y_test

array([0.98057481, 0.59972559, 0.21374928, 0.52310803, 0.40128538,
       0.8440208 , 1.        , 0.56253611, 0.21252166, 0.52188042,
       0.38409879, 0.84423744])

In [28]:
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    print('MAPE為', MAPE)

MAPE為 0.08875465184127525
MAPE為 0.0975403417022141
MAPE為 0.2613653566674033
MAPE為 0.07505108854026886
MAPE為 0.3959483337413723
MAPE為 0.22502002696069764


In [29]:
number = 0 
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    number += MAPE
number /= 6
print('平均MAPE為', number)

平均MAPE為 0.19061329990887188


In [30]:
df1

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.592504  0.598065  0.630199  0.729131  0.765670  0.799321   
Taipei City      0.428148  0.403163  0.413128  0.455734  0.498411  0.483969   
Taoyuan City     0.000000  0.008160  0.036540  0.086727  0.093876  0.093515   
Taichung City    0.299610  0.298094  0.336727  0.378250  0.385615  0.394353   
Tainan City      0.242851  0.239240  0.254838  0.307915  0.302860  0.313692   
Kaohsiung City   0.566147  0.614674  0.601098  0.662045  0.669266  0.693241   

                      104       105       106       107  
million                                                  
New Taipei City  0.885182  0.902513  0.980575  1.000000  
Taipei City      0.541594  0.536467  0.599726  0.562536  
Taoyuan City     0.157207  0.138865  0.213749  0.212522  
Taichung City    0.454289  0.461655  0.523108  0.521880  
Tainan City      0.340338  0.782135  0.401285  0.384099  
Kaohsiung City   0.765815  0.224003  0.844021  0.844237

In [31]:
df2 = df1.copy()
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.592504  0.598065  0.630199  0.729131  0.765670  0.799321   
Taipei City      0.428148  0.403163  0.413128  0.455734  0.498411  0.483969   
Taoyuan City     0.000000  0.008160  0.036540  0.086727  0.093876  0.093515   
Taichung City    0.299610  0.298094  0.336727  0.378250  0.385615  0.394353   
Tainan City      0.242851  0.239240  0.254838  0.307915  0.302860  0.313692   
Kaohsiung City   0.566147  0.614674  0.601098  0.662045  0.669266  0.693241   

                      104       105       106       107  
million                                                  
New Taipei City  0.885182  0.902513  0.980575  1.000000  
Taipei City      0.541594  0.536467  0.599726  0.562536  
Taoyuan City     0.157207  0.138865  0.213749  0.212522  
Taichung City    0.454289  0.461655  0.523108  0.521880  
Tainan City      0.340338  0.782135  0.401285  0.384099  
Kaohsiung City   0.765815  0.224003  0.844021  0.844237

In [32]:
df2.iloc[:, -d:].values

array([[0.7993212 , 0.88518198, 0.902513  , 0.98057481, 1.        ],
       [0.4839688 , 0.54159445, 0.53646736, 0.59972559, 0.56253611],
       [0.09351531, 0.15720682, 0.13886482, 0.21374928, 0.21252166],
       [0.39435298, 0.45428943, 0.46165511, 0.52310803, 0.52188042],
       [0.31369151, 0.34033795, 0.7821346 , 0.40128538, 0.38409879],
       [0.6932409 , 0.76581456, 0.22400347, 0.8440208 , 0.84423744]])

In [33]:
xgbr.predict(df2.iloc[:, -d:].values)

array([0.902308  , 0.5894997 , 0.15742794, 0.54150015, 0.40967488,
       0.9047345 ], dtype=float32)

In [34]:
df2['108'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.592504  0.598065  0.630199  0.729131  0.765670  0.799321   
Taipei City      0.428148  0.403163  0.413128  0.455734  0.498411  0.483969   
Taoyuan City     0.000000  0.008160  0.036540  0.086727  0.093876  0.093515   
Taichung City    0.299610  0.298094  0.336727  0.378250  0.385615  0.394353   
Tainan City      0.242851  0.239240  0.254838  0.307915  0.302860  0.313692   
Kaohsiung City   0.566147  0.614674  0.601098  0.662045  0.669266  0.693241   

                      104       105       106       107       108  
million                                                            
New Taipei City  0.885182  0.902513  0.980575  1.000000  0.902308  
Taipei City      0.541594  0.536467  0.599726  0.562536  0.589500  
Taoyuan City     0.157207  0.138865  0.213749  0.212522  0.157428  
Taichung City    0.454289  0.461655  0.523108  0.521880  0.541500  
Tainan City      0.340338  0.782135  0.401285  0.384099  0.409675  
Kaohsiung City   0.765815  0.224003  0.844021  0.844237  0.904734

In [35]:
df2['109'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.592504  0.598065  0.630199  0.729131  0.765670  0.799321   
Taipei City      0.428148  0.403163  0.413128  0.455734  0.498411  0.483969   
Taoyuan City     0.000000  0.008160  0.036540  0.086727  0.093876  0.093515   
Taichung City    0.299610  0.298094  0.336727  0.378250  0.385615  0.394353   
Tainan City      0.242851  0.239240  0.254838  0.307915  0.302860  0.313692   
Kaohsiung City   0.566147  0.614674  0.601098  0.662045  0.669266  0.693241   

                      104       105       106       107       108       109  
million                                                                      
New Taipei City  0.885182  0.902513  0.980575  1.000000  0.902308  0.902308  
Taipei City      0.541594  0.536467  0.599726  0.562536  0.589500  0.665618  
Taoyuan City     0.157207  0.138865  0.213749  0.212522  0.157428  0.287405  
Taichung City    0.454289  0.461655  0.523108  0.521880  0.541500  0.542191  
Tainan City      0.340338  0.782135  0.401285  0.384099  0.409675  0.387743  
Kaohsiung City   0.765815  0.224003  0.844021  0.844237  0.904734  0.498369

In [36]:
df2['110'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.592504  0.598065  0.630199  0.729131  0.765670  0.799321   
Taipei City      0.428148  0.403163  0.413128  0.455734  0.498411  0.483969   
Taoyuan City     0.000000  0.008160  0.036540  0.086727  0.093876  0.093515   
Taichung City    0.299610  0.298094  0.336727  0.378250  0.385615  0.394353   
Tainan City      0.242851  0.239240  0.254838  0.307915  0.302860  0.313692   
Kaohsiung City   0.566147  0.614674  0.601098  0.662045  0.669266  0.693241   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  0.885182  0.902513  0.980575  1.000000  0.902308  0.902308   
Taipei City      0.541594  0.536467  0.599726  0.562536  0.589500  0.665618   
Taoyuan City     0.157207  0.138865  0.213749  0.212522  0.157428  0.287405   
Taichung City    0.454289  0.461655  0.523108  0.521880  0.541500  0.542191   
Tainan City      0.340338  0.782135  0.401285  0.384099  0.409675  0.387743   
Kaohsiung City   0.765815  0.224003  0.844021  0.844237  0.904734  0.498369   

                      110  
million                    
New Taipei City  0.902308  
Taipei City      0.692801  
Taoyuan City     0.309702  
Taichung City    0.542191  
Tainan City      0.592887  
Kaohsiung City   0.568700

In [37]:
df2['111'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.592504  0.598065  0.630199  0.729131  0.765670  0.799321   
Taipei City      0.428148  0.403163  0.413128  0.455734  0.498411  0.483969   
Taoyuan City     0.000000  0.008160  0.036540  0.086727  0.093876  0.093515   
Taichung City    0.299610  0.298094  0.336727  0.378250  0.385615  0.394353   
Tainan City      0.242851  0.239240  0.254838  0.307915  0.302860  0.313692   
Kaohsiung City   0.566147  0.614674  0.601098  0.662045  0.669266  0.693241   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  0.885182  0.902513  0.980575  1.000000  0.902308  0.902308   
Taipei City      0.541594  0.536467  0.599726  0.562536  0.589500  0.665618   
Taoyuan City     0.157207  0.138865  0.213749  0.212522  0.157428  0.287405   
Taichung City    0.454289  0.461655  0.523108  0.521880  0.541500  0.542191   
Tainan City      0.340338  0.782135  0.401285  0.384099  0.409675  0.387743   
Kaohsiung City   0.765815  0.224003  0.844021  0.844237  0.904734  0.498369   

                      110       111  
million                              
New Taipei City  0.902308  0.902308  
Taipei City      0.692801  0.629663  
Taoyuan City     0.309702  0.318563  
Taichung City    0.542191  0.618309  
Tainan City      0.592887  0.480536  
Kaohsiung City   0.568700  0.574632

In [38]:
df2['112'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.592504  0.598065  0.630199  0.729131  0.765670  0.799321   
Taipei City      0.428148  0.403163  0.413128  0.455734  0.498411  0.483969   
Taoyuan City     0.000000  0.008160  0.036540  0.086727  0.093876  0.093515   
Taichung City    0.299610  0.298094  0.336727  0.378250  0.385615  0.394353   
Tainan City      0.242851  0.239240  0.254838  0.307915  0.302860  0.313692   
Kaohsiung City   0.566147  0.614674  0.601098  0.662045  0.669266  0.693241   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  0.885182  0.902513  0.980575  1.000000  0.902308  0.902308   
Taipei City      0.541594  0.536467  0.599726  0.562536  0.589500  0.665618   
Taoyuan City     0.157207  0.138865  0.213749  0.212522  0.157428  0.287405   
Taichung City    0.454289  0.461655  0.523108  0.521880  0.541500  0.542191   
Tainan City      0.340338  0.782135  0.401285  0.384099  0.409675  0.387743   
Kaohsiung City   0.765815  0.224003  0.844021  0.844237  0.904734  0.498369   

                      110       111       112  
million                                        
New Taipei City  0.902308  0.902308  0.902308  
Taipei City      0.692801  0.629663  0.660429  
Taoyuan City     0.309702  0.318563  0.287631  
Taichung City    0.542191  0.618309  0.665618  
Tainan City      0.592887  0.480536  0.538680  
Kaohsiung City   0.568700  0.574632  0.629222

In [39]:
df2['113'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.592504  0.598065  0.630199  0.729131  0.765670  0.799321   
Taipei City      0.428148  0.403163  0.413128  0.455734  0.498411  0.483969   
Taoyuan City     0.000000  0.008160  0.036540  0.086727  0.093876  0.093515   
Taichung City    0.299610  0.298094  0.336727  0.378250  0.385615  0.394353   
Tainan City      0.242851  0.239240  0.254838  0.307915  0.302860  0.313692   
Kaohsiung City   0.566147  0.614674  0.601098  0.662045  0.669266  0.693241   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  0.885182  0.902513  0.980575  1.000000  0.902308  0.902308   
Taipei City      0.541594  0.536467  0.599726  0.562536  0.589500  0.665618   
Taoyuan City     0.157207  0.138865  0.213749  0.212522  0.157428  0.287405   
Taichung City    0.454289  0.461655  0.523108  0.521880  0.541500  0.542191   
Tainan City      0.340338  0.782135  0.401285  0.384099  0.409675  0.387743   
Kaohsiung City   0.765815  0.224003  0.844021  0.844237  0.904734  0.498369   

                      110       111       112       113  
million                                                  
New Taipei City  0.902308  0.902308  0.902308  0.902308  
Taipei City      0.692801  0.629663  0.660429  0.268637  
Taoyuan City     0.309702  0.318563  0.287631  0.346760  
Taichung City    0.542191  0.618309  0.665618  0.665618  
Tainan City      0.592887  0.480536  0.538680  0.483355  
Kaohsiung City   0.568700  0.574632  0.629222  0.681143

In [40]:
df2['114'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.592504  0.598065  0.630199  0.729131  0.765670  0.799321   
Taipei City      0.428148  0.403163  0.413128  0.455734  0.498411  0.483969   
Taoyuan City     0.000000  0.008160  0.036540  0.086727  0.093876  0.093515   
Taichung City    0.299610  0.298094  0.336727  0.378250  0.385615  0.394353   
Tainan City      0.242851  0.239240  0.254838  0.307915  0.302860  0.313692   
Kaohsiung City   0.566147  0.614674  0.601098  0.662045  0.669266  0.693241   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  0.885182  0.902513  0.980575  1.000000  0.902308  0.902308   
Taipei City      0.541594  0.536467  0.599726  0.562536  0.589500  0.665618   
Taoyuan City     0.157207  0.138865  0.213749  0.212522  0.157428  0.287405   
Taichung City    0.454289  0.461655  0.523108  0.521880  0.541500  0.542191   
Tainan City      0.340338  0.782135  0.401285  0.384099  0.409675  0.387743   
Kaohsiung City   0.765815  0.224003  0.844021  0.844237  0.904734  0.498369   

                      110       111       112       113       114  
million                                                            
New Taipei City  0.902308  0.902308  0.902308  0.902308  0.902308  
Taipei City      0.692801  0.629663  0.660429  0.268637  0.574471  
Taoyuan City     0.309702  0.318563  0.287631  0.346760  0.577343  
Taichung City    0.542191  0.618309  0.665618  0.665618  0.665618  
Tainan City      0.592887  0.480536  0.538680  0.483355  0.588809  
Kaohsiung City   0.568700  0.574632  0.629222  0.681143  0.665618

In [41]:
for i in range(len(df2)):
    for j in range(len(df2.columns)):
        df2.iloc[i, j] = (df2.iloc[i, j]*rangeing+min)
df2

98       99      100      101      102      103  \
million                                                                 
New Taipei City  17882.0  17959.0  18404.0  19774.0  20280.0  20746.0   
Taipei City      15606.0  15260.0  15398.0  15988.0  16579.0  16379.0   
Taoyuan City      9677.0   9790.0  10183.0  10878.0  10977.0  10972.0   
Taichung City    13826.0  13805.0  14340.0  14915.0  15017.0  15138.0   
Tainan City      13040.0  12990.0  13206.0  13941.0  13871.0  14021.0   
Kaohsiung City   17517.0  18189.0  18001.0  18845.0  18945.0  19277.0   

                     104      105      106      107           108  \
million                                                             
New Taipei City  21935.0  22175.0  23256.0  23525.0  22172.160156   
Taipei City      17177.0  17106.0  17982.0  17467.0  17840.392578   
Taoyuan City     11854.0  11600.0  12637.0  12620.0  11857.062500   
Taichung City    15968.0  16070.0  16921.0  16904.0  17175.693359   
Tainan City      14390.0  20508.0  15234.0  14996.0  15350.177734   
Kaohsiung City   20282.0  12779.0  21365.0  21368.0  22205.763672   

                          109           110           111           112  \
million                                                                   
New Taipei City  22172.160156  22172.160156  22172.160156  22172.160156   
Taipei City      18894.476562  19270.902344  18396.568359  18822.619141   
Taoyuan City     13656.989258  13965.754883  14088.456055  13660.117188   
Taichung City    17185.255859  17185.255859  18239.341797  18894.476562   
Tainan City      15046.459961  17887.302734  16331.456055  17136.646484   
Kaohsiung City   16578.410156  17552.355469  17634.505859  18390.466797   

                          113           114  
million                                      
New Taipei City  22172.160156  22172.160156  
Taipei City      13397.083008  17632.277344  
Taoyuan City     14478.926758  17672.044922  
Taichung City    18894.476562  18894.476562  
Tainan City      16370.503906  17830.830078  
Kaohsiung City   19109.474609  18894.476562

In [42]:
outputpath='C:/Users/Steven/Desktop/新增資料夾/death_update1.xlsx'
df2.to_excel(outputpath,index=True,header=True)