In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottle

In [3]:
df1 = pd.read_excel('immigration_df.xlsx')
df1

million     98     99    100    101    102    103   104    105  \
0  New Taipei City  21342  25789  14501   4535   2287    455 -4780 -10312   
1      Taipei City -11431 -19638   8212  23052   9339   2959  3952  -9386   
2     Taoyuan City  14215  11371  17623   4082   7967   8077  8799  36668   
3    Taichung City   7457   2893   7461   6863   7192   7351  7948  14367   
4      Tainan City   1211   1195    -18   2899    804    796    40  -2035   
5   Kaohsiung City   -479  -1055   1913  -1579  -1829  -1131 -3123    102   
6           Taiwan  35013  21237  19077  15680  14490  13782  6798  11707   

     106    107     108  
0  -2511   -605  4030.0  
1 -19116 -20022     NaN  
2  30834  29518     NaN  
3  14060  12397     NaN  
4   1028   1712     NaN  
5     61  -1351     NaN  
6   8809   6770     NaN

In [4]:
df1.index = df1['million']

In [5]:
df1.columns

Index(['million', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [6]:
df1

million     98     99    100    101    102    103  \
million                                                                      
New Taipei City  New Taipei City  21342  25789  14501   4535   2287    455   
Taipei City          Taipei City -11431 -19638   8212  23052   9339   2959   
Taoyuan City        Taoyuan City  14215  11371  17623   4082   7967   8077   
Taichung City      Taichung City   7457   2893   7461   6863   7192   7351   
Tainan City          Tainan City   1211   1195    -18   2899    804    796   
Kaohsiung City    Kaohsiung City   -479  -1055   1913  -1579  -1829  -1131   
Taiwan                    Taiwan  35013  21237  19077  15680  14490  13782   

                  104    105    106    107     108  
million                                             
New Taipei City -4780 -10312  -2511   -605  4030.0  
Taipei City      3952  -9386 -19116 -20022     NaN  
Taoyuan City     8799  36668  30834  29518     NaN  
Taichung City    7948  14367  14060  12397     NaN  
Tainan City        40  -2035   1028   1712     NaN  
Kaohsiung City  -3123    102     61  -1351     NaN  
Taiwan           6798  11707   8809   6770     NaN

In [7]:
df1 = df1.iloc[:-1, 1:-1]
df1

98     99     100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107  
million                 
New Taipei City   -605  
Taipei City     -20022  
Taoyuan City     29518  
Taichung City    12397  
Tainan City       1712  
Kaohsiung City   -1351

In [8]:
col = []
for i in df1.columns:
    col.append(str(i))
col

['98', '99', '100', '101', '102', '103', '104', '105', '106', '107']

In [9]:
df1.columns = col
df1

98     99    100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107  
million                 
New Taipei City   -605  
Taipei City     -20022  
Taoyuan City     29518  
Taichung City    12397  
Tainan City       1712  
Kaohsiung City   -1351

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, New Taipei City to Kaohsiung City
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   98      6 non-null      int64
 1   99      6 non-null      int64
 2   100     6 non-null      int64
 3   101     6 non-null      int64
 4   102     6 non-null      int64
 5   103     6 non-null      int64
 6   104     6 non-null      int64
 7   105     6 non-null      int64
 8   106     6 non-null      int64
 9   107     6 non-null      int64
dtypes: int64(10)
memory usage: 528.0+ bytes


In [11]:
df1

98     99    100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107  
million                 
New Taipei City   -605  
Taipei City     -20022  
Taoyuan City     29518  
Taichung City    12397  
Tainan City       1712  
Kaohsiung City   -1351

In [12]:
min = df1.min().min()
rangeing = (df1.max().max())-(df1.min().min())
print(min)
print(rangeing)

-20022
56690


In [13]:
for i in range(len(df1)):
    for j in range(len(df1.columns)):
        df1.iloc[i, j] = (df1.iloc[i, j]-min)/rangeing

### input為4維

In [14]:
d = int(input('輸入的維度：'))
x_train = []
y_train = []
x_test = []
y_test = []

for a in range(2):
    x_test.append([])
    y_test.append([])

for b in range(8-d):
    x_train.append([])
    y_train.append([])
    
for i in range(2):
    x_test[i] = (df1.iloc[:, -2-d+i:-2+i].values)
    y_test[i] = (df1.iloc[:, -2+i].values)

for j in range(8-d):
    x_train[j] = (df1.iloc[:, j:d+j].values)
    y_train[j] = (df1.iloc[:, d+j].values)

輸入的維度：4


In [15]:
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)

In [16]:
x_train

array([[[0.7296525 , 0.80809667, 0.60897866, 0.43318046],
        [0.15154348, 0.00677368, 0.49804198, 0.75981655],
        [0.60393367, 0.5537661 , 0.6640501 , 0.42518963],
        [0.48472394, 0.40421591, 0.4847945 , 0.4742459 ],
        [0.37454578, 0.37426354, 0.35286647, 0.40432175],
        [0.34473452, 0.334574  , 0.38692891, 0.32533075]],

       [[0.80809667, 0.60897866, 0.43318046, 0.3935262 ],
        [0.00677368, 0.49804198, 0.75981655, 0.51792203],
        [0.5537661 , 0.6640501 , 0.42518963, 0.49372023],
        [0.40421591, 0.4847945 , 0.4742459 , 0.48004939],
        [0.37426354, 0.35286647, 0.40432175, 0.36736638],
        [0.334574  , 0.38692891, 0.32533075, 0.3209208 ]],

       [[0.60897866, 0.43318046, 0.3935262 , 0.36121009],
        [0.49804198, 0.75981655, 0.51792203, 0.40538014],
        [0.6640501 , 0.42518963, 0.49372023, 0.49566061],
        [0.4847945 , 0.4742459 , 0.48004939, 0.48285412],
        [0.35286647, 0.40432175, 0.36736638, 0.36722526],
        [0

In [17]:
x_train.shape

(4, 6, 4)

In [18]:
y_train

array([[0.3935262 , 0.51792203, 0.49372023, 0.48004939, 0.36736638,
        0.3209208 ],
       [0.36121009, 0.40538014, 0.49566061, 0.48285412, 0.36722526,
        0.33323337],
       [0.26886576, 0.42289645, 0.50839654, 0.49338508, 0.35388957,
        0.2980949 ],
       [0.17128241, 0.18761686, 1.        , 0.60661492, 0.317287  ,
        0.35498324]])

In [19]:
y_train.shape

(4, 6)

In [20]:
x_test

array([[[0.3935262 , 0.36121009, 0.26886576, 0.17128241],
        [0.51792203, 0.40538014, 0.42289645, 0.18761686],
        [0.49372023, 0.49566061, 0.50839654, 1.        ],
        [0.48004939, 0.48285412, 0.49338508, 0.60661492],
        [0.36736638, 0.36722526, 0.35388957, 0.317287  ],
        [0.3209208 , 0.33323337, 0.2980949 , 0.35498324]],

       [[0.36121009, 0.26886576, 0.17128241, 0.30889046],
        [0.40538014, 0.42289645, 0.18761686, 0.01598165],
        [0.49566061, 0.50839654, 1.        , 0.89708943],
        [0.48285412, 0.49338508, 0.60661492, 0.60119951],
        [0.36722526, 0.35388957, 0.317287  , 0.37131769],
        [0.33323337, 0.2980949 , 0.35498324, 0.35426001]]])

In [21]:
y_test

array([[0.30889046, 0.01598165, 0.89708943, 0.60119951, 0.37131769,
        0.35426001],
       [0.34251191, 0.        , 0.87387546, 0.57186453, 0.38338331,
        0.32935262]])

In [22]:
x_train = x_train.reshape(-1, d)
y_train = y_train.ravel()
x_test = x_test.reshape(-1, d)
y_test = y_test.ravel()

In [23]:
x_train

array([[0.7296525 , 0.80809667, 0.60897866, 0.43318046],
       [0.15154348, 0.00677368, 0.49804198, 0.75981655],
       [0.60393367, 0.5537661 , 0.6640501 , 0.42518963],
       [0.48472394, 0.40421591, 0.4847945 , 0.4742459 ],
       [0.37454578, 0.37426354, 0.35286647, 0.40432175],
       [0.34473452, 0.334574  , 0.38692891, 0.32533075],
       [0.80809667, 0.60897866, 0.43318046, 0.3935262 ],
       [0.00677368, 0.49804198, 0.75981655, 0.51792203],
       [0.5537661 , 0.6640501 , 0.42518963, 0.49372023],
       [0.40421591, 0.4847945 , 0.4742459 , 0.48004939],
       [0.37426354, 0.35286647, 0.40432175, 0.36736638],
       [0.334574  , 0.38692891, 0.32533075, 0.3209208 ],
       [0.60897866, 0.43318046, 0.3935262 , 0.36121009],
       [0.49804198, 0.75981655, 0.51792203, 0.40538014],
       [0.6640501 , 0.42518963, 0.49372023, 0.49566061],
       [0.4847945 , 0.4742459 , 0.48004939, 0.48285412],
       [0.35286647, 0.40432175, 0.36736638, 0.36722526],
       [0.38692891, 0.32533075,

In [24]:
y_train

array([0.3935262 , 0.51792203, 0.49372023, 0.48004939, 0.36736638,
       0.3209208 , 0.36121009, 0.40538014, 0.49566061, 0.48285412,
       0.36722526, 0.33323337, 0.26886576, 0.42289645, 0.50839654,
       0.49338508, 0.35388957, 0.2980949 , 0.17128241, 0.18761686,
       1.        , 0.60661492, 0.317287  , 0.35498324])

In [25]:
from xgboost import XGBRegressor
xgbr = XGBRegressor(n_estimators=100 , max_depth=3 , learning_rate=0.1, subsample=1, colsample_bynode=0.8, reg_lambda=1e-05)
xgbr.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.8, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1e-05, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [26]:
xgbr.predict(x_test)

array([0.21996401, 0.27966133, 0.82396114, 0.6904949 , 0.3302242 ,
       0.34886998, 0.32934976, 0.21973044, 0.59704286, 0.8036153 ,
       0.36400872, 0.3420444 ], dtype=float32)

In [27]:
y_test

array([0.30889046, 0.01598165, 0.89708943, 0.60119951, 0.37131769,
       0.35426001, 0.34251191, 0.        , 0.87387546, 0.57186453,
       0.38338331, 0.32935262])

In [28]:
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    print('MAPE為', MAPE)

MAPE為 0.16315910308799583
MAPE為 inf
MAPE為 0.1991522673046281
MAPE為 0.27689167030156714
MAPE為 0.08060260772965945
MAPE為 0.02687523983333192


<ipython-input-28-a64b37226bbc>:2: RuntimeWarning: divide by zero encountered in double_scalars
  MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])


In [29]:
number = 0 
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    number += MAPE
number /= 6
print('平均MAPE為', number)

平均MAPE為 inf


<ipython-input-29-91765b084251>:3: RuntimeWarning: divide by zero encountered in double_scalars
  MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])


In [30]:
df1

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.729652  0.808097  0.608979  0.433180  0.393526  0.361210   
Taipei City      0.151543  0.006774  0.498042  0.759817  0.517922  0.405380   
Taoyuan City     0.603934  0.553766  0.664050  0.425190  0.493720  0.495661   
Taichung City    0.484724  0.404216  0.484794  0.474246  0.480049  0.482854   
Tainan City      0.374546  0.374264  0.352866  0.404322  0.367366  0.367225   
Kaohsiung City   0.344735  0.334574  0.386929  0.325331  0.320921  0.333233   

                      104       105       106       107  
million                                                  
New Taipei City  0.268866  0.171282  0.308890  0.342512  
Taipei City      0.422896  0.187617  0.015982  0.000000  
Taoyuan City     0.508397  1.000000  0.897089  0.873875  
Taichung City    0.493385  0.606615  0.601200  0.571865  
Tainan City      0.353890  0.317287  0.371318  0.383383  
Kaohsiung City   0.298095  0.354983  0.354260  0.329353

In [31]:
df2 = df1.copy()
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.729652  0.808097  0.608979  0.433180  0.393526  0.361210   
Taipei City      0.151543  0.006774  0.498042  0.759817  0.517922  0.405380   
Taoyuan City     0.603934  0.553766  0.664050  0.425190  0.493720  0.495661   
Taichung City    0.484724  0.404216  0.484794  0.474246  0.480049  0.482854   
Tainan City      0.374546  0.374264  0.352866  0.404322  0.367366  0.367225   
Kaohsiung City   0.344735  0.334574  0.386929  0.325331  0.320921  0.333233   

                      104       105       106       107  
million                                                  
New Taipei City  0.268866  0.171282  0.308890  0.342512  
Taipei City      0.422896  0.187617  0.015982  0.000000  
Taoyuan City     0.508397  1.000000  0.897089  0.873875  
Taichung City    0.493385  0.606615  0.601200  0.571865  
Tainan City      0.353890  0.317287  0.371318  0.383383  
Kaohsiung City   0.298095  0.354983  0.354260  0.329353

In [32]:
df2.iloc[:, -d:].values

array([[0.26886576, 0.17128241, 0.30889046, 0.34251191],
       [0.42289645, 0.18761686, 0.01598165, 0.        ],
       [0.50839654, 1.        , 0.89708943, 0.87387546],
       [0.49338508, 0.60661492, 0.60119951, 0.57186453],
       [0.35388957, 0.317287  , 0.37131769, 0.38338331],
       [0.2980949 , 0.35498324, 0.35426001, 0.32935262]])

In [33]:
xgbr.predict(df2.iloc[:, -d:].values)

array([0.35217166, 0.17818725, 0.5972107 , 0.59447473, 0.35841608,
       0.3500015 ], dtype=float32)

In [34]:
df2['108'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.729652  0.808097  0.608979  0.433180  0.393526  0.361210   
Taipei City      0.151543  0.006774  0.498042  0.759817  0.517922  0.405380   
Taoyuan City     0.603934  0.553766  0.664050  0.425190  0.493720  0.495661   
Taichung City    0.484724  0.404216  0.484794  0.474246  0.480049  0.482854   
Tainan City      0.374546  0.374264  0.352866  0.404322  0.367366  0.367225   
Kaohsiung City   0.344735  0.334574  0.386929  0.325331  0.320921  0.333233   

                      104       105       106       107       108  
million                                                            
New Taipei City  0.268866  0.171282  0.308890  0.342512  0.352172  
Taipei City      0.422896  0.187617  0.015982  0.000000  0.178187  
Taoyuan City     0.508397  1.000000  0.897089  0.873875  0.597211  
Taichung City    0.493385  0.606615  0.601200  0.571865  0.594475  
Tainan City      0.353890  0.317287  0.371318  0.383383  0.358416  
Kaohsiung City   0.298095  0.354983  0.354260  0.329353  0.350002

In [35]:
df2['109'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.729652  0.808097  0.608979  0.433180  0.393526  0.361210   
Taipei City      0.151543  0.006774  0.498042  0.759817  0.517922  0.405380   
Taoyuan City     0.603934  0.553766  0.664050  0.425190  0.493720  0.495661   
Taichung City    0.484724  0.404216  0.484794  0.474246  0.480049  0.482854   
Tainan City      0.374546  0.374264  0.352866  0.404322  0.367366  0.367225   
Kaohsiung City   0.344735  0.334574  0.386929  0.325331  0.320921  0.333233   

                      104       105       106       107       108       109  
million                                                                      
New Taipei City  0.268866  0.171282  0.308890  0.342512  0.352172  0.351519  
Taipei City      0.422896  0.187617  0.015982  0.000000  0.178187  0.274108  
Taoyuan City     0.508397  1.000000  0.897089  0.873875  0.597211  0.572163  
Taichung City    0.493385  0.606615  0.601200  0.571865  0.594475  0.594475  
Tainan City      0.353890  0.317287  0.371318  0.383383  0.358416  0.350899  
Kaohsiung City   0.298095  0.354983  0.354260  0.329353  0.350002  0.342947

In [36]:
df2['110'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.729652  0.808097  0.608979  0.433180  0.393526  0.361210   
Taipei City      0.151543  0.006774  0.498042  0.759817  0.517922  0.405380   
Taoyuan City     0.603934  0.553766  0.664050  0.425190  0.493720  0.495661   
Taichung City    0.484724  0.404216  0.484794  0.474246  0.480049  0.482854   
Tainan City      0.374546  0.374264  0.352866  0.404322  0.367366  0.367225   
Kaohsiung City   0.344735  0.334574  0.386929  0.325331  0.320921  0.333233   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  0.268866  0.171282  0.308890  0.342512  0.352172  0.351519   
Taipei City      0.422896  0.187617  0.015982  0.000000  0.178187  0.274108   
Taoyuan City     0.508397  1.000000  0.897089  0.873875  0.597211  0.572163   
Taichung City    0.493385  0.606615  0.601200  0.571865  0.594475  0.594475   
Tainan City      0.353890  0.317287  0.371318  0.383383  0.358416  0.350899   
Kaohsiung City   0.298095  0.354983  0.354260  0.329353  0.350002  0.342947   

                      110  
million                    
New Taipei City  0.350909  
Taipei City      0.274108  
Taoyuan City     0.569427  
Taichung City    0.594307  
Tainan City      0.349538  
Kaohsiung City   0.326177

In [37]:
df2['111'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.729652  0.808097  0.608979  0.433180  0.393526  0.361210   
Taipei City      0.151543  0.006774  0.498042  0.759817  0.517922  0.405380   
Taoyuan City     0.603934  0.553766  0.664050  0.425190  0.493720  0.495661   
Taichung City    0.484724  0.404216  0.484794  0.474246  0.480049  0.482854   
Tainan City      0.374546  0.374264  0.352866  0.404322  0.367366  0.367225   
Kaohsiung City   0.344735  0.334574  0.386929  0.325331  0.320921  0.333233   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  0.268866  0.171282  0.308890  0.342512  0.352172  0.351519   
Taipei City      0.422896  0.187617  0.015982  0.000000  0.178187  0.274108   
Taoyuan City     0.508397  1.000000  0.897089  0.873875  0.597211  0.572163   
Taichung City    0.493385  0.606615  0.601200  0.571865  0.594475  0.594475   
Tainan City      0.353890  0.317287  0.371318  0.383383  0.358416  0.350899   
Kaohsiung City   0.298095  0.354983  0.354260  0.329353  0.350002  0.342947   

                      110       111  
million                              
New Taipei City  0.350909  0.340682  
Taipei City      0.274108  0.274108  
Taoyuan City     0.569427  0.569427  
Taichung City    0.594307  0.594475  
Tainan City      0.349538  0.317542  
Kaohsiung City   0.326177  0.350821

In [38]:
df2['112'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.729652  0.808097  0.608979  0.433180  0.393526  0.361210   
Taipei City      0.151543  0.006774  0.498042  0.759817  0.517922  0.405380   
Taoyuan City     0.603934  0.553766  0.664050  0.425190  0.493720  0.495661   
Taichung City    0.484724  0.404216  0.484794  0.474246  0.480049  0.482854   
Tainan City      0.374546  0.374264  0.352866  0.404322  0.367366  0.367225   
Kaohsiung City   0.344735  0.334574  0.386929  0.325331  0.320921  0.333233   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  0.268866  0.171282  0.308890  0.342512  0.352172  0.351519   
Taipei City      0.422896  0.187617  0.015982  0.000000  0.178187  0.274108   
Taoyuan City     0.508397  1.000000  0.897089  0.873875  0.597211  0.572163   
Taichung City    0.493385  0.606615  0.601200  0.571865  0.594475  0.594475   
Tainan City      0.353890  0.317287  0.371318  0.383383  0.358416  0.350899   
Kaohsiung City   0.298095  0.354983  0.354260  0.329353  0.350002  0.342947   

                      110       111       112  
million                                        
New Taipei City  0.350909  0.340682  0.325791  
Taipei City      0.274108  0.274108  0.274108  
Taoyuan City     0.569427  0.569427  0.594307  
Taichung City    0.594307  0.594475  0.594475  
Tainan City      0.349538  0.317542  0.325578  
Kaohsiung City   0.326177  0.350821  0.342706

In [39]:
df2['113'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.729652  0.808097  0.608979  0.433180  0.393526  0.361210   
Taipei City      0.151543  0.006774  0.498042  0.759817  0.517922  0.405380   
Taoyuan City     0.603934  0.553766  0.664050  0.425190  0.493720  0.495661   
Taichung City    0.484724  0.404216  0.484794  0.474246  0.480049  0.482854   
Tainan City      0.374546  0.374264  0.352866  0.404322  0.367366  0.367225   
Kaohsiung City   0.344735  0.334574  0.386929  0.325331  0.320921  0.333233   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  0.268866  0.171282  0.308890  0.342512  0.352172  0.351519   
Taipei City      0.422896  0.187617  0.015982  0.000000  0.178187  0.274108   
Taoyuan City     0.508397  1.000000  0.897089  0.873875  0.597211  0.572163   
Taichung City    0.493385  0.606615  0.601200  0.571865  0.594475  0.594475   
Tainan City      0.353890  0.317287  0.371318  0.383383  0.358416  0.350899   
Kaohsiung City   0.298095  0.354983  0.354260  0.329353  0.350002  0.342947   

                      110       111       112       113  
million                                                  
New Taipei City  0.350909  0.340682  0.325791  0.327612  
Taipei City      0.274108  0.274108  0.274108  0.274108  
Taoyuan City     0.569427  0.569427  0.594307  0.594307  
Taichung City    0.594307  0.594475  0.594475  0.594475  
Tainan City      0.349538  0.317542  0.325578  0.325573  
Kaohsiung City   0.326177  0.350821  0.342706  0.323912

In [40]:
df2['114'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
million                                                                       
New Taipei City  0.729652  0.808097  0.608979  0.433180  0.393526  0.361210   
Taipei City      0.151543  0.006774  0.498042  0.759817  0.517922  0.405380   
Taoyuan City     0.603934  0.553766  0.664050  0.425190  0.493720  0.495661   
Taichung City    0.484724  0.404216  0.484794  0.474246  0.480049  0.482854   
Tainan City      0.374546  0.374264  0.352866  0.404322  0.367366  0.367225   
Kaohsiung City   0.344735  0.334574  0.386929  0.325331  0.320921  0.333233   

                      104       105       106       107       108       109  \
million                                                                       
New Taipei City  0.268866  0.171282  0.308890  0.342512  0.352172  0.351519   
Taipei City      0.422896  0.187617  0.015982  0.000000  0.178187  0.274108   
Taoyuan City     0.508397  1.000000  0.897089  0.873875  0.597211  0.572163   
Taichung City    0.493385  0.606615  0.601200  0.571865  0.594475  0.594475   
Tainan City      0.353890  0.317287  0.371318  0.383383  0.358416  0.350899   
Kaohsiung City   0.298095  0.354983  0.354260  0.329353  0.350002  0.342947   

                      110       111       112       113       114  
million                                                            
New Taipei City  0.350909  0.340682  0.325791  0.327612  0.327372  
Taipei City      0.274108  0.274108  0.274108  0.274108  0.274108  
Taoyuan City     0.569427  0.569427  0.594307  0.594307  0.594307  
Taichung City    0.594307  0.594475  0.594475  0.594475  0.594475  
Tainan City      0.349538  0.317542  0.325578  0.325573  0.331148  
Kaohsiung City   0.326177  0.350821  0.342706  0.323912  0.350821

In [41]:
for i in range(len(df2)):
    for j in range(len(df2.columns)):
        df2.iloc[i, j] = (df2.iloc[i, j]*rangeing+min)
df2

98       99      100      101     102     103     104  \
million                                                                       
New Taipei City  21342.0  25789.0  14501.0   4535.0  2287.0   455.0 -4780.0   
Taipei City     -11431.0 -19638.0   8212.0  23052.0  9339.0  2959.0  3952.0   
Taoyuan City     14215.0  11371.0  17623.0   4082.0  7967.0  8077.0  8799.0   
Taichung City     7457.0   2893.0   7461.0   6863.0  7192.0  7351.0  7948.0   
Tainan City       1211.0   1195.0    -18.0   2899.0   804.0   796.0    40.0   
Kaohsiung City    -479.0  -1055.0   1913.0  -1579.0 -1829.0 -1131.0 -3123.0   

                     105      106      107           108           109  \
million                                                                  
New Taipei City -10312.0  -2511.0   -605.0    -57.388626    -94.363190   
Taipei City      -9386.0 -19116.0 -20022.0  -9920.564453  -4482.797852   
Taoyuan City     36668.0  30834.0  29518.0  13833.875000  12413.916016   
Taichung City    14367.0  14060.0  12397.0  13678.772461  13678.772461   
Tainan City      -2035.0   1028.0   1712.0    296.607605   -129.545212   
Kaohsiung City     102.0     61.0  -1351.0   -180.414169   -580.332520   

                          110           111           112           113  \
million                                                                   
New Taipei City   -128.942062   -708.764465  -1552.918213  -1449.647949   
Taipei City      -4482.797852  -4482.797852  -4482.797852  -4482.797852   
Taoyuan City     12258.814453  12258.814453  13669.257812  13669.257812   
Taichung City    13669.257812  13678.772461  13678.772461  13678.772461   
Tainan City       -206.717896  -2020.565063  -1564.974487  -1565.266724   
Kaohsiung City   -1531.010620   -133.966614   -593.988708  -1659.442505   

                          114  
million                        
New Taipei City  -1463.304199  
Taipei City      -4482.797852  
Taoyuan City     13669.257812  
Taichung City    13678.772461  
Tainan City      -1249.199707  
Kaohsiung City    -133.966614

In [42]:
outputpath='C:/Users/Steven/Desktop/新增資料夾/immigration_update1.xlsx'
df2.to_excel(outputpath,index=True,header=True)