In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottle

In [3]:
df1 = pd.read_excel('per_capital_income_df.xlsx')
df1

Unnamed: 0             98      99     100     101     102     103  \
0  New Taipei City  265140.804598  273351  279239  278023  284783  291591   
1      Taipei City  387052.795031  402056  381561  398217  408688  412973   
2     Taoyuan City  268840.571429  272470  273295  287727  288668  314701   
3    Taichung City  263142.638037  279324  265316  271157  282352  303365   
4      Tainan City  263413.109756  252184  245524  242163  261153  266012   
5   Kaohsiung City  291891.194969  311566  270996  283843  295244  300872   
6           Taiwan  473259.000000  524234  527186  537021  565198  607264   

      104     105     106     107     108  
0  305575  326152  337605  350606  371156  
1  426633  440278  436538  436489  458839  
2  311248  325471  327133  346623  357432  
3  311948  322806  337637  343713  352633  
4  269302  286254  293031  293762  305444  
5  319905  304104  321015  328911  331657  
6  633367  650854  667945  678233  687140

In [4]:
df1.columns

Index(['Unnamed: 0', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [5]:
df1.index = df1['Unnamed: 0']

In [6]:
df1.columns

Index(['Unnamed: 0', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [7]:
df1

Unnamed: 0             98      99     100     101  \
Unnamed: 0                                                                
New Taipei City  New Taipei City  265140.804598  273351  279239  278023   
Taipei City          Taipei City  387052.795031  402056  381561  398217   
Taoyuan City        Taoyuan City  268840.571429  272470  273295  287727   
Taichung City      Taichung City  263142.638037  279324  265316  271157   
Tainan City          Tainan City  263413.109756  252184  245524  242163   
Kaohsiung City    Kaohsiung City  291891.194969  311566  270996  283843   
Taiwan                    Taiwan  473259.000000  524234  527186  537021   

                    102     103     104     105     106     107     108  
Unnamed: 0                                                               
New Taipei City  284783  291591  305575  326152  337605  350606  371156  
Taipei City      408688  412973  426633  440278  436538  436489  458839  
Taoyuan City     288668  314701  311248  325471  327133  346623  357432  
Taichung City    282352  303365  311948  322806  337637  343713  352633  
Tainan City      261153  266012  269302  286254  293031  293762  305444  
Kaohsiung City   295244  300872  319905  304104  321015  328911  331657  
Taiwan           565198  607264  633367  650854  667945  678233  687140

In [8]:
df1 = df1.iloc[:-1, 1:-1]
df1

98      99      100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107  
Unnamed: 0                                       
New Taipei City  305575  326152  337605  350606  
Taipei City      426633  440278  436538  436489  
Taoyuan City     311248  325471  327133  346623  
Taichung City    311948  322806  337637  343713  
Tainan City      269302  286254  293031  293762  
Kaohsiung City   319905  304104  321015  328911

In [9]:
col = []
for i in df1.columns:
    col.append(str(i))
col

['98', '99', '100', '101', '102', '103', '104', '105', '106', '107']

In [10]:
df1.columns = col
df1

98      99     100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107  
Unnamed: 0                                       
New Taipei City  305575  326152  337605  350606  
Taipei City      426633  440278  436538  436489  
Taoyuan City     311248  325471  327133  346623  
Taichung City    311948  322806  337637  343713  
Tainan City      269302  286254  293031  293762  
Kaohsiung City   319905  304104  321015  328911

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, New Taipei City to Kaohsiung City
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   98      6 non-null      float64
 1   99      6 non-null      int64  
 2   100     6 non-null      int64  
 3   101     6 non-null      int64  
 4   102     6 non-null      int64  
 5   103     6 non-null      int64  
 6   104     6 non-null      int64  
 7   105     6 non-null      int64  
 8   106     6 non-null      int64  
 9   107     6 non-null      int64  
dtypes: float64(1), int64(9)
memory usage: 528.0+ bytes


In [12]:
df1

98      99     100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107  
Unnamed: 0                                       
New Taipei City  305575  326152  337605  350606  
Taipei City      426633  440278  436538  436489  
Taoyuan City     311248  325471  327133  346623  
Taichung City    311948  322806  337637  343713  
Tainan City      269302  286254  293031  293762  
Kaohsiung City   319905  304104  321015  328911

In [13]:
min = df1.min().min()
rangeing = (df1.max().max())-(df1.min().min())
print(min)
print(rangeing)

242163.0
198115.0


In [14]:
for i in range(len(df1)):
    for j in range(len(df1.columns)):
        df1.iloc[i, j] = (df1.iloc[i, j]-min)/rangeing

### input為2維

In [15]:
d = int(input('輸入的維度：'))
x_train = []
y_train = []
x_test = []
y_test = []

for a in range(2):
    x_test.append([])
    y_test.append([])

for b in range(8-d):
    x_train.append([])
    y_train.append([])
    
for i in range(2):
    x_test[i] = (df1.iloc[:, -2-d+i:-2+i].values)
    y_test[i] = (df1.iloc[:, -2+i].values)

for j in range(8-d):
    x_train[j] = (df1.iloc[:, j:d+j].values)
    y_train[j] = (df1.iloc[:, d+j].values)

輸入的維度：2


In [16]:
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)

In [17]:
x_train

array([[[0.11598215, 0.15742372],
        [0.73134187, 0.80707165],
        [0.134657  , 0.15297681],
        [0.10589626, 0.18757287],
        [0.10726149, 0.05058173],
        [0.25100671, 0.35031674]],

       [[0.15742372, 0.18714383],
        [0.80707165, 0.70362163],
        [0.15297681, 0.15714105],
        [0.18757287, 0.11686647],
        [0.05058173, 0.01696489],
        [0.35031674, 0.14553668]],

       [[0.18714383, 0.18100598],
        [0.70362163, 0.78769402],
        [0.15714105, 0.22998763],
        [0.11686647, 0.14634934],
        [0.01696489, 0.        ],
        [0.14553668, 0.21038286]],

       [[0.18100598, 0.21512758],
        [0.78769402, 0.84054716],
        [0.22998763, 0.2347374 ],
        [0.14634934, 0.20285693],
        [0.        , 0.09585342],
        [0.21038286, 0.26793024]],

       [[0.21512758, 0.24949146],
        [0.84054716, 0.86217601],
        [0.2347374 , 0.36614088],
        [0.20285693, 0.30892159],
        [0.09585342, 0.12037958],
      

In [18]:
x_train.shape

(6, 6, 2)

In [19]:
y_train

array([[0.18714383, 0.70362163, 0.15714105, 0.11686647, 0.01696489,
        0.14553668],
       [0.18100598, 0.78769402, 0.22998763, 0.14634934, 0.        ,
        0.21038286],
       [0.21512758, 0.84054716, 0.2347374 , 0.20285693, 0.09585342,
        0.26793024],
       [0.24949146, 0.86217601, 0.36614088, 0.30892159, 0.12037958,
        0.29633799],
       [0.32007672, 0.93112586, 0.34871161, 0.35224491, 0.13698609,
        0.39240845],
       [0.42394064, 1.        , 0.42050324, 0.40705146, 0.22255256,
        0.31265174]])

In [20]:
y_train.shape

(6, 6)

In [21]:
x_test

array([[[0.32007672, 0.42394064],
        [0.93112586, 1.        ],
        [0.34871161, 0.42050324],
        [0.35224491, 0.40705146],
        [0.13698609, 0.22255256],
        [0.39240845, 0.31265174]],

       [[0.42394064, 0.4817505 ],
        [1.        , 0.98112208],
        [0.42050324, 0.42889231],
        [0.40705146, 0.48191202],
        [0.22255256, 0.25675996],
        [0.31265174, 0.39801126]]])

In [22]:
y_test

array([[0.4817505 , 0.98112208, 0.42889231, 0.48191202, 0.25675996,
        0.39801126],
       [0.547374  , 0.98087474, 0.52726952, 0.51258108, 0.26044974,
        0.4378669 ]])

In [23]:
x_train = x_train.reshape(-1, d)
y_train = y_train.ravel()
x_test = x_test.reshape(-1, d)
y_test = y_test.ravel()

In [24]:
x_train

array([[0.11598215, 0.15742372],
       [0.73134187, 0.80707165],
       [0.134657  , 0.15297681],
       [0.10589626, 0.18757287],
       [0.10726149, 0.05058173],
       [0.25100671, 0.35031674],
       [0.15742372, 0.18714383],
       [0.80707165, 0.70362163],
       [0.15297681, 0.15714105],
       [0.18757287, 0.11686647],
       [0.05058173, 0.01696489],
       [0.35031674, 0.14553668],
       [0.18714383, 0.18100598],
       [0.70362163, 0.78769402],
       [0.15714105, 0.22998763],
       [0.11686647, 0.14634934],
       [0.01696489, 0.        ],
       [0.14553668, 0.21038286],
       [0.18100598, 0.21512758],
       [0.78769402, 0.84054716],
       [0.22998763, 0.2347374 ],
       [0.14634934, 0.20285693],
       [0.        , 0.09585342],
       [0.21038286, 0.26793024],
       [0.21512758, 0.24949146],
       [0.84054716, 0.86217601],
       [0.2347374 , 0.36614088],
       [0.20285693, 0.30892159],
       [0.09585342, 0.12037958],
       [0.26793024, 0.29633799],
       [0.

In [25]:
y_train

array([0.18714383, 0.70362163, 0.15714105, 0.11686647, 0.01696489,
       0.14553668, 0.18100598, 0.78769402, 0.22998763, 0.14634934,
       0.        , 0.21038286, 0.21512758, 0.84054716, 0.2347374 ,
       0.20285693, 0.09585342, 0.26793024, 0.24949146, 0.86217601,
       0.36614088, 0.30892159, 0.12037958, 0.29633799, 0.32007672,
       0.93112586, 0.34871161, 0.35224491, 0.13698609, 0.39240845,
       0.42394064, 1.        , 0.42050324, 0.40705146, 0.22255256,
       0.31265174])

In [26]:
from xgboost import XGBRegressor
xgbr = XGBRegressor(n_estimators=100 , max_depth=3 , learning_rate=0.1, subsample=1, colsample_bynode=0.8, reg_lambda=1e-05)
xgbr.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.8, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1e-05, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [27]:
xgbr.predict(x_test)

array([0.38924745, 0.9972046 , 0.36597213, 0.36597213, 0.24428889,
       0.43047702, 0.42804363, 0.9972046 , 0.42804363, 0.42804363,
       0.3209279 , 0.38924745], dtype=float32)

In [28]:
y_test

array([0.4817505 , 0.98112208, 0.42889231, 0.48191202, 0.25675996,
       0.39801126, 0.547374  , 0.98087474, 0.52726952, 0.51258108,
       0.26044974, 0.4378669 ])

In [29]:
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    print('MAPE為', MAPE)

MAPE為 0.2050098079412762
MAPE為 0.016520116069286172
MAPE為 0.16744603614212186
MAPE為 0.20275406013194508
MAPE為 0.14038876881413775
MAPE為 0.09630351087804792


In [30]:
number = 0 
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    number += MAPE
number /= 6
print('平均MAPE為', number)

平均MAPE為 0.13807038332946917


In [31]:
df1

98        99       100       101       102       103  \
Unnamed: 0                                                                    
New Taipei City  0.115982  0.157424  0.187144  0.181006  0.215128  0.249491   
Taipei City      0.731342  0.807072  0.703622  0.787694  0.840547  0.862176   
Taoyuan City     0.134657  0.152977  0.157141  0.229988  0.234737  0.366141   
Taichung City    0.105896  0.187573  0.116866  0.146349  0.202857  0.308922   
Tainan City      0.107261  0.050582  0.016965  0.000000  0.095853  0.120380   
Kaohsiung City   0.251007  0.350317  0.145537  0.210383  0.267930  0.296338   

                      104       105       106       107  
Unnamed: 0                                               
New Taipei City  0.320077  0.423941  0.481750  0.547374  
Taipei City      0.931126  1.000000  0.981122  0.980875  
Taoyuan City     0.348712  0.420503  0.428892  0.527270  
Taichung City    0.352245  0.407051  0.481912  0.512581  
Tainan City      0.136986  0.222553  0.256760  0.260450  
Kaohsiung City   0.392408  0.312652  0.398011  0.437867

In [32]:
df2 = df1.copy()
df2

98        99       100       101       102       103  \
Unnamed: 0                                                                    
New Taipei City  0.115982  0.157424  0.187144  0.181006  0.215128  0.249491   
Taipei City      0.731342  0.807072  0.703622  0.787694  0.840547  0.862176   
Taoyuan City     0.134657  0.152977  0.157141  0.229988  0.234737  0.366141   
Taichung City    0.105896  0.187573  0.116866  0.146349  0.202857  0.308922   
Tainan City      0.107261  0.050582  0.016965  0.000000  0.095853  0.120380   
Kaohsiung City   0.251007  0.350317  0.145537  0.210383  0.267930  0.296338   

                      104       105       106       107  
Unnamed: 0                                               
New Taipei City  0.320077  0.423941  0.481750  0.547374  
Taipei City      0.931126  1.000000  0.981122  0.980875  
Taoyuan City     0.348712  0.420503  0.428892  0.527270  
Taichung City    0.352245  0.407051  0.481912  0.512581  
Tainan City      0.136986  0.222553  0.256760  0.260450  
Kaohsiung City   0.392408  0.312652  0.398011  0.437867

In [33]:
df2.iloc[:, -d:].values

array([[0.4817505 , 0.547374  ],
       [0.98112208, 0.98087474],
       [0.42889231, 0.52726952],
       [0.48191202, 0.51258108],
       [0.25675996, 0.26044974],
       [0.39801126, 0.4378669 ]])

In [34]:
xgbr.predict(df2.iloc[:, -d:].values)

array([0.43286285, 0.9972046 , 0.43286285, 0.42804363, 0.28576434,
       0.42804363], dtype=float32)

In [35]:
df2['108'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
Unnamed: 0                                                                    
New Taipei City  0.115982  0.157424  0.187144  0.181006  0.215128  0.249491   
Taipei City      0.731342  0.807072  0.703622  0.787694  0.840547  0.862176   
Taoyuan City     0.134657  0.152977  0.157141  0.229988  0.234737  0.366141   
Taichung City    0.105896  0.187573  0.116866  0.146349  0.202857  0.308922   
Tainan City      0.107261  0.050582  0.016965  0.000000  0.095853  0.120380   
Kaohsiung City   0.251007  0.350317  0.145537  0.210383  0.267930  0.296338   

                      104       105       106       107       108  
Unnamed: 0                                                         
New Taipei City  0.320077  0.423941  0.481750  0.547374  0.432863  
Taipei City      0.931126  1.000000  0.981122  0.980875  0.997205  
Taoyuan City     0.348712  0.420503  0.428892  0.527270  0.432863  
Taichung City    0.352245  0.407051  0.481912  0.512581  0.428044  
Tainan City      0.136986  0.222553  0.256760  0.260450  0.285764  
Kaohsiung City   0.392408  0.312652  0.398011  0.437867  0.428044

In [36]:
df2['109'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
Unnamed: 0                                                                    
New Taipei City  0.115982  0.157424  0.187144  0.181006  0.215128  0.249491   
Taipei City      0.731342  0.807072  0.703622  0.787694  0.840547  0.862176   
Taoyuan City     0.134657  0.152977  0.157141  0.229988  0.234737  0.366141   
Taichung City    0.105896  0.187573  0.116866  0.146349  0.202857  0.308922   
Tainan City      0.107261  0.050582  0.016965  0.000000  0.095853  0.120380   
Kaohsiung City   0.251007  0.350317  0.145537  0.210383  0.267930  0.296338   

                      104       105       106       107       108       109  
Unnamed: 0                                                                   
New Taipei City  0.320077  0.423941  0.481750  0.547374  0.432863  0.614219  
Taipei City      0.931126  1.000000  0.981122  0.980875  0.997205  0.997205  
Taoyuan City     0.348712  0.420503  0.428892  0.527270  0.432863  0.428044  
Taichung City    0.352245  0.407051  0.481912  0.512581  0.428044  0.428044  
Tainan City      0.136986  0.222553  0.256760  0.260450  0.285764  0.388726  
Kaohsiung City   0.392408  0.312652  0.398011  0.437867  0.428044  0.428044

In [37]:
df2['110'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
Unnamed: 0                                                                    
New Taipei City  0.115982  0.157424  0.187144  0.181006  0.215128  0.249491   
Taipei City      0.731342  0.807072  0.703622  0.787694  0.840547  0.862176   
Taoyuan City     0.134657  0.152977  0.157141  0.229988  0.234737  0.366141   
Taichung City    0.105896  0.187573  0.116866  0.146349  0.202857  0.308922   
Tainan City      0.107261  0.050582  0.016965  0.000000  0.095853  0.120380   
Kaohsiung City   0.251007  0.350317  0.145537  0.210383  0.267930  0.296338   

                      104       105       106       107       108       109  \
Unnamed: 0                                                                    
New Taipei City  0.320077  0.423941  0.481750  0.547374  0.432863  0.614219   
Taipei City      0.931126  1.000000  0.981122  0.980875  0.997205  0.997205   
Taoyuan City     0.348712  0.420503  0.428892  0.527270  0.432863  0.428044   
Taichung City    0.352245  0.407051  0.481912  0.512581  0.428044  0.428044   
Tainan City      0.136986  0.222553  0.256760  0.260450  0.285764  0.388726   
Kaohsiung City   0.392408  0.312652  0.398011  0.437867  0.428044  0.428044   

                      110  
Unnamed: 0                 
New Taipei City  0.645517  
Taipei City      0.997205  
Taoyuan City     0.428044  
Taichung City    0.428044  
Tainan City      0.316061  
Kaohsiung City   0.428044

In [38]:
df2['111'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
Unnamed: 0                                                                    
New Taipei City  0.115982  0.157424  0.187144  0.181006  0.215128  0.249491   
Taipei City      0.731342  0.807072  0.703622  0.787694  0.840547  0.862176   
Taoyuan City     0.134657  0.152977  0.157141  0.229988  0.234737  0.366141   
Taichung City    0.105896  0.187573  0.116866  0.146349  0.202857  0.308922   
Tainan City      0.107261  0.050582  0.016965  0.000000  0.095853  0.120380   
Kaohsiung City   0.251007  0.350317  0.145537  0.210383  0.267930  0.296338   

                      104       105       106       107       108       109  \
Unnamed: 0                                                                    
New Taipei City  0.320077  0.423941  0.481750  0.547374  0.432863  0.614219   
Taipei City      0.931126  1.000000  0.981122  0.980875  0.997205  0.997205   
Taoyuan City     0.348712  0.420503  0.428892  0.527270  0.432863  0.428044   
Taichung City    0.352245  0.407051  0.481912  0.512581  0.428044  0.428044   
Tainan City      0.136986  0.222553  0.256760  0.260450  0.285764  0.388726   
Kaohsiung City   0.392408  0.312652  0.398011  0.437867  0.428044  0.428044   

                      110       111  
Unnamed: 0                           
New Taipei City  0.645517  0.831693  
Taipei City      0.997205  0.997205  
Taoyuan City     0.428044  0.428044  
Taichung City    0.428044  0.428044  
Tainan City      0.316061  0.430477  
Kaohsiung City   0.428044  0.428044

In [39]:
df2['112'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
Unnamed: 0                                                                    
New Taipei City  0.115982  0.157424  0.187144  0.181006  0.215128  0.249491   
Taipei City      0.731342  0.807072  0.703622  0.787694  0.840547  0.862176   
Taoyuan City     0.134657  0.152977  0.157141  0.229988  0.234737  0.366141   
Taichung City    0.105896  0.187573  0.116866  0.146349  0.202857  0.308922   
Tainan City      0.107261  0.050582  0.016965  0.000000  0.095853  0.120380   
Kaohsiung City   0.251007  0.350317  0.145537  0.210383  0.267930  0.296338   

                      104       105       106       107       108       109  \
Unnamed: 0                                                                    
New Taipei City  0.320077  0.423941  0.481750  0.547374  0.432863  0.614219   
Taipei City      0.931126  1.000000  0.981122  0.980875  0.997205  0.997205   
Taoyuan City     0.348712  0.420503  0.428892  0.527270  0.432863  0.428044   
Taichung City    0.352245  0.407051  0.481912  0.512581  0.428044  0.428044   
Tainan City      0.136986  0.222553  0.256760  0.260450  0.285764  0.388726   
Kaohsiung City   0.392408  0.312652  0.398011  0.437867  0.428044  0.428044   

                      110       111       112  
Unnamed: 0                                     
New Taipei City  0.645517  0.831693  0.857217  
Taipei City      0.997205  0.997205  0.997205  
Taoyuan City     0.428044  0.428044  0.428044  
Taichung City    0.428044  0.428044  0.428044  
Tainan City      0.316061  0.430477  0.389247  
Kaohsiung City   0.428044  0.428044  0.428044

In [40]:
df2['113'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
Unnamed: 0                                                                    
New Taipei City  0.115982  0.157424  0.187144  0.181006  0.215128  0.249491   
Taipei City      0.731342  0.807072  0.703622  0.787694  0.840547  0.862176   
Taoyuan City     0.134657  0.152977  0.157141  0.229988  0.234737  0.366141   
Taichung City    0.105896  0.187573  0.116866  0.146349  0.202857  0.308922   
Tainan City      0.107261  0.050582  0.016965  0.000000  0.095853  0.120380   
Kaohsiung City   0.251007  0.350317  0.145537  0.210383  0.267930  0.296338   

                      104       105       106       107       108       109  \
Unnamed: 0                                                                    
New Taipei City  0.320077  0.423941  0.481750  0.547374  0.432863  0.614219   
Taipei City      0.931126  1.000000  0.981122  0.980875  0.997205  0.997205   
Taoyuan City     0.348712  0.420503  0.428892  0.527270  0.432863  0.428044   
Taichung City    0.352245  0.407051  0.481912  0.512581  0.428044  0.428044   
Tainan City      0.136986  0.222553  0.256760  0.260450  0.285764  0.388726   
Kaohsiung City   0.392408  0.312652  0.398011  0.437867  0.428044  0.428044   

                      110       111       112       113  
Unnamed: 0                                               
New Taipei City  0.645517  0.831693  0.857217  0.930599  
Taipei City      0.997205  0.997205  0.997205  0.997205  
Taoyuan City     0.428044  0.428044  0.428044  0.428044  
Taichung City    0.428044  0.428044  0.428044  0.428044  
Tainan City      0.316061  0.430477  0.389247  0.428044  
Kaohsiung City   0.428044  0.428044  0.428044  0.428044

In [41]:
df2['114'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
Unnamed: 0                                                                    
New Taipei City  0.115982  0.157424  0.187144  0.181006  0.215128  0.249491   
Taipei City      0.731342  0.807072  0.703622  0.787694  0.840547  0.862176   
Taoyuan City     0.134657  0.152977  0.157141  0.229988  0.234737  0.366141   
Taichung City    0.105896  0.187573  0.116866  0.146349  0.202857  0.308922   
Tainan City      0.107261  0.050582  0.016965  0.000000  0.095853  0.120380   
Kaohsiung City   0.251007  0.350317  0.145537  0.210383  0.267930  0.296338   

                      104       105       106       107       108       109  \
Unnamed: 0                                                                    
New Taipei City  0.320077  0.423941  0.481750  0.547374  0.432863  0.614219   
Taipei City      0.931126  1.000000  0.981122  0.980875  0.997205  0.997205   
Taoyuan City     0.348712  0.420503  0.428892  0.527270  0.432863  0.428044   
Taichung City    0.352245  0.407051  0.481912  0.512581  0.428044  0.428044   
Tainan City      0.136986  0.222553  0.256760  0.260450  0.285764  0.388726   
Kaohsiung City   0.392408  0.312652  0.398011  0.437867  0.428044  0.428044   

                      110       111       112       113       114  
Unnamed: 0                                                         
New Taipei City  0.645517  0.831693  0.857217  0.930599  0.997205  
Taipei City      0.997205  0.997205  0.997205  0.997205  0.997205  
Taoyuan City     0.428044  0.428044  0.428044  0.428044  0.428044  
Taichung City    0.428044  0.428044  0.428044  0.428044  0.428044  
Tainan City      0.316061  0.430477  0.389247  0.428044  0.428044  
Kaohsiung City   0.428044  0.428044  0.428044  0.428044  0.428044

In [42]:
for i in range(len(df2)):
    for j in range(len(df2.columns)):
        df2.iloc[i, j] = (df2.iloc[i, j]*rangeing+min)
df2

98        99       100       101       102  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351.0  279239.0  278023.0  284783.0   
Taipei City      387052.795031  402056.0  381561.0  398217.0  408688.0   
Taoyuan City     268840.571429  272470.0  273295.0  287727.0  288668.0   
Taichung City    263142.638037  279324.0  265316.0  271157.0  282352.0   
Tainan City      263413.109756  252184.0  245524.0  242163.0  261153.0   
Kaohsiung City   291891.194969  311566.0  270996.0  283843.0  295244.0   

                      103       104       105       106       107  \
Unnamed: 0                                                          
New Taipei City  291591.0  305575.0  326152.0  337605.0  350606.0   
Taipei City      412973.0  426633.0  440278.0  436538.0  436489.0   
Taoyuan City     314701.0  311248.0  325471.0  327133.0  346623.0   
Taichung City    303365.0  311948.0  322806.0  337637.0  343713.0   
Tainan City      266012.0  269302.0  286254.0  293031.0  293762.0   
Kaohsiung City   300872.0  319905.0  304104.0  321015.0  328911.0   

                         108           109           110           111  \
Unnamed: 0                                                               
New Taipei City  327919.6250  363849.00000  370049.65625  406933.78125   
Taipei City      439724.1875  439724.18750  439724.18750  439724.18750   
Taoyuan City     327919.6250  326964.87500  326964.87500  326964.87500   
Taichung City    326964.8750  326964.87500  326964.87500  326964.87500   
Tainan City      298777.1875  319175.53125  304779.53125  327446.96875   
Kaohsiung City   326964.8750  326964.87500  326964.87500  326964.87500   

                         112          113          114  
Unnamed: 0                                              
New Taipei City  411990.5625  426528.6875  439724.1875  
Taipei City      439724.1875  439724.1875  439724.1875  
Taoyuan City     326964.8750  326964.8750  326964.8750  
Taichung City    326964.8750  326964.8750  326964.8750  
Tainan City      319278.7500  326964.8750  326964.8750  
Kaohsiung City   326964.8750  326964.8750  326964.8750

In [43]:
outputpath='C:/Users/Steven/Desktop/新增資料夾/income_update1.xlsx'
df2.to_excel(outputpath,index=True,header=True)