In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottle

In [3]:
df1 = pd.read_excel('population_df.xlsx')
df1

location        98        99       100       101       102  \
0  New Taipei City   3873653   3897367   3916451   3939305   3954929   
1      Taipei City   2607428   2618772   2650968   2673226   2686516   
2     Taoyuan City   1978782   2002060   2013305   2030161   2044023   
3    Taichung City   2635761   2648419   2664394   2684893   2701661   
4      Tainan City   1875406   1873794   1876960   1881645   1883208   
5   Kaohsiung City   2770887   2773483   2774470   2778659   2779877   
6           Taiwan  23119772  23162123  23224912  23315822  23373517   

        103       104       105       106       107       108  
0   3966818   3970644   3979208   3986689   3995717   4018696  
1   2702315   2704810   2695704   2683257   2668572   2645041  
2   2058328   2105780   2147763   2188017   2220872   2249037  
3   2719835   2744445   2767239   2787070   2803894   2815261  
4   1884284   1885541   1886033   1886522   1883831   1880906  
5   2778992   2778918   2779371   2776912   2773533   2773198  
6  23433753  23492074  23539816  23571227  23588932  23603121

In [4]:
df1.columns

Index(['location', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [5]:
df1.index = df1['location']

In [6]:
df1.columns

Index(['location', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [7]:
df1

location        98        99       100       101  \
location                                                                   
New Taipei City  New Taipei City   3873653   3897367   3916451   3939305   
Taipei City          Taipei City   2607428   2618772   2650968   2673226   
Taoyuan City        Taoyuan City   1978782   2002060   2013305   2030161   
Taichung City      Taichung City   2635761   2648419   2664394   2684893   
Tainan City          Tainan City   1875406   1873794   1876960   1881645   
Kaohsiung City    Kaohsiung City   2770887   2773483   2774470   2778659   
Taiwan                    Taiwan  23119772  23162123  23224912  23315822   

                      102       103       104       105       106       107  \
location                                                                      
New Taipei City   3954929   3966818   3970644   3979208   3986689   3995717   
Taipei City       2686516   2702315   2704810   2695704   2683257   2668572   
Taoyuan City      2044023   2058328   2105780   2147763   2188017   2220872   
Taichung City     2701661   2719835   2744445   2767239   2787070   2803894   
Tainan City       1883208   1884284   1885541   1886033   1886522   1883831   
Kaohsiung City    2779877   2778992   2778918   2779371   2776912   2773533   
Taiwan           23373517  23433753  23492074  23539816  23571227  23588932   

                      108  
location                   
New Taipei City   4018696  
Taipei City       2645041  
Taoyuan City      2249037  
Taichung City     2815261  
Tainan City       1880906  
Kaohsiung City    2773198  
Taiwan           23603121

In [8]:
df1 = df1.iloc[:-1, 1:-1]
df1

98       99       100      101      102      103  \
location                                                                
New Taipei City  3873653  3897367  3916451  3939305  3954929  3966818   
Taipei City      2607428  2618772  2650968  2673226  2686516  2702315   
Taoyuan City     1978782  2002060  2013305  2030161  2044023  2058328   
Taichung City    2635761  2648419  2664394  2684893  2701661  2719835   
Tainan City      1875406  1873794  1876960  1881645  1883208  1884284   
Kaohsiung City   2770887  2773483  2774470  2778659  2779877  2778992   

                     104      105      106      107  
location                                             
New Taipei City  3970644  3979208  3986689  3995717  
Taipei City      2704810  2695704  2683257  2668572  
Taoyuan City     2105780  2147763  2188017  2220872  
Taichung City    2744445  2767239  2787070  2803894  
Tainan City      1885541  1886033  1886522  1883831  
Kaohsiung City   2778918  2779371  2776912  2773533

In [9]:
col = []
for i in df1.columns:
    col.append(str(i))
col

['98', '99', '100', '101', '102', '103', '104', '105', '106', '107']

In [10]:
df1.columns = col
df1

98       99      100      101      102      103  \
location                                                                
New Taipei City  3873653  3897367  3916451  3939305  3954929  3966818   
Taipei City      2607428  2618772  2650968  2673226  2686516  2702315   
Taoyuan City     1978782  2002060  2013305  2030161  2044023  2058328   
Taichung City    2635761  2648419  2664394  2684893  2701661  2719835   
Tainan City      1875406  1873794  1876960  1881645  1883208  1884284   
Kaohsiung City   2770887  2773483  2774470  2778659  2779877  2778992   

                     104      105      106      107  
location                                             
New Taipei City  3970644  3979208  3986689  3995717  
Taipei City      2704810  2695704  2683257  2668572  
Taoyuan City     2105780  2147763  2188017  2220872  
Taichung City    2744445  2767239  2787070  2803894  
Tainan City      1885541  1886033  1886522  1883831  
Kaohsiung City   2778918  2779371  2776912  2773533

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, New Taipei City to Kaohsiung City
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   98      6 non-null      int64
 1   99      6 non-null      int64
 2   100     6 non-null      int64
 3   101     6 non-null      int64
 4   102     6 non-null      int64
 5   103     6 non-null      int64
 6   104     6 non-null      int64
 7   105     6 non-null      int64
 8   106     6 non-null      int64
 9   107     6 non-null      int64
dtypes: int64(10)
memory usage: 528.0+ bytes


In [12]:
df1

98       99      100      101      102      103  \
location                                                                
New Taipei City  3873653  3897367  3916451  3939305  3954929  3966818   
Taipei City      2607428  2618772  2650968  2673226  2686516  2702315   
Taoyuan City     1978782  2002060  2013305  2030161  2044023  2058328   
Taichung City    2635761  2648419  2664394  2684893  2701661  2719835   
Tainan City      1875406  1873794  1876960  1881645  1883208  1884284   
Kaohsiung City   2770887  2773483  2774470  2778659  2779877  2778992   

                     104      105      106      107  
location                                             
New Taipei City  3970644  3979208  3986689  3995717  
Taipei City      2704810  2695704  2683257  2668572  
Taoyuan City     2105780  2147763  2188017  2220872  
Taichung City    2744445  2767239  2787070  2803894  
Tainan City      1885541  1886033  1886522  1883831  
Kaohsiung City   2778918  2779371  2776912  2773533

In [13]:
min = df1.min().min()
rangeing = (df1.max().max())-(df1.min().min())
print(min)
print(rangeing)

1873794
2121923


In [14]:
for i in range(len(df1)):
    for j in range(len(df1.columns)):
        df1.iloc[i, j] = (df1.iloc[i, j]-min)/rangeing

### input為2維

In [15]:
d = int(input('輸入的維度：'))
x_train = []
y_train = []
x_test = []
y_test = []

for a in range(2):
    x_test.append([])
    y_test.append([])

for b in range(8-d):
    x_train.append([])
    y_train.append([])
    
for i in range(2):
    x_test[i] = (df1.iloc[:, -2-d+i:-2+i].values)
    y_test[i] = (df1.iloc[:, -2+i].values)

for j in range(8-d):
    x_train[j] = (df1.iloc[:, j:d+j].values)
    y_train[j] = (df1.iloc[:, d+j].values)

輸入的維度：2


In [16]:
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)

In [17]:
x_train

array([[[9.42474821e-01, 9.53650533e-01],
        [3.45740161e-01, 3.51086255e-01],
        [4.94777614e-02, 6.04479993e-02],
        [3.59092672e-01, 3.65058016e-01],
        [7.59688264e-04, 0.00000000e+00],
        [4.22773588e-01, 4.23997006e-01]],

       [[9.53650533e-01, 9.62644262e-01],
        [3.51086255e-01, 3.66259285e-01],
        [6.04479993e-02, 6.57474376e-02],
        [3.65058016e-01, 3.72586564e-01],
        [0.00000000e+00, 1.49204283e-03],
        [4.23997006e-01, 4.24462151e-01]],

       [[9.62644262e-01, 9.73414681e-01],
        [3.66259285e-01, 3.76748826e-01],
        [6.57474376e-02, 7.36911754e-02],
        [3.72586564e-01, 3.82247141e-01],
        [1.49204283e-03, 3.69994576e-03],
        [4.24462151e-01, 4.26436303e-01]],

       [[9.73414681e-01, 9.80777813e-01],
        [3.76748826e-01, 3.83012013e-01],
        [7.36911754e-02, 8.02239290e-02],
        [3.82247141e-01, 3.90149407e-01],
        [3.69994576e-03, 4.43654176e-03],
        [4.26436303e-01, 4.2

In [18]:
x_train.shape

(6, 6, 2)

In [19]:
y_train

array([[0.96264426, 0.36625928, 0.06574744, 0.37258656, 0.00149204,
        0.42446215],
       [0.97341468, 0.37674883, 0.07369118, 0.38224714, 0.00369995,
        0.4264363 ],
       [0.98077781, 0.38301201, 0.08022393, 0.39014941, 0.00443654,
        0.42701031],
       [0.98638075, 0.39045762, 0.08696546, 0.39871428, 0.00494363,
        0.42659324],
       [0.98818383, 0.39163344, 0.10932819, 0.41031225, 0.00553602,
        0.42655836],
       [0.99221979, 0.38734205, 0.12911354, 0.42105439, 0.00576788,
        0.42677185]])

In [20]:
y_train.shape

(6, 6)

In [21]:
x_test

array([[[0.98818383, 0.99221979],
        [0.39163344, 0.38734205],
        [0.10932819, 0.12911354],
        [0.41031225, 0.42105439],
        [0.00553602, 0.00576788],
        [0.42655836, 0.42677185]],

       [[0.99221979, 0.99574537],
        [0.38734205, 0.38147614],
        [0.12911354, 0.14808407],
        [0.42105439, 0.43040016],
        [0.00576788, 0.00599833],
        [0.42677185, 0.42561299]]])

In [22]:
y_test

array([[0.99574537, 0.38147614, 0.14808407, 0.43040016, 0.00599833,
        0.42561299],
       [1.        , 0.37455553, 0.16356767, 0.43832882, 0.00473014,
        0.42402057]])

In [23]:
x_train = x_train.reshape(-1, d)
y_train = y_train.ravel()
x_test = x_test.reshape(-1, d)
y_test = y_test.ravel()

In [24]:
x_train

array([[9.42474821e-01, 9.53650533e-01],
       [3.45740161e-01, 3.51086255e-01],
       [4.94777614e-02, 6.04479993e-02],
       [3.59092672e-01, 3.65058016e-01],
       [7.59688264e-04, 0.00000000e+00],
       [4.22773588e-01, 4.23997006e-01],
       [9.53650533e-01, 9.62644262e-01],
       [3.51086255e-01, 3.66259285e-01],
       [6.04479993e-02, 6.57474376e-02],
       [3.65058016e-01, 3.72586564e-01],
       [0.00000000e+00, 1.49204283e-03],
       [4.23997006e-01, 4.24462151e-01],
       [9.62644262e-01, 9.73414681e-01],
       [3.66259285e-01, 3.76748826e-01],
       [6.57474376e-02, 7.36911754e-02],
       [3.72586564e-01, 3.82247141e-01],
       [1.49204283e-03, 3.69994576e-03],
       [4.24462151e-01, 4.26436303e-01],
       [9.73414681e-01, 9.80777813e-01],
       [3.76748826e-01, 3.83012013e-01],
       [7.36911754e-02, 8.02239290e-02],
       [3.82247141e-01, 3.90149407e-01],
       [3.69994576e-03, 4.43654176e-03],
       [4.26436303e-01, 4.27010311e-01],
       [9.807778

In [25]:
y_train

array([0.96264426, 0.36625928, 0.06574744, 0.37258656, 0.00149204,
       0.42446215, 0.97341468, 0.37674883, 0.07369118, 0.38224714,
       0.00369995, 0.4264363 , 0.98077781, 0.38301201, 0.08022393,
       0.39014941, 0.00443654, 0.42701031, 0.98638075, 0.39045762,
       0.08696546, 0.39871428, 0.00494363, 0.42659324, 0.98818383,
       0.39163344, 0.10932819, 0.41031225, 0.00553602, 0.42655836,
       0.99221979, 0.38734205, 0.12911354, 0.42105439, 0.00576788,
       0.42677185])

In [26]:
from xgboost import XGBRegressor
xgbr = XGBRegressor(n_estimators=100 , max_depth=3 , learning_rate=0.1, subsample=1, colsample_bynode=0.8, reg_lambda=1e-05)
xgbr.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.8, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1e-05, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [27]:
xgbr.predict(x_test)

array([0.9912508 , 0.39105928, 0.12918532, 0.42188984, 0.00591932,
       0.42664364, 0.9912508 , 0.39142075, 0.12918532, 0.4245416 ,
       0.00591932, 0.42664364], dtype=float32)

In [28]:
y_test

array([0.99574537, 0.38147614, 0.14808407, 0.43040016, 0.00599833,
       0.42561299, 1.        , 0.37455553, 0.16356767, 0.43832882,
       0.00473014, 0.42402057])

In [29]:
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    print('MAPE為', MAPE)

MAPE為 0.006631473537923073
MAPE為 0.035074241220553165
MAPE為 0.1689121965494561
MAPE為 0.025613554213761956
MAPE為 0.13228826686797387
MAPE為 0.004303871322998471


In [30]:
number = 0 
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    number += MAPE
number /= 6
print('平均MAPE為', number)

平均MAPE為 0.06213726728544444


In [31]:
df1

98        99       100       101       102       103  \
location                                                                      
New Taipei City  0.942475  0.953651  0.962644  0.973415  0.980778  0.986381   
Taipei City      0.345740  0.351086  0.366259  0.376749  0.383012  0.390458   
Taoyuan City     0.049478  0.060448  0.065747  0.073691  0.080224  0.086965   
Taichung City    0.359093  0.365058  0.372587  0.382247  0.390149  0.398714   
Tainan City      0.000760  0.000000  0.001492  0.003700  0.004437  0.004944   
Kaohsiung City   0.422774  0.423997  0.424462  0.426436  0.427010  0.426593   

                      104       105       106       107  
location                                                 
New Taipei City  0.988184  0.992220  0.995745  1.000000  
Taipei City      0.391633  0.387342  0.381476  0.374556  
Taoyuan City     0.109328  0.129114  0.148084  0.163568  
Taichung City    0.410312  0.421054  0.430400  0.438329  
Tainan City      0.005536  0.005768  0.005998  0.004730  
Kaohsiung City   0.426558  0.426772  0.425613  0.424021

In [32]:
df2 = df1.copy()
df2

98        99       100       101       102       103  \
location                                                                      
New Taipei City  0.942475  0.953651  0.962644  0.973415  0.980778  0.986381   
Taipei City      0.345740  0.351086  0.366259  0.376749  0.383012  0.390458   
Taoyuan City     0.049478  0.060448  0.065747  0.073691  0.080224  0.086965   
Taichung City    0.359093  0.365058  0.372587  0.382247  0.390149  0.398714   
Tainan City      0.000760  0.000000  0.001492  0.003700  0.004437  0.004944   
Kaohsiung City   0.422774  0.423997  0.424462  0.426436  0.427010  0.426593   

                      104       105       106       107  
location                                                 
New Taipei City  0.988184  0.992220  0.995745  1.000000  
Taipei City      0.391633  0.387342  0.381476  0.374556  
Taoyuan City     0.109328  0.129114  0.148084  0.163568  
Taichung City    0.410312  0.421054  0.430400  0.438329  
Tainan City      0.005536  0.005768  0.005998  0.004730  
Kaohsiung City   0.426558  0.426772  0.425613  0.424021

In [33]:
df2.iloc[:, -d:].values

array([[0.99574537, 1.        ],
       [0.38147614, 0.37455553],
       [0.14808407, 0.16356767],
       [0.43040016, 0.43832882],
       [0.00599833, 0.00473014],
       [0.42561299, 0.42402057]])

In [34]:
xgbr.predict(df2.iloc[:, -d:].values)

array([0.9912508 , 0.39435646, 0.12918532, 0.42664364, 0.00572599,
       0.42650974], dtype=float32)

In [35]:
df2['108'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
location                                                                      
New Taipei City  0.942475  0.953651  0.962644  0.973415  0.980778  0.986381   
Taipei City      0.345740  0.351086  0.366259  0.376749  0.383012  0.390458   
Taoyuan City     0.049478  0.060448  0.065747  0.073691  0.080224  0.086965   
Taichung City    0.359093  0.365058  0.372587  0.382247  0.390149  0.398714   
Tainan City      0.000760  0.000000  0.001492  0.003700  0.004437  0.004944   
Kaohsiung City   0.422774  0.423997  0.424462  0.426436  0.427010  0.426593   

                      104       105       106       107       108  
location                                                           
New Taipei City  0.988184  0.992220  0.995745  1.000000  0.991251  
Taipei City      0.391633  0.387342  0.381476  0.374556  0.394356  
Taoyuan City     0.109328  0.129114  0.148084  0.163568  0.129185  
Taichung City    0.410312  0.421054  0.430400  0.438329  0.426644  
Tainan City      0.005536  0.005768  0.005998  0.004730  0.005726  
Kaohsiung City   0.426558  0.426772  0.425613  0.424021  0.426510

In [36]:
df2['109'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
location                                                                      
New Taipei City  0.942475  0.953651  0.962644  0.973415  0.980778  0.986381   
Taipei City      0.345740  0.351086  0.366259  0.376749  0.383012  0.390458   
Taoyuan City     0.049478  0.060448  0.065747  0.073691  0.080224  0.086965   
Taichung City    0.359093  0.365058  0.372587  0.382247  0.390149  0.398714   
Tainan City      0.000760  0.000000  0.001492  0.003700  0.004437  0.004944   
Kaohsiung City   0.422774  0.423997  0.424462  0.426436  0.427010  0.426593   

                      104       105       106       107       108       109  
location                                                                     
New Taipei City  0.988184  0.992220  0.995745  1.000000  0.991251  0.991251  
Taipei City      0.391633  0.387342  0.381476  0.374556  0.394356  0.390510  
Taoyuan City     0.109328  0.129114  0.148084  0.163568  0.129185  0.129185  
Taichung City    0.410312  0.421054  0.430400  0.438329  0.426644  0.426644  
Tainan City      0.005536  0.005768  0.005998  0.004730  0.005726  0.005919  
Kaohsiung City   0.426558  0.426772  0.425613  0.424021  0.426510  0.426379

In [37]:
df2['110'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
location                                                                      
New Taipei City  0.942475  0.953651  0.962644  0.973415  0.980778  0.986381   
Taipei City      0.345740  0.351086  0.366259  0.376749  0.383012  0.390458   
Taoyuan City     0.049478  0.060448  0.065747  0.073691  0.080224  0.086965   
Taichung City    0.359093  0.365058  0.372587  0.382247  0.390149  0.398714   
Tainan City      0.000760  0.000000  0.001492  0.003700  0.004437  0.004944   
Kaohsiung City   0.422774  0.423997  0.424462  0.426436  0.427010  0.426593   

                      104       105       106       107       108       109  \
location                                                                      
New Taipei City  0.988184  0.992220  0.995745  1.000000  0.991251  0.991251   
Taipei City      0.391633  0.387342  0.381476  0.374556  0.394356  0.390510   
Taoyuan City     0.109328  0.129114  0.148084  0.163568  0.129185  0.129185   
Taichung City    0.410312  0.421054  0.430400  0.438329  0.426644  0.426644   
Tainan City      0.005536  0.005768  0.005998  0.004730  0.005726  0.005919   
Kaohsiung City   0.426558  0.426772  0.425613  0.424021  0.426510  0.426379   

                      110  
location                   
New Taipei City  0.991251  
Taipei City      0.388993  
Taoyuan City     0.129185  
Taichung City    0.426644  
Tainan City      0.005919  
Kaohsiung City   0.426644

In [38]:
df2['111'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
location                                                                      
New Taipei City  0.942475  0.953651  0.962644  0.973415  0.980778  0.986381   
Taipei City      0.345740  0.351086  0.366259  0.376749  0.383012  0.390458   
Taoyuan City     0.049478  0.060448  0.065747  0.073691  0.080224  0.086965   
Taichung City    0.359093  0.365058  0.372587  0.382247  0.390149  0.398714   
Tainan City      0.000760  0.000000  0.001492  0.003700  0.004437  0.004944   
Kaohsiung City   0.422774  0.423997  0.424462  0.426436  0.427010  0.426593   

                      104       105       106       107       108       109  \
location                                                                      
New Taipei City  0.988184  0.992220  0.995745  1.000000  0.991251  0.991251   
Taipei City      0.391633  0.387342  0.381476  0.374556  0.394356  0.390510   
Taoyuan City     0.109328  0.129114  0.148084  0.163568  0.129185  0.129185   
Taichung City    0.410312  0.421054  0.430400  0.438329  0.426644  0.426644   
Tainan City      0.005536  0.005768  0.005998  0.004730  0.005726  0.005919   
Kaohsiung City   0.426558  0.426772  0.425613  0.424021  0.426510  0.426379   

                      110       111  
location                             
New Taipei City  0.991251  0.991251  
Taipei City      0.388993  0.391059  
Taoyuan City     0.129185  0.129185  
Taichung City    0.426644  0.426644  
Tainan City      0.005919  0.005919  
Kaohsiung City   0.426644  0.426644

In [39]:
df2['112'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
location                                                                      
New Taipei City  0.942475  0.953651  0.962644  0.973415  0.980778  0.986381   
Taipei City      0.345740  0.351086  0.366259  0.376749  0.383012  0.390458   
Taoyuan City     0.049478  0.060448  0.065747  0.073691  0.080224  0.086965   
Taichung City    0.359093  0.365058  0.372587  0.382247  0.390149  0.398714   
Tainan City      0.000760  0.000000  0.001492  0.003700  0.004437  0.004944   
Kaohsiung City   0.422774  0.423997  0.424462  0.426436  0.427010  0.426593   

                      104       105       106       107       108       109  \
location                                                                      
New Taipei City  0.988184  0.992220  0.995745  1.000000  0.991251  0.991251   
Taipei City      0.391633  0.387342  0.381476  0.374556  0.394356  0.390510   
Taoyuan City     0.109328  0.129114  0.148084  0.163568  0.129185  0.129185   
Taichung City    0.410312  0.421054  0.430400  0.438329  0.426644  0.426644   
Tainan City      0.005536  0.005768  0.005998  0.004730  0.005726  0.005919   
Kaohsiung City   0.426558  0.426772  0.425613  0.424021  0.426510  0.426379   

                      110       111       112  
location                                       
New Taipei City  0.991251  0.991251  0.991251  
Taipei City      0.388993  0.391059  0.390272  
Taoyuan City     0.129185  0.129185  0.129185  
Taichung City    0.426644  0.426644  0.426644  
Tainan City      0.005919  0.005919  0.005919  
Kaohsiung City   0.426644  0.426644  0.426644

In [40]:
df2['113'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
location                                                                      
New Taipei City  0.942475  0.953651  0.962644  0.973415  0.980778  0.986381   
Taipei City      0.345740  0.351086  0.366259  0.376749  0.383012  0.390458   
Taoyuan City     0.049478  0.060448  0.065747  0.073691  0.080224  0.086965   
Taichung City    0.359093  0.365058  0.372587  0.382247  0.390149  0.398714   
Tainan City      0.000760  0.000000  0.001492  0.003700  0.004437  0.004944   
Kaohsiung City   0.422774  0.423997  0.424462  0.426436  0.427010  0.426593   

                      104       105       106       107       108       109  \
location                                                                      
New Taipei City  0.988184  0.992220  0.995745  1.000000  0.991251  0.991251   
Taipei City      0.391633  0.387342  0.381476  0.374556  0.394356  0.390510   
Taoyuan City     0.109328  0.129114  0.148084  0.163568  0.129185  0.129185   
Taichung City    0.410312  0.421054  0.430400  0.438329  0.426644  0.426644   
Tainan City      0.005536  0.005768  0.005998  0.004730  0.005726  0.005919   
Kaohsiung City   0.426558  0.426772  0.425613  0.424021  0.426510  0.426379   

                      110       111       112       113  
location                                                 
New Taipei City  0.991251  0.991251  0.991251  0.991251  
Taipei City      0.388993  0.391059  0.390272  0.391059  
Taoyuan City     0.129185  0.129185  0.129185  0.129185  
Taichung City    0.426644  0.426644  0.426644  0.426644  
Tainan City      0.005919  0.005919  0.005919  0.005919  
Kaohsiung City   0.426644  0.426644  0.426644  0.426644

In [41]:
df2['114'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98        99       100       101       102       103  \
location                                                                      
New Taipei City  0.942475  0.953651  0.962644  0.973415  0.980778  0.986381   
Taipei City      0.345740  0.351086  0.366259  0.376749  0.383012  0.390458   
Taoyuan City     0.049478  0.060448  0.065747  0.073691  0.080224  0.086965   
Taichung City    0.359093  0.365058  0.372587  0.382247  0.390149  0.398714   
Tainan City      0.000760  0.000000  0.001492  0.003700  0.004437  0.004944   
Kaohsiung City   0.422774  0.423997  0.424462  0.426436  0.427010  0.426593   

                      104       105       106       107       108       109  \
location                                                                      
New Taipei City  0.988184  0.992220  0.995745  1.000000  0.991251  0.991251   
Taipei City      0.391633  0.387342  0.381476  0.374556  0.394356  0.390510   
Taoyuan City     0.109328  0.129114  0.148084  0.163568  0.129185  0.129185   
Taichung City    0.410312  0.421054  0.430400  0.438329  0.426644  0.426644   
Tainan City      0.005536  0.005768  0.005998  0.004730  0.005726  0.005919   
Kaohsiung City   0.426558  0.426772  0.425613  0.424021  0.426510  0.426379   

                      110       111       112       113       114  
location                                                           
New Taipei City  0.991251  0.991251  0.991251  0.991251  0.991251  
Taipei City      0.388993  0.391059  0.390272  0.391059  0.390272  
Taoyuan City     0.129185  0.129185  0.129185  0.129185  0.129185  
Taichung City    0.426644  0.426644  0.426644  0.426644  0.426644  
Tainan City      0.005919  0.005919  0.005919  0.005919  0.005919  
Kaohsiung City   0.426644  0.426644  0.426644  0.426644  0.426644

In [42]:
for i in range(len(df2)):
    for j in range(len(df2.columns)):
        df2.iloc[i, j] = (df2.iloc[i, j]*rangeing+min)
df2

98         99        100        101        102  \
location                                                                 
New Taipei City  3873653.0  3897367.0  3916451.0  3939305.0  3954929.0   
Taipei City      2607428.0  2618772.0  2650968.0  2673226.0  2686516.0   
Taoyuan City     1978782.0  2002060.0  2013305.0  2030161.0  2044023.0   
Taichung City    2635761.0  2648419.0  2664394.0  2684893.0  2701661.0   
Tainan City      1875406.0  1873794.0  1876960.0  1881645.0  1883208.0   
Kaohsiung City   2770887.0  2773483.0  2774470.0  2778659.0  2779877.0   

                       103        104        105        106        107  \
location                                                                 
New Taipei City  3966818.0  3970644.0  3979208.0  3986689.0  3995717.0   
Taipei City      2702315.0  2704810.0  2695704.0  2683257.0  2668572.0   
Taoyuan City     2058328.0  2105780.0  2147763.0  2188017.0  2220872.0   
Taichung City    2719835.0  2744445.0  2767239.0  2787070.0  2803894.0   
Tainan City      1884284.0  1885541.0  1886033.0  1886522.0  1883831.0   
Kaohsiung City   2778992.0  2778918.0  2779371.0  2776912.0  2773533.0   

                         108          109          110          111  \
location                                                              
New Taipei City  3977152.000  3977152.000  3977152.000  3977152.000   
Taipei City      2710588.000  2702426.750  2699206.250  2703591.750   
Taoyuan City     2147915.250  2147915.250  2147915.250  2147915.250   
Taichung City    2779099.000  2779099.000  2779099.000  2779099.000   
Tainan City      1885944.125  1886354.375  1886354.375  1886354.375   
Kaohsiung City   2778814.750  2778537.500  2779099.000  2779099.000   

                         112          113          114  
location                                                
New Taipei City  3977152.000  3977152.000  3977152.000  
Taipei City      2701920.750  2703591.750  2701920.750  
Taoyuan City     2147915.250  2147915.250  2147915.250  
Taichung City    2779099.000  2779099.000  2779099.000  
Tainan City      1886354.375  1886354.375  1886354.375  
Kaohsiung City   2779099.000  2779099.000  2779099.000

In [43]:
outputpath='C:/Users/Steven/Desktop/新增資料夾/population_update1.xlsx'
df2.to_excel(outputpath,index=True,header=True)