In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottle

In [3]:
df1 = pd.read_excel('birth_df.xlsx')
df1

million      98      99     100     101     102     103     104  \
0  New Taipei City   32255   32093   27617   34323   22854   35915   38604   
1      Taipei City   20691   19403   18530   25132   22258   26710   29024   
2     Taoyuan City   19180   18515   15838   18041   16856   16757   17360   
3    Taichung City   23647   22601   19537   24027   20499   24555   26194   
4      Tainan City   14773   14196   11612   14208   17752   14788   15426   
5   Kaohsiung City   22182   11116   18684   21411   24963   21626   22520   
6           Taiwan  191310  166886  196627  229481  199113  210383  213598   

      105     106     107  108  
0   36313   34331   31611  NaN  
1   28987   27992   25042  NaN  
2   22384   23786   23356  NaN  
3   26313   25655   24338  NaN  
4   22469   14698   13773  NaN  
5   12044   21757   20260  NaN  
6  208440  193844  181601  NaN

In [4]:
df1.index = df1['million']

In [5]:
df1.columns

Index(['million', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [6]:
df1

million      98      99     100     101     102  \
million                                                                    
New Taipei City  New Taipei City   32255   32093   27617   34323   22854   
Taipei City          Taipei City   20691   19403   18530   25132   22258   
Taoyuan City        Taoyuan City   19180   18515   15838   18041   16856   
Taichung City      Taichung City   23647   22601   19537   24027   20499   
Tainan City          Tainan City   14773   14196   11612   14208   17752   
Kaohsiung City    Kaohsiung City   22182   11116   18684   21411   24963   
Taiwan                    Taiwan  191310  166886  196627  229481  199113   

                    103     104     105     106     107  108  
million                                                       
New Taipei City   35915   38604   36313   34331   31611  NaN  
Taipei City       26710   29024   28987   27992   25042  NaN  
Taoyuan City      16757   17360   22384   23786   23356  NaN  
Taichung City     24555   26194   26313   25655   24338  NaN  
Tainan City       14788   15426   22469   14698   13773  NaN  
Kaohsiung City    21626   22520   12044   21757   20260  NaN  
Taiwan           210383  213598  208440  193844  181601  NaN

In [7]:
df1 = df1.iloc[:-1, 1:-1]
df1

98     99     100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107  
million                        
New Taipei City  34331  31611  
Taipei City      27992  25042  
Taoyuan City     23786  23356  
Taichung City    25655  24338  
Tainan City      14698  13773  
Kaohsiung City   21757  20260

In [8]:
col = []
for i in df1.columns:
    col.append(str(i))
col

['98', '99', '100', '101', '102', '103', '104', '105', '106', '107']

In [9]:
df1.columns = col
df1

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107  
million                        
New Taipei City  34331  31611  
Taipei City      27992  25042  
Taoyuan City     23786  23356  
Taichung City    25655  24338  
Tainan City      14698  13773  
Kaohsiung City   21757  20260

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, New Taipei City to Kaohsiung City
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   98      6 non-null      int64
 1   99      6 non-null      int64
 2   100     6 non-null      int64
 3   101     6 non-null      int64
 4   102     6 non-null      int64
 5   103     6 non-null      int64
 6   104     6 non-null      int64
 7   105     6 non-null      int64
 8   106     6 non-null      int64
 9   107     6 non-null      int64
dtypes: int64(10)
memory usage: 528.0+ bytes


### input為n維

In [12]:
d = int(input('輸入的維度：'))
x_train = []
y_train = []
x_test = []
y_test = []

for a in range(2):
    x_test.append([])
    y_test.append([])

for b in range(8-d):
    x_train.append([])
    y_train.append([])
    
for i in range(2):
    x_test[i] = (df1.iloc[:, -2-d+i:-2+i].values)
    y_test[i] = (df1.iloc[:, -2+i].values)

for j in range(8-d):
    x_train[j] = (df1.iloc[:, j:d+j].values)
    y_train[j] = (df1.iloc[:, d+j].values)

輸入的維度：2


In [13]:
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)

In [14]:
x_train

array([[[32255, 32093],
        [20691, 19403],
        [19180, 18515],
        [23647, 22601],
        [14773, 14196],
        [22182, 11116]],

       [[32093, 27617],
        [19403, 18530],
        [18515, 15838],
        [22601, 19537],
        [14196, 11612],
        [11116, 18684]],

       [[27617, 34323],
        [18530, 25132],
        [15838, 18041],
        [19537, 24027],
        [11612, 14208],
        [18684, 21411]],

       [[34323, 22854],
        [25132, 22258],
        [18041, 16856],
        [24027, 20499],
        [14208, 17752],
        [21411, 24963]],

       [[22854, 35915],
        [22258, 26710],
        [16856, 16757],
        [20499, 24555],
        [17752, 14788],
        [24963, 21626]],

       [[35915, 38604],
        [26710, 29024],
        [16757, 17360],
        [24555, 26194],
        [14788, 15426],
        [21626, 22520]]], dtype=int64)

In [15]:
x_train.shape

(6, 6, 2)

In [16]:
y_train

array([[27617, 18530, 15838, 19537, 11612, 18684],
       [34323, 25132, 18041, 24027, 14208, 21411],
       [22854, 22258, 16856, 20499, 17752, 24963],
       [35915, 26710, 16757, 24555, 14788, 21626],
       [38604, 29024, 17360, 26194, 15426, 22520],
       [36313, 28987, 22384, 26313, 22469, 12044]], dtype=int64)

In [17]:
y_train.shape

(6, 6)

In [18]:
x_test

array([[[38604, 36313],
        [29024, 28987],
        [17360, 22384],
        [26194, 26313],
        [15426, 22469],
        [22520, 12044]],

       [[36313, 34331],
        [28987, 27992],
        [22384, 23786],
        [26313, 25655],
        [22469, 14698],
        [12044, 21757]]], dtype=int64)

In [19]:
y_test

array([[34331, 27992, 23786, 25655, 14698, 21757],
       [31611, 25042, 23356, 24338, 13773, 20260]], dtype=int64)

In [20]:
x_train = x_train.reshape(-1, d)
y_train = y_train.ravel()
x_test = x_test.reshape(-1, d)
y_test = y_test.ravel()

In [21]:
x_train

array([[32255, 32093],
       [20691, 19403],
       [19180, 18515],
       [23647, 22601],
       [14773, 14196],
       [22182, 11116],
       [32093, 27617],
       [19403, 18530],
       [18515, 15838],
       [22601, 19537],
       [14196, 11612],
       [11116, 18684],
       [27617, 34323],
       [18530, 25132],
       [15838, 18041],
       [19537, 24027],
       [11612, 14208],
       [18684, 21411],
       [34323, 22854],
       [25132, 22258],
       [18041, 16856],
       [24027, 20499],
       [14208, 17752],
       [21411, 24963],
       [22854, 35915],
       [22258, 26710],
       [16856, 16757],
       [20499, 24555],
       [17752, 14788],
       [24963, 21626],
       [35915, 38604],
       [26710, 29024],
       [16757, 17360],
       [24555, 26194],
       [14788, 15426],
       [21626, 22520]], dtype=int64)

In [22]:
y_train

array([27617, 18530, 15838, 19537, 11612, 18684, 34323, 25132, 18041,
       24027, 14208, 21411, 22854, 22258, 16856, 20499, 17752, 24963,
       35915, 26710, 16757, 24555, 14788, 21626, 38604, 29024, 17360,
       26194, 15426, 22520, 36313, 28987, 22384, 26313, 22469, 12044],
      dtype=int64)

In [23]:
from xgboost import XGBRegressor
xgbr = XGBRegressor(n_estimators=100 , max_depth=3 , learning_rate=0.1, subsample=1, colsample_bynode=0.8, reg_lambda=1e-05)
xgbr.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.8, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1e-05, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [24]:
xgbr.predict(x_test)

array([37640.332, 27009.807, 20270.947, 28172.996, 17571.738, 22695.816,
       31092.463, 27019.363, 27435.6  , 28172.996, 22159.357, 20858.367],
      dtype=float32)

In [25]:
y_test

array([34331, 27992, 23786, 25655, 14698, 21757, 31611, 25042, 23356,
       24338, 13773, 20260], dtype=int64)

In [26]:
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    print('MAPE為', MAPE)

MAPE為 0.05639927737321211
MAPE為 0.05702511740423184
MAPE為 0.16122426163016612
MAPE為 0.12786035832015857
MAPE為 0.4022086918940509
MAPE為 0.03634224866806265


In [27]:
number = 0 
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    number += MAPE
number /= 6
print('平均MAPE為', number)

平均MAPE為 0.14017665921498038


In [28]:
number = 0
for i in range(len(xgbr.predict(x_test) - y_test)):
    number += ((xgbr.predict(x_test) - y_test)[i])**2
    
number /= len(xgbr.predict(x_test) - y_test)
print('平均MSE為', number)

平均MSE為 12164186.557153383


```
輸入為1D的平均MAPE為0.12888944257531462
         平均MSE為 17930530.46018545
輸入為2D的平均MAPE為0.14017665921498038
         平均MSE為 12164186.557153383
輸入為3D的平均MAPE為0.1364862293375502
         平均MSE為 13009518.58934466
輸入為4D的平均MAPE為0.16044767651193326
         平均MSE為 15189380.450484911
輸入為5D的平均MAPE為0.15570076271906588
         平均MSE為 14309323.882553736
```

## 選擇2D！！！

In [29]:
df1

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107  
million                        
New Taipei City  34331  31611  
Taipei City      27992  25042  
Taoyuan City     23786  23356  
Taichung City    25655  24338  
Tainan City      14698  13773  
Kaohsiung City   21757  20260

In [30]:
df2 = df1.copy()
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107  
million                        
New Taipei City  34331  31611  
Taipei City      27992  25042  
Taoyuan City     23786  23356  
Taichung City    25655  24338  
Tainan City      14698  13773  
Kaohsiung City   21757  20260

In [31]:
df2.iloc[:, -d:].values

array([[34331, 31611],
       [27992, 25042],
       [23786, 23356],
       [25655, 24338],
       [14698, 13773],
       [21757, 20260]], dtype=int64)

In [32]:
xgbr.predict(df2.iloc[:, -d:].values)

array([31286.455, 26469.15 , 27007.33 , 28339.703, 12119.2  , 16526.07 ],
      dtype=float32)

In [33]:
df2['108'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107           108  
million                                      
New Taipei City  34331  31611  31286.455078  
Taipei City      27992  25042  26469.150391  
Taoyuan City     23786  23356  27007.330078  
Taichung City    25655  24338  28339.703125  
Tainan City      14698  13773  12119.200195  
Kaohsiung City   21757  20260  16526.070312

In [34]:
df2['109'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107           108           109  
million                                                    
New Taipei City  34331  31611  31286.455078  29692.728516  
Taipei City      27992  25042  26469.150391  26807.716797  
Taoyuan City     23786  23356  27007.330078  27432.810547  
Taichung City    25655  24338  28339.703125  27539.292969  
Tainan City      14698  13773  12119.200195  14128.716797  
Kaohsiung City   21757  20260  16526.070312  19311.265625

In [35]:
df2['110'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107           108           109           110  
million                                                                  
New Taipei City  34331  31611  31286.455078  29692.728516  33974.882812  
Taipei City      27992  25042  26469.150391  26807.716797  28474.800781  
Taoyuan City     23786  23356  27007.330078  27432.810547  28814.875000  
Taichung City    25655  24338  28339.703125  27539.292969  27019.363281  
Tainan City      14698  13773  12119.200195  14128.716797  15692.099609  
Kaohsiung City   21757  20260  16526.070312  19311.265625  21870.410156

In [36]:
df2['111'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107           108           109           110  \
million                                                                   
New Taipei City  34331  31611  31286.455078  29692.728516  33974.882812   
Taipei City      27992  25042  26469.150391  26807.716797  28474.800781   
Taoyuan City     23786  23356  27007.330078  27432.810547  28814.875000   
Taichung City    25655  24338  28339.703125  27539.292969  27019.363281   
Tainan City      14698  13773  12119.200195  14128.716797  15692.099609   
Kaohsiung City   21757  20260  16526.070312  19311.265625  21870.410156   

                          111  
million                        
New Taipei City  23200.667969  
Taipei City      28805.318359  
Taoyuan City     27009.806641  
Taichung City    26679.289062  
Tainan City      16370.118164  
Kaohsiung City   22977.884766

In [37]:
df2['112'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107           108           109           110  \
million                                                                   
New Taipei City  34331  31611  31286.455078  29692.728516  33974.882812   
Taipei City      27992  25042  26469.150391  26807.716797  28474.800781   
Taoyuan City     23786  23356  27007.330078  27432.810547  28814.875000   
Taichung City    25655  24338  28339.703125  27539.292969  27019.363281   
Tainan City      14698  13773  12119.200195  14128.716797  15692.099609   
Kaohsiung City   21757  20260  16526.070312  19311.265625  21870.410156   

                          111           112  
million                                      
New Taipei City  23200.667969  35740.445312  
Taipei City      28805.318359  27009.806641  
Taoyuan City     27009.806641  26679.289062  
Taichung City    26679.289062  28474.800781  
Tainan City      16370.118164  19896.466797  
Kaohsiung City   22977.884766  20098.812500

In [38]:
df2['113'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107           108           109           110  \
million                                                                   
New Taipei City  34331  31611  31286.455078  29692.728516  33974.882812   
Taipei City      27992  25042  26469.150391  26807.716797  28474.800781   
Taoyuan City     23786  23356  27007.330078  27432.810547  28814.875000   
Taichung City    25655  24338  28339.703125  27539.292969  27019.363281   
Tainan City      14698  13773  12119.200195  14128.716797  15692.099609   
Kaohsiung City   21757  20260  16526.070312  19311.265625  21870.410156   

                          111           112           113  
million                                                    
New Taipei City  23200.667969  35740.445312  38344.253906  
Taipei City      28805.318359  27009.806641  26679.289062  
Taoyuan City     27009.806641  26679.289062  28474.800781  
Taichung City    26679.289062  28474.800781  28805.318359  
Tainan City      16370.118164  19896.466797  21870.410156  
Kaohsiung City   22977.884766  20098.812500  24765.357422

In [39]:
df2['114'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  32255  32093  27617  34323  22854  35915  38604  36313   
Taipei City      20691  19403  18530  25132  22258  26710  29024  28987   
Taoyuan City     19180  18515  15838  18041  16856  16757  17360  22384   
Taichung City    23647  22601  19537  24027  20499  24555  26194  26313   
Tainan City      14773  14196  11612  14208  17752  14788  15426  22469   
Kaohsiung City   22182  11116  18684  21411  24963  21626  22520  12044   

                   106    107           108           109           110  \
million                                                                   
New Taipei City  34331  31611  31286.455078  29692.728516  33974.882812   
Taipei City      27992  25042  26469.150391  26807.716797  28474.800781   
Taoyuan City     23786  23356  27007.330078  27432.810547  28814.875000   
Taichung City    25655  24338  28339.703125  27539.292969  27019.363281   
Tainan City      14698  13773  12119.200195  14128.716797  15692.099609   
Kaohsiung City   21757  20260  16526.070312  19311.265625  21870.410156   

                          111           112           113           114  
million                                                                  
New Taipei City  23200.667969  35740.445312  38344.253906  36277.570312  
Taipei City      28805.318359  27009.806641  26679.289062  28474.800781  
Taoyuan City     27009.806641  26679.289062  28474.800781  28805.318359  
Taichung City    26679.289062  28474.800781  28805.318359  27009.806641  
Tainan City      16370.118164  19896.466797  21870.410156  20951.187500  
Kaohsiung City   22977.884766  20098.812500  24765.357422  24833.892578

In [40]:
outputpath='C:/Users/Steven/Desktop/新增資料夾/birth_update.xlsx'
df2.to_excel(outputpath,index=True,header=True)