In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottle

In [3]:
df1 = pd.read_excel('city_annual_expend_df.xlsx')
df1

million             98             99            100  \
0  New Taipei City   96578.611019   98880.514918  101597.893147   
1      Taipei City  148192.887258  155531.416179  162280.646270   
2     Taoyuan City   45593.320794   48076.080794   48577.653444   
3    Taichung City   75788.780000   74185.000000   77484.420000   
4      Tainan City   58714.480000   59532.477000   64737.220000   
5   Kaohsiung City  102063.120000  117931.345000  115951.800000   
6           Taiwan  807522.000000  867824.000000  882066.000000   

             101            102            103            104           105  \
0  145899.009050  149866.518605  146754.099649  154473.463926  1.516608e+05   
1  173139.571548  176075.234609  169580.238024  167504.327527  1.541876e+05   
2   57174.898426   58093.627307   57736.471325   62760.000000  8.497782e+04   
3   96887.312546   99883.362462  109538.016083  104869.032822  1.131774e+05   
4   77578.825927   82584.343311   77916.851738   73521.376929  6.949806e+04   
5  126711.535220  124889.951539  122071.850246  126265.671271  1.199338e+05   
6  986397.000000  998285.000000  987590.000000  999547.000000  1.002236e+06   

          106           107       108  
0   148828.44  1.488284e+05  166966.0  
1   162256.23  1.622562e+05  165546.0  
2    95094.42  9.509442e+04  115998.0  
3   123807.59  1.238076e+05  124657.0  
4    74696.14  7.469614e+04   86319.0  
5   121757.81  1.217580e+05  133542.0  
6  1014904.00  1.036507e+06       NaN

In [4]:
df1.index = df1['million']

In [5]:
df1.columns

Index(['million', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [6]:
df1

million             98             99            100  \
million                                                                         
New Taipei City  New Taipei City   96578.611019   98880.514918  101597.893147   
Taipei City          Taipei City  148192.887258  155531.416179  162280.646270   
Taoyuan City        Taoyuan City   45593.320794   48076.080794   48577.653444   
Taichung City      Taichung City   75788.780000   74185.000000   77484.420000   
Tainan City          Tainan City   58714.480000   59532.477000   64737.220000   
Kaohsiung City    Kaohsiung City  102063.120000  117931.345000  115951.800000   
Taiwan                    Taiwan  807522.000000  867824.000000  882066.000000   

                           101            102            103            104  \
million                                                                       
New Taipei City  145899.009050  149866.518605  146754.099649  154473.463926   
Taipei City      173139.571548  176075.234609  169580.238024  167504.327527   
Taoyuan City      57174.898426   58093.627307   57736.471325   62760.000000   
Taichung City     96887.312546   99883.362462  109538.016083  104869.032822   
Tainan City       77578.825927   82584.343311   77916.851738   73521.376929   
Kaohsiung City   126711.535220  124889.951539  122071.850246  126265.671271   
Taiwan           986397.000000  998285.000000  987590.000000  999547.000000   

                          105         106           107       108  
million                                                            
New Taipei City  1.516608e+05   148828.44  1.488284e+05  166966.0  
Taipei City      1.541876e+05   162256.23  1.622562e+05  165546.0  
Taoyuan City     8.497782e+04    95094.42  9.509442e+04  115998.0  
Taichung City    1.131774e+05   123807.59  1.238076e+05  124657.0  
Tainan City      6.949806e+04    74696.14  7.469614e+04   86319.0  
Kaohsiung City   1.199338e+05   121757.81  1.217580e+05  133542.0  
Taiwan           1.002236e+06  1014904.00  1.036507e+06       NaN

In [7]:
df1 = df1.iloc[:-1, 1:-1]
df1

98             99             100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107  
million                                    
New Taipei City  148828.44  148828.437264  
Taipei City      162256.23  162256.234058  
Taoyuan City      95094.42   95094.418061  
Taichung City    123807.59  123807.590957  
Tainan City       74696.14   74696.140442  
Kaohsiung City   121757.81  121758.000000

In [8]:
col = []
for i in df1.columns:
    col.append(str(i))
col

['98', '99', '100', '101', '102', '103', '104', '105', '106', '107']

In [9]:
df1.columns = col
df1

98             99            100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107  
million                                    
New Taipei City  148828.44  148828.437264  
Taipei City      162256.23  162256.234058  
Taoyuan City      95094.42   95094.418061  
Taichung City    123807.59  123807.590957  
Tainan City       74696.14   74696.140442  
Kaohsiung City   121757.81  121758.000000

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, New Taipei City to Kaohsiung City
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   98      6 non-null      float64
 1   99      6 non-null      float64
 2   100     6 non-null      float64
 3   101     6 non-null      float64
 4   102     6 non-null      float64
 5   103     6 non-null      float64
 6   104     6 non-null      float64
 7   105     6 non-null      float64
 8   106     6 non-null      float64
 9   107     6 non-null      float64
dtypes: float64(10)
memory usage: 528.0+ bytes


### input為n維

In [12]:
d = int(input('輸入的維度：'))
x_train = []
y_train = []
x_test = []
y_test = []

for a in range(2):
    x_test.append([])
    y_test.append([])

for b in range(8-d):
    x_train.append([])
    y_train.append([])
    
for i in range(2):
    x_test[i] = (df1.iloc[:, -2-d+i:-2+i].values)
    y_test[i] = (df1.iloc[:, -2+i].values)

for j in range(8-d):
    x_train[j] = (df1.iloc[:, j:d+j].values)
    y_train[j] = (df1.iloc[:, d+j].values)

輸入的維度：4


In [13]:
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)

In [14]:
x_train

array([[[ 96578.611019,  98880.514918, 101597.893147, 145899.00905 ],
        [148192.887258, 155531.416179, 162280.64627 , 173139.571548],
        [ 45593.320794,  48076.080794,  48577.653444,  57174.898426],
        [ 75788.78    ,  74185.      ,  77484.42    ,  96887.312546],
        [ 58714.48    ,  59532.477   ,  64737.22    ,  77578.825927],
        [102063.12    , 117931.345   , 115951.8     , 126711.53522 ]],

       [[ 98880.514918, 101597.893147, 145899.00905 , 149866.518605],
        [155531.416179, 162280.64627 , 173139.571548, 176075.234609],
        [ 48076.080794,  48577.653444,  57174.898426,  58093.627307],
        [ 74185.      ,  77484.42    ,  96887.312546,  99883.362462],
        [ 59532.477   ,  64737.22    ,  77578.825927,  82584.343311],
        [117931.345   , 115951.8     , 126711.53522 , 124889.951539]],

       [[101597.893147, 145899.00905 , 149866.518605, 146754.099649],
        [162280.64627 , 173139.571548, 176075.234609, 169580.238024],
        [ 48577.

In [15]:
x_train.shape

(4, 6, 4)

In [16]:
y_train

array([[149866.518605, 176075.234609,  58093.627307,  99883.362462,
         82584.343311, 124889.951539],
       [146754.099649, 169580.238024,  57736.471325, 109538.016083,
         77916.851738, 122071.850246],
       [154473.463926, 167504.327527,  62760.      , 104869.032822,
         73521.376929, 126265.671271],
       [151660.814378, 154187.639168,  84977.820413, 113177.438775,
         69498.060327, 119933.785777]])

In [17]:
y_train.shape

(4, 6)

In [18]:
x_test

array([[[149866.518605, 146754.099649, 154473.463926, 151660.814378],
        [176075.234609, 169580.238024, 167504.327527, 154187.639168],
        [ 58093.627307,  57736.471325,  62760.      ,  84977.820413],
        [ 99883.362462, 109538.016083, 104869.032822, 113177.438775],
        [ 82584.343311,  77916.851738,  73521.376929,  69498.060327],
        [124889.951539, 122071.850246, 126265.671271, 119933.785777]],

       [[146754.099649, 154473.463926, 151660.814378, 148828.44    ],
        [169580.238024, 167504.327527, 154187.639168, 162256.23    ],
        [ 57736.471325,  62760.      ,  84977.820413,  95094.42    ],
        [109538.016083, 104869.032822, 113177.438775, 123807.59    ],
        [ 77916.851738,  73521.376929,  69498.060327,  74696.14    ],
        [122071.850246, 126265.671271, 119933.785777, 121757.81    ]]])

In [19]:
y_test

array([[148828.44    , 162256.23    ,  95094.42    , 123807.59    ,
         74696.14    , 121757.81    ],
       [148828.437264, 162256.234058,  95094.418061, 123807.590957,
         74696.140442, 121758.      ]])

In [20]:
x_train = x_train.reshape(-1, d)
y_train = y_train.ravel()
x_test = x_test.reshape(-1, d)
y_test = y_test.ravel()

In [21]:
x_train

array([[ 96578.611019,  98880.514918, 101597.893147, 145899.00905 ],
       [148192.887258, 155531.416179, 162280.64627 , 173139.571548],
       [ 45593.320794,  48076.080794,  48577.653444,  57174.898426],
       [ 75788.78    ,  74185.      ,  77484.42    ,  96887.312546],
       [ 58714.48    ,  59532.477   ,  64737.22    ,  77578.825927],
       [102063.12    , 117931.345   , 115951.8     , 126711.53522 ],
       [ 98880.514918, 101597.893147, 145899.00905 , 149866.518605],
       [155531.416179, 162280.64627 , 173139.571548, 176075.234609],
       [ 48076.080794,  48577.653444,  57174.898426,  58093.627307],
       [ 74185.      ,  77484.42    ,  96887.312546,  99883.362462],
       [ 59532.477   ,  64737.22    ,  77578.825927,  82584.343311],
       [117931.345   , 115951.8     , 126711.53522 , 124889.951539],
       [101597.893147, 145899.00905 , 149866.518605, 146754.099649],
       [162280.64627 , 173139.571548, 176075.234609, 169580.238024],
       [ 48577.653444,  57174.8984

In [22]:
y_train

array([149866.518605, 176075.234609,  58093.627307,  99883.362462,
        82584.343311, 124889.951539, 146754.099649, 169580.238024,
        57736.471325, 109538.016083,  77916.851738, 122071.850246,
       154473.463926, 167504.327527,  62760.      , 104869.032822,
        73521.376929, 126265.671271, 151660.814378, 154187.639168,
        84977.820413, 113177.438775,  69498.060327, 119933.785777])

In [23]:
from xgboost import XGBRegressor
xgbr = XGBRegressor(n_estimators=100 , max_depth=3 , learning_rate=0.1, subsample=1, colsample_bynode=0.8, reg_lambda=1e-05)
xgbr.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.8, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1e-05, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [24]:
xgbr.predict(x_test)

array([157509.   , 154434.95 ,  82555.195, 113996.46 ,  73134.664,
       120571.78 , 153957.9  , 154434.95 ,  99918.836, 122858.45 ,
        76638.625, 123640.74 ], dtype=float32)

In [25]:
y_test

array([148828.44    , 162256.23    ,  95094.42    , 123807.59    ,
        74696.14    , 121757.81    , 148828.437264, 162256.234058,
        95094.418061, 123807.590957,  74696.140442, 121758.      ])

In [26]:
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    print('MAPE為', MAPE)

MAPE為 0.04639580002416881
MAPE為 0.04820325731835118
MAPE為 0.0912968534976665
MAPE為 0.04345560271047763
MAPE為 0.023454762749492264
MAPE為 0.01260193493761408


In [27]:
number = 0 
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    number += MAPE
number /= 6
print('平均MAPE為', number)

平均MAPE為 0.044234701872961746


In [28]:
number = 0
for i in range(len(xgbr.predict(x_test) - y_test)):
    number += ((xgbr.predict(x_test) - y_test)[i])**2
    
number /= len(xgbr.predict(x_test) - y_test)
print('平均MSE為', number)

平均MSE為 42736458.06650014


```
輸入為1D的平均MAPE為0.04341205887484145
         平均MSE為 46937868.20342507
輸入為2D的平均MAPE為0.06350798404674672
         平均MSE為 67510921.0132922
輸入為3D的平均MAPE為0.057164359008339834
         平均MSE為 66729070.90116366
輸入為4D的平均MAPE為0.044234701872961746
         平均MSE為 42736458.06650014
輸入為5D的平均MAPE為0.11376583461173885
         平均MSE為 208985558.635559
```

## 選擇4D！！！

In [29]:
df1

98             99            100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107  
million                                    
New Taipei City  148828.44  148828.437264  
Taipei City      162256.23  162256.234058  
Taoyuan City      95094.42   95094.418061  
Taichung City    123807.59  123807.590957  
Tainan City       74696.14   74696.140442  
Kaohsiung City   121757.81  121758.000000

In [30]:
df2 = df1.copy()
df2

98             99            100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107  
million                                    
New Taipei City  148828.44  148828.437264  
Taipei City      162256.23  162256.234058  
Taoyuan City      95094.42   95094.418061  
Taichung City    123807.59  123807.590957  
Tainan City       74696.14   74696.140442  
Kaohsiung City   121757.81  121758.000000

In [31]:
df2.iloc[:, -d:].values

array([[154473.463926, 151660.814378, 148828.44    , 148828.437264],
       [167504.327527, 154187.639168, 162256.23    , 162256.234058],
       [ 62760.      ,  84977.820413,  95094.42    ,  95094.418061],
       [104869.032822, 113177.438775, 123807.59    , 123807.590957],
       [ 73521.376929,  69498.060327,  74696.14    ,  74696.140442],
       [126265.671271, 119933.785777, 121757.81    , 121758.      ]])

In [32]:
xgbr.predict(df2.iloc[:, -d:].values)

array([155891.02, 155891.02, 107049.77, 124101.68,  78680.77, 120162.48],
      dtype=float32)

In [33]:
df2['108'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98             99            100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107            108  
million                                                   
New Taipei City  148828.44  148828.437264  155891.015625  
Taipei City      162256.23  162256.234058  155891.015625  
Taoyuan City      95094.42   95094.418061  107049.773438  
Taichung City    123807.59  123807.590957  124101.679688  
Tainan City       74696.14   74696.140442   78680.773438  
Kaohsiung City   121757.81  121758.000000  120162.476562

In [34]:
df2['109'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98             99            100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107            108            109  
million                                                                  
New Taipei City  148828.44  148828.437264  155891.015625  157509.000000  
Taipei City      162256.23  162256.234058  155891.015625  155525.515625  
Taoyuan City      95094.42   95094.418061  107049.773438  103615.382812  
Taichung City    123807.59  123807.590957  124101.679688  124077.179688  
Tainan City       74696.14   74696.140442   78680.773438   78773.367188  
Kaohsiung City   121757.81  121758.000000  120162.476562  121497.015625

In [35]:
df2['110'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98             99            100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107            108            109  \
million                                                                   
New Taipei City  148828.44  148828.437264  155891.015625  157509.000000   
Taipei City      162256.23  162256.234058  155891.015625  155525.515625   
Taoyuan City      95094.42   95094.418061  107049.773438  103615.382812   
Taichung City    123807.59  123807.590957  124101.679688  124077.179688   
Tainan City       74696.14   74696.140442   78680.773438   78773.367188   
Kaohsiung City   121757.81  121758.000000  120162.476562  121497.015625   

                           110  
million                         
New Taipei City  157509.000000  
Taipei City      155525.515625  
Taoyuan City     114603.960938  
Taichung City    120571.781250  
Tainan City       75374.375000  
Kaohsiung City   121497.015625

In [36]:
df2['111'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98             99            100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107            108            109  \
million                                                                   
New Taipei City  148828.44  148828.437264  155891.015625  157509.000000   
Taipei City      162256.23  162256.234058  155891.015625  155525.515625   
Taoyuan City      95094.42   95094.418061  107049.773438  103615.382812   
Taichung City    123807.59  123807.590957  124101.679688  124077.179688   
Tainan City       74696.14   74696.140442   78680.773438   78773.367188   
Kaohsiung City   121757.81  121758.000000  120162.476562  121497.015625   

                           110            111  
million                                        
New Taipei City  157509.000000  157509.000000  
Taipei City      155525.515625  155891.015625  
Taoyuan City     114603.960938  115679.804688  
Taichung City    120571.781250  120571.781250  
Tainan City       75374.375000   71907.742188  
Kaohsiung City   121497.015625  121521.515625

In [37]:
df2['112'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98             99            100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107            108            109  \
million                                                                   
New Taipei City  148828.44  148828.437264  155891.015625  157509.000000   
Taipei City      162256.23  162256.234058  155891.015625  155525.515625   
Taoyuan City      95094.42   95094.418061  107049.773438  103615.382812   
Taichung City    123807.59  123807.590957  124101.679688  124077.179688   
Tainan City       74696.14   74696.140442   78680.773438   78773.367188   
Kaohsiung City   121757.81  121758.000000  120162.476562  121497.015625   

                           110            111            112  
million                                                       
New Taipei City  157509.000000  157509.000000  155891.015625  
Taipei City      155525.515625  155891.015625  155891.015625  
Taoyuan City     114603.960938  115679.804688  113224.921875  
Taichung City    120571.781250  120571.781250  120137.976562  
Tainan City       75374.375000   71907.742188   73134.664062  
Kaohsiung City   121497.015625  121521.515625  121497.015625

In [38]:
df2['113'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98             99            100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107            108            109  \
million                                                                   
New Taipei City  148828.44  148828.437264  155891.015625  157509.000000   
Taipei City      162256.23  162256.234058  155891.015625  155525.515625   
Taoyuan City      95094.42   95094.418061  107049.773438  103615.382812   
Taichung City    123807.59  123807.590957  124101.679688  124077.179688   
Tainan City       74696.14   74696.140442   78680.773438   78773.367188   
Kaohsiung City   121757.81  121758.000000  120162.476562  121497.015625   

                           110            111            112            113  
million                                                                      
New Taipei City  157509.000000  157509.000000  155891.015625  155891.015625  
Taipei City      155525.515625  155891.015625  155891.015625  155891.015625  
Taoyuan City     114603.960938  115679.804688  113224.921875  113996.460938  
Taichung City    120571.781250  120571.781250  120137.976562  120162.476562  
Tainan City       75374.375000   71907.742188   73134.664062   76638.625000  
Kaohsiung City   121497.015625  121521.515625  121497.015625  121497.015625

In [39]:
df2['114'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98             99            100            101  \
million                                                                       
New Taipei City   96578.611019   98880.514918  101597.893147  145899.009050   
Taipei City      148192.887258  155531.416179  162280.646270  173139.571548   
Taoyuan City      45593.320794   48076.080794   48577.653444   57174.898426   
Taichung City     75788.780000   74185.000000   77484.420000   96887.312546   
Tainan City       58714.480000   59532.477000   64737.220000   77578.825927   
Kaohsiung City   102063.120000  117931.345000  115951.800000  126711.535220   

                           102            103            104            105  \
million                                                                       
New Taipei City  149866.518605  146754.099649  154473.463926  151660.814378   
Taipei City      176075.234609  169580.238024  167504.327527  154187.639168   
Taoyuan City      58093.627307   57736.471325   62760.000000   84977.820413   
Taichung City     99883.362462  109538.016083  104869.032822  113177.438775   
Tainan City       82584.343311   77916.851738   73521.376929   69498.060327   
Kaohsiung City   124889.951539  122071.850246  126265.671271  119933.785777   

                       106            107            108            109  \
million                                                                   
New Taipei City  148828.44  148828.437264  155891.015625  157509.000000   
Taipei City      162256.23  162256.234058  155891.015625  155525.515625   
Taoyuan City      95094.42   95094.418061  107049.773438  103615.382812   
Taichung City    123807.59  123807.590957  124101.679688  124077.179688   
Tainan City       74696.14   74696.140442   78680.773438   78773.367188   
Kaohsiung City   121757.81  121758.000000  120162.476562  121497.015625   

                           110            111            112            113  \
million                                                                       
New Taipei City  157509.000000  157509.000000  155891.015625  155891.015625   
Taipei City      155525.515625  155891.015625  155891.015625  155891.015625   
Taoyuan City     114603.960938  115679.804688  113224.921875  113996.460938   
Taichung City    120571.781250  120571.781250  120137.976562  120162.476562   
Tainan City       75374.375000   71907.742188   73134.664062   76638.625000   
Kaohsiung City   121497.015625  121521.515625  121497.015625  121497.015625   

                           114  
million                         
New Taipei City  155891.015625  
Taipei City      155891.015625  
Taoyuan City     113996.460938  
Taichung City    121521.515625  
Tainan City       78504.304688  
Kaohsiung City   121497.015625

In [40]:
outputpath='C:/Users/Steven/Desktop/新增資料夾/city_annual_update.xlsx'
df2.to_excel(outputpath,index=True,header=True)