In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottle

In [3]:
df1 = pd.read_excel('death_df.xlsx')
df1

million      98      99     100     101     102     103     104  \
0  New Taipei City   17882   17959   18404   19774   20280   20746   21935   
1      Taipei City   15606   15260   15398   15988   16579   16379   17177   
2     Taoyuan City    9677    9790   10183   10878   10977   10972   11854   
3    Taichung City   13826   13805   14340   14915   15017   15138   15968   
4      Tainan City   13040   12990   13206   13941   13871   14021   14390   
5   Kaohsiung City   17517   18189   18001   18845   18945   19277   20282   
6           Taiwan  143582  145772  152915  154251  155908  163929  163858   

      105     106     107  108  
0   22175   23256   23525  NaN  
1   17106   17982   17467  NaN  
2   11600   12637   12620  NaN  
3   16070   16921   16904  NaN  
4   20508   15234   14996  NaN  
5   12779   21365   21368  NaN  
6  172405  171242  172784  NaN

In [4]:
df1.index = df1['million']

In [5]:
df1.columns

Index(['million', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [6]:
df1

million      98      99     100     101     102  \
million                                                                    
New Taipei City  New Taipei City   17882   17959   18404   19774   20280   
Taipei City          Taipei City   15606   15260   15398   15988   16579   
Taoyuan City        Taoyuan City    9677    9790   10183   10878   10977   
Taichung City      Taichung City   13826   13805   14340   14915   15017   
Tainan City          Tainan City   13040   12990   13206   13941   13871   
Kaohsiung City    Kaohsiung City   17517   18189   18001   18845   18945   
Taiwan                    Taiwan  143582  145772  152915  154251  155908   

                    103     104     105     106     107  108  
million                                                       
New Taipei City   20746   21935   22175   23256   23525  NaN  
Taipei City       16379   17177   17106   17982   17467  NaN  
Taoyuan City      10972   11854   11600   12637   12620  NaN  
Taichung City     15138   15968   16070   16921   16904  NaN  
Tainan City       14021   14390   20508   15234   14996  NaN  
Kaohsiung City    19277   20282   12779   21365   21368  NaN  
Taiwan           163929  163858  172405  171242  172784  NaN

In [7]:
df1 = df1.iloc[:-1, 1:-1]
df1

98     99     100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107  
million                        
New Taipei City  23256  23525  
Taipei City      17982  17467  
Taoyuan City     12637  12620  
Taichung City    16921  16904  
Tainan City      15234  14996  
Kaohsiung City   21365  21368

In [8]:
col = []
for i in df1.columns:
    col.append(str(i))
col

['98', '99', '100', '101', '102', '103', '104', '105', '106', '107']

In [9]:
df1.columns = col
df1

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107  
million                        
New Taipei City  23256  23525  
Taipei City      17982  17467  
Taoyuan City     12637  12620  
Taichung City    16921  16904  
Tainan City      15234  14996  
Kaohsiung City   21365  21368

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, New Taipei City to Kaohsiung City
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   98      6 non-null      int64
 1   99      6 non-null      int64
 2   100     6 non-null      int64
 3   101     6 non-null      int64
 4   102     6 non-null      int64
 5   103     6 non-null      int64
 6   104     6 non-null      int64
 7   105     6 non-null      int64
 8   106     6 non-null      int64
 9   107     6 non-null      int64
dtypes: int64(10)
memory usage: 528.0+ bytes


### input為n維

In [12]:
d = int(input('輸入的維度：'))
x_train = []
y_train = []
x_test = []
y_test = []

for a in range(2):
    x_test.append([])
    y_test.append([])

for b in range(8-d):
    x_train.append([])
    y_train.append([])
    
for i in range(2):
    x_test[i] = (df1.iloc[:, -2-d+i:-2+i].values)
    y_test[i] = (df1.iloc[:, -2+i].values)

for j in range(8-d):
    x_train[j] = (df1.iloc[:, j:d+j].values)
    y_train[j] = (df1.iloc[:, d+j].values)

輸入的維度：5


In [13]:
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)

In [14]:
x_train

array([[[17882, 17959, 18404, 19774, 20280],
        [15606, 15260, 15398, 15988, 16579],
        [ 9677,  9790, 10183, 10878, 10977],
        [13826, 13805, 14340, 14915, 15017],
        [13040, 12990, 13206, 13941, 13871],
        [17517, 18189, 18001, 18845, 18945]],

       [[17959, 18404, 19774, 20280, 20746],
        [15260, 15398, 15988, 16579, 16379],
        [ 9790, 10183, 10878, 10977, 10972],
        [13805, 14340, 14915, 15017, 15138],
        [12990, 13206, 13941, 13871, 14021],
        [18189, 18001, 18845, 18945, 19277]],

       [[18404, 19774, 20280, 20746, 21935],
        [15398, 15988, 16579, 16379, 17177],
        [10183, 10878, 10977, 10972, 11854],
        [14340, 14915, 15017, 15138, 15968],
        [13206, 13941, 13871, 14021, 14390],
        [18001, 18845, 18945, 19277, 20282]]], dtype=int64)

In [15]:
x_train.shape

(3, 6, 5)

In [16]:
y_train

array([[20746, 16379, 10972, 15138, 14021, 19277],
       [21935, 17177, 11854, 15968, 14390, 20282],
       [22175, 17106, 11600, 16070, 20508, 12779]], dtype=int64)

In [17]:
y_train.shape

(3, 6)

In [18]:
x_test

array([[[19774, 20280, 20746, 21935, 22175],
        [15988, 16579, 16379, 17177, 17106],
        [10878, 10977, 10972, 11854, 11600],
        [14915, 15017, 15138, 15968, 16070],
        [13941, 13871, 14021, 14390, 20508],
        [18845, 18945, 19277, 20282, 12779]],

       [[20280, 20746, 21935, 22175, 23256],
        [16579, 16379, 17177, 17106, 17982],
        [10977, 10972, 11854, 11600, 12637],
        [15017, 15138, 15968, 16070, 16921],
        [13871, 14021, 14390, 20508, 15234],
        [18945, 19277, 20282, 12779, 21365]]], dtype=int64)

In [19]:
y_test

array([[23256, 17982, 12637, 16921, 15234, 21365],
       [23525, 17467, 12620, 16904, 14996, 21368]], dtype=int64)

In [20]:
x_train = x_train.reshape(-1, d)
y_train = y_train.ravel()
x_test = x_test.reshape(-1, d)
y_test = y_test.ravel()

In [21]:
x_train

array([[17882, 17959, 18404, 19774, 20280],
       [15606, 15260, 15398, 15988, 16579],
       [ 9677,  9790, 10183, 10878, 10977],
       [13826, 13805, 14340, 14915, 15017],
       [13040, 12990, 13206, 13941, 13871],
       [17517, 18189, 18001, 18845, 18945],
       [17959, 18404, 19774, 20280, 20746],
       [15260, 15398, 15988, 16579, 16379],
       [ 9790, 10183, 10878, 10977, 10972],
       [13805, 14340, 14915, 15017, 15138],
       [12990, 13206, 13941, 13871, 14021],
       [18189, 18001, 18845, 18945, 19277],
       [18404, 19774, 20280, 20746, 21935],
       [15398, 15988, 16579, 16379, 17177],
       [10183, 10878, 10977, 10972, 11854],
       [14340, 14915, 15017, 15138, 15968],
       [13206, 13941, 13871, 14021, 14390],
       [18001, 18845, 18945, 19277, 20282]], dtype=int64)

In [22]:
y_train

array([20746, 16379, 10972, 15138, 14021, 19277, 21935, 17177, 11854,
       15968, 14390, 20282, 22175, 17106, 11600, 16070, 20508, 12779],
      dtype=int64)

In [23]:
from xgboost import XGBRegressor
xgbr = XGBRegressor(n_estimators=100 , max_depth=3 , learning_rate=0.1, subsample=1, colsample_bynode=0.8, reg_lambda=1e-05)
xgbr.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.8, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1e-05, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [24]:
xgbr.predict(x_test)

array([22174.396, 17186.469, 11853.863, 16323.321, 15560.958, 20699.934,
       22174.396, 18238.275, 11853.863, 16406.932, 18923.076, 16776.596],
      dtype=float32)

In [25]:
y_test

array([23256, 17982, 12637, 16921, 15234, 21365, 23525, 17467, 12620,
       16904, 14996, 21368], dtype=int64)

In [26]:
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    print('MAPE為', MAPE)

MAPE為 0.051959996578719914
MAPE為 0.0441982831574422
MAPE為 0.06133993336508491
MAPE為 0.0323635412087734
MAPE為 0.14166864935699627
MAPE為 0.12300084447463557


In [27]:
number = 0 
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    number += MAPE
number /= 6
print('平均MAPE為', number)

平均MAPE為 0.0757552080236087


In [28]:
number = 0
for i in range(len(xgbr.predict(x_test) - y_test)):
    number += ((xgbr.predict(x_test) - y_test)[i])**2
    
number /= len(xgbr.predict(x_test) - y_test)
print('平均MSE為', number)

平均MSE為 3589869.387289842


```
輸入為1D的平均MAPE為0.08254572659034058
         平均MSE為 6813854.726236264
輸入為2D的平均MAPE為0.07977910050381481
         平均MSE為 3968261.6737377644
輸入為3D的平均MAPE為0.07777130367454381
         平均MSE為 4205531.2481200695
輸入為4D的平均MAPE為0.08363779374502793
         平均MSE為 4879564.360830386
輸入為5D的平均MAPE為0.0757552080236087
         平均MSE為 3589869.387289842
```

## 選擇5D！！！

In [29]:
df1

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107  
million                        
New Taipei City  23256  23525  
Taipei City      17982  17467  
Taoyuan City     12637  12620  
Taichung City    16921  16904  
Tainan City      15234  14996  
Kaohsiung City   21365  21368

In [30]:
df2 = df1.copy()
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107  
million                        
New Taipei City  23256  23525  
Taipei City      17982  17467  
Taoyuan City     12637  12620  
Taichung City    16921  16904  
Tainan City      15234  14996  
Kaohsiung City   21365  21368

In [31]:
df2.iloc[:, -d:].values

array([[20746, 21935, 22175, 23256, 23525],
       [16379, 17177, 17106, 17982, 17467],
       [10972, 11854, 11600, 12637, 12620],
       [15138, 15968, 16070, 16921, 16904],
       [14021, 14390, 20508, 15234, 14996],
       [19277, 20282, 12779, 21365, 21368]], dtype=int64)

In [32]:
xgbr.predict(df2.iloc[:, -d:].values)

array([22174.396, 17844.375, 11853.863, 17176.254, 15333.377, 22204.02 ],
      dtype=float32)

In [33]:
df2['108'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107           108  
million                                      
New Taipei City  23256  23525  22174.396484  
Taipei City      17982  17467  17844.375000  
Taoyuan City     12637  12620  11853.863281  
Taichung City    16921  16904  17176.253906  
Tainan City      15234  14996  15333.376953  
Kaohsiung City   21365  21368  22204.019531

In [34]:
df2['109'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107           108           109  
million                                                    
New Taipei City  23256  23525  22174.396484  22174.396484  
Taipei City      17982  17467  17844.375000  18896.179688  
Taoyuan City     12637  12620  11853.863281  13654.607422  
Taichung City    16921  16904  17176.253906  17186.468750  
Tainan City      15234  14996  15333.376953  15045.445312  
Kaohsiung City   21365  21368  22204.019531  16581.410156

In [35]:
df2['110'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107           108           109           110  
million                                                                  
New Taipei City  23256  23525  22174.396484  22174.396484  22174.396484  
Taipei City      17982  17467  17844.375000  18896.179688  19275.449219  
Taoyuan City     12637  12620  11853.863281  13654.607422  13963.094727  
Taichung City    16921  16904  17176.253906  17186.468750  17186.898438  
Tainan City      15234  14996  15333.376953  15045.445312  17890.626953  
Kaohsiung City   21365  21368  22204.019531  16581.410156  17549.916016

In [36]:
df2['111'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107           108           109           110  \
million                                                                   
New Taipei City  23256  23525  22174.396484  22174.396484  22174.396484   
Taipei City      17982  17467  17844.375000  18896.179688  19275.449219   
Taoyuan City     12637  12620  11853.863281  13654.607422  13963.094727   
Taichung City    16921  16904  17176.253906  17186.468750  17186.898438   
Tainan City      15234  14996  15333.376953  15045.445312  17890.626953   
Kaohsiung City   21365  21368  22204.019531  16581.410156  17549.916016   

                          111  
million                        
New Taipei City  22174.396484  
Taipei City      18403.794922  
Taoyuan City     14086.073242  
Taichung City    18238.705078  
Tainan City      16323.321289  
Kaohsiung City   17641.443359

In [37]:
df2['112'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107           108           109           110  \
million                                                                   
New Taipei City  23256  23525  22174.396484  22174.396484  22174.396484   
Taipei City      17982  17467  17844.375000  18896.179688  19275.449219   
Taoyuan City     12637  12620  11853.863281  13654.607422  13963.094727   
Taichung City    16921  16904  17176.253906  17186.468750  17186.898438   
Tainan City      15234  14996  15333.376953  15045.445312  17890.626953   
Kaohsiung City   21365  21368  22204.019531  16581.410156  17549.916016   

                          111           112  
million                                      
New Taipei City  22174.396484  22174.396484  
Taipei City      18403.794922  17533.853516  
Taoyuan City     14086.073242  13661.483398  
Taichung City    18238.705078  18896.179688  
Tainan City      16323.321289  17137.207031  
Kaohsiung City   17641.443359  18394.771484

In [38]:
df2['113'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107           108           109           110  \
million                                                                   
New Taipei City  23256  23525  22174.396484  22174.396484  22174.396484   
Taipei City      17982  17467  17844.375000  18896.179688  19275.449219   
Taoyuan City     12637  12620  11853.863281  13654.607422  13963.094727   
Taichung City    16921  16904  17176.253906  17186.468750  17186.898438   
Tainan City      15234  14996  15333.376953  15045.445312  17890.626953   
Kaohsiung City   21365  21368  22204.019531  16581.410156  17549.916016   

                          111           112           113  
million                                                    
New Taipei City  22174.396484  22174.396484  22174.396484  
Taipei City      18403.794922  17533.853516  13390.725586  
Taoyuan City     14086.073242  13661.483398  14482.796875  
Taichung City    18238.705078  18896.179688  18896.179688  
Tainan City      16323.321289  17137.207031  16362.367188  
Kaohsiung City   17641.443359  18394.771484  19113.654297

In [39]:
df2['114'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101    102    103    104    105  \
million                                                                   
New Taipei City  17882  17959  18404  19774  20280  20746  21935  22175   
Taipei City      15606  15260  15398  15988  16579  16379  17177  17106   
Taoyuan City      9677   9790  10183  10878  10977  10972  11854  11600   
Taichung City    13826  13805  14340  14915  15017  15138  15968  16070   
Tainan City      13040  12990  13206  13941  13871  14021  14390  20508   
Kaohsiung City   17517  18189  18001  18845  18945  19277  20282  12779   

                   106    107           108           109           110  \
million                                                                   
New Taipei City  23256  23525  22174.396484  22174.396484  22174.396484   
Taipei City      17982  17467  17844.375000  18896.179688  19275.449219   
Taoyuan City     12637  12620  11853.863281  13654.607422  13963.094727   
Taichung City    16921  16904  17176.253906  17186.468750  17186.898438   
Tainan City      15234  14996  15333.376953  15045.445312  17890.626953   
Kaohsiung City   21365  21368  22204.019531  16581.410156  17549.916016   

                          111           112           113           114  
million                                                                  
New Taipei City  22174.396484  22174.396484  22174.396484  22174.396484  
Taipei City      18403.794922  17533.853516  13390.725586  17636.658203  
Taoyuan City     14086.073242  13661.483398  14482.796875  17692.960938  
Taichung City    18238.705078  18896.179688  18896.179688  18896.179688  
Tainan City      16323.321289  17137.207031  16362.367188  17833.730469  
Kaohsiung City   17641.443359  18394.771484  19113.654297  18896.179688

In [40]:
outputpath='C:/Users/Steven/Desktop/新增資料夾/death_update.xlsx'
df2.to_excel(outputpath,index=True,header=True)