In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottle

In [3]:
df1 = pd.read_excel('immigration_df.xlsx')
df1

million     98     99    100    101    102    103   104    105  \
0  New Taipei City  21342  25789  14501   4535   2287    455 -4780 -10312   
1      Taipei City -11431 -19638   8212  23052   9339   2959  3952  -9386   
2     Taoyuan City  14215  11371  17623   4082   7967   8077  8799  36668   
3    Taichung City   7457   2893   7461   6863   7192   7351  7948  14367   
4      Tainan City   1211   1195    -18   2899    804    796    40  -2035   
5   Kaohsiung City   -479  -1055   1913  -1579  -1829  -1131 -3123    102   
6           Taiwan  35013  21237  19077  15680  14490  13782  6798  11707   

     106    107     108  
0  -2511   -605  4030.0  
1 -19116 -20022     NaN  
2  30834  29518     NaN  
3  14060  12397     NaN  
4   1028   1712     NaN  
5     61  -1351     NaN  
6   8809   6770     NaN

In [4]:
df1.index = df1['million']

In [5]:
df1.columns

Index(['million', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [6]:
df1

million     98     99    100    101    102    103  \
million                                                                      
New Taipei City  New Taipei City  21342  25789  14501   4535   2287    455   
Taipei City          Taipei City -11431 -19638   8212  23052   9339   2959   
Taoyuan City        Taoyuan City  14215  11371  17623   4082   7967   8077   
Taichung City      Taichung City   7457   2893   7461   6863   7192   7351   
Tainan City          Tainan City   1211   1195    -18   2899    804    796   
Kaohsiung City    Kaohsiung City   -479  -1055   1913  -1579  -1829  -1131   
Taiwan                    Taiwan  35013  21237  19077  15680  14490  13782   

                  104    105    106    107     108  
million                                             
New Taipei City -4780 -10312  -2511   -605  4030.0  
Taipei City      3952  -9386 -19116 -20022     NaN  
Taoyuan City     8799  36668  30834  29518     NaN  
Taichung City    7948  14367  14060  12397     NaN  
Tainan City        40  -2035   1028   1712     NaN  
Kaohsiung City  -3123    102     61  -1351     NaN  
Taiwan           6798  11707   8809   6770     NaN

In [7]:
df1 = df1.iloc[:-1, 1:-1]
df1

98     99     100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107  
million                 
New Taipei City   -605  
Taipei City     -20022  
Taoyuan City     29518  
Taichung City    12397  
Tainan City       1712  
Kaohsiung City   -1351

In [8]:
col = []
for i in df1.columns:
    col.append(str(i))
col

['98', '99', '100', '101', '102', '103', '104', '105', '106', '107']

In [9]:
df1.columns = col
df1

98     99    100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107  
million                 
New Taipei City   -605  
Taipei City     -20022  
Taoyuan City     29518  
Taichung City    12397  
Tainan City       1712  
Kaohsiung City   -1351

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, New Taipei City to Kaohsiung City
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   98      6 non-null      int64
 1   99      6 non-null      int64
 2   100     6 non-null      int64
 3   101     6 non-null      int64
 4   102     6 non-null      int64
 5   103     6 non-null      int64
 6   104     6 non-null      int64
 7   105     6 non-null      int64
 8   106     6 non-null      int64
 9   107     6 non-null      int64
dtypes: int64(10)
memory usage: 528.0+ bytes


### input為n維

In [12]:
d = int(input('輸入的維度：'))
x_train = []
y_train = []
x_test = []
y_test = []

for a in range(2):
    x_test.append([])
    y_test.append([])

for b in range(8-d):
    x_train.append([])
    y_train.append([])
    
for i in range(2):
    x_test[i] = (df1.iloc[:, -2-d+i:-2+i].values)
    y_test[i] = (df1.iloc[:, -2+i].values)

for j in range(8-d):
    x_train[j] = (df1.iloc[:, j:d+j].values)
    y_train[j] = (df1.iloc[:, d+j].values)

輸入的維度：4


In [13]:
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)

In [14]:
x_train

array([[[ 21342,  25789,  14501,   4535],
        [-11431, -19638,   8212,  23052],
        [ 14215,  11371,  17623,   4082],
        [  7457,   2893,   7461,   6863],
        [  1211,   1195,    -18,   2899],
        [  -479,  -1055,   1913,  -1579]],

       [[ 25789,  14501,   4535,   2287],
        [-19638,   8212,  23052,   9339],
        [ 11371,  17623,   4082,   7967],
        [  2893,   7461,   6863,   7192],
        [  1195,    -18,   2899,    804],
        [ -1055,   1913,  -1579,  -1829]],

       [[ 14501,   4535,   2287,    455],
        [  8212,  23052,   9339,   2959],
        [ 17623,   4082,   7967,   8077],
        [  7461,   6863,   7192,   7351],
        [   -18,   2899,    804,    796],
        [  1913,  -1579,  -1829,  -1131]],

       [[  4535,   2287,    455,  -4780],
        [ 23052,   9339,   2959,   3952],
        [  4082,   7967,   8077,   8799],
        [  6863,   7192,   7351,   7948],
        [  2899,    804,    796,     40],
        [ -1579,  -1829,  -1

In [15]:
x_train.shape

(4, 6, 4)

In [16]:
y_train

array([[  2287,   9339,   7967,   7192,    804,  -1829],
       [   455,   2959,   8077,   7351,    796,  -1131],
       [ -4780,   3952,   8799,   7948,     40,  -3123],
       [-10312,  -9386,  36668,  14367,  -2035,    102]], dtype=int64)

In [17]:
y_train.shape

(4, 6)

In [18]:
x_test

array([[[  2287,    455,  -4780, -10312],
        [  9339,   2959,   3952,  -9386],
        [  7967,   8077,   8799,  36668],
        [  7192,   7351,   7948,  14367],
        [   804,    796,     40,  -2035],
        [ -1829,  -1131,  -3123,    102]],

       [[   455,  -4780, -10312,  -2511],
        [  2959,   3952,  -9386, -19116],
        [  8077,   8799,  36668,  30834],
        [  7351,   7948,  14367,  14060],
        [   796,     40,  -2035,   1028],
        [ -1131,  -3123,    102,     61]]], dtype=int64)

In [19]:
y_test

array([[ -2511, -19116,  30834,  14060,   1028,     61],
       [  -605, -20022,  29518,  12397,   1712,  -1351]], dtype=int64)

In [20]:
x_train = x_train.reshape(-1, d)
y_train = y_train.ravel()
x_test = x_test.reshape(-1, d)
y_test = y_test.ravel()

In [21]:
x_train

array([[ 21342,  25789,  14501,   4535],
       [-11431, -19638,   8212,  23052],
       [ 14215,  11371,  17623,   4082],
       [  7457,   2893,   7461,   6863],
       [  1211,   1195,    -18,   2899],
       [  -479,  -1055,   1913,  -1579],
       [ 25789,  14501,   4535,   2287],
       [-19638,   8212,  23052,   9339],
       [ 11371,  17623,   4082,   7967],
       [  2893,   7461,   6863,   7192],
       [  1195,    -18,   2899,    804],
       [ -1055,   1913,  -1579,  -1829],
       [ 14501,   4535,   2287,    455],
       [  8212,  23052,   9339,   2959],
       [ 17623,   4082,   7967,   8077],
       [  7461,   6863,   7192,   7351],
       [   -18,   2899,    804,    796],
       [  1913,  -1579,  -1829,  -1131],
       [  4535,   2287,    455,  -4780],
       [ 23052,   9339,   2959,   3952],
       [  4082,   7967,   8077,   8799],
       [  6863,   7192,   7351,   7948],
       [  2899,    804,    796,     40],
       [ -1579,  -1829,  -1131,  -3123]], dtype=int64)

In [22]:
y_train

array([  2287,   9339,   7967,   7192,    804,  -1829,    455,   2959,
         8077,   7351,    796,  -1131,  -4780,   3952,   8799,   7948,
           40,  -3123, -10312,  -9386,  36668,  14367,  -2035,    102],
      dtype=int64)

In [23]:
from xgboost import XGBRegressor
xgbr = XGBRegressor(n_estimators=100 , max_depth=3 , learning_rate=0.1, subsample=1, colsample_bynode=0.8, reg_lambda=1e-05)
xgbr.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.8, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1e-05, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [24]:
xgbr.predict(x_test)

array([-7570.4756, -4206.702 , 26693.953 , 19124.45  , -1291.166 ,
        -249.1439, -1371.541 , -7588.8203, 13824.03  , 25540.627 ,
         652.0807,  -628.942 ], dtype=float32)

In [25]:
y_test

array([ -2511, -19116,  30834,  14060,   1028,     61,   -605, -20022,
        29518,  12397,   1712,  -1351], dtype=int64)

In [26]:
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    print('MAPE為', MAPE)

MAPE為 1.6409672547325858
MAPE為 0.7004570350442437
MAPE為 0.3329717248069878
MAPE為 0.7102145345521385
MAPE為 1.437554908529655
MAPE為 2.8093940948809606


In [27]:
number = 0 
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    number += MAPE
number /= 6
print('平均MAPE為', number)

平均MAPE為 1.2719265920910952


In [28]:
number = 0
for i in range(len(xgbr.predict(x_test) - y_test)):
    number += ((xgbr.predict(x_test) - y_test)[i])**2
    
number /= len(xgbr.predict(x_test) - y_test)
print('平均MSE為', number)

平均MSE為 72668397.00898631


```
輸入為1D的平均MAPE為3.060568921047715
         平均MSE為 136892872.91622683
輸入為2D的平均MAPE為5.301683403118922
         平均MSE為 163420451.18258664
輸入為3D的平均MAPE為4.586300235788694
         平均MSE為 93191825.61048622
輸入為4D的平均MAPE為1.2719265920910952
         平均MSE為 72668397.00898631
輸入為5D的平均MAPE為2.8192658995896416
         平均MSE為 112885920.03243451
```

## 選擇4D！！！

In [29]:
df1

98     99    100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107  
million                 
New Taipei City   -605  
Taipei City     -20022  
Taoyuan City     29518  
Taichung City    12397  
Tainan City       1712  
Kaohsiung City   -1351

In [30]:
df2 = df1.copy()
df2

98     99    100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107  
million                 
New Taipei City   -605  
Taipei City     -20022  
Taoyuan City     29518  
Taichung City    12397  
Tainan City       1712  
Kaohsiung City   -1351

In [31]:
df2.iloc[:, -d:].values

array([[ -4780, -10312,  -2511,   -605],
       [  3952,  -9386, -19116, -20022],
       [  8799,  36668,  30834,  29518],
       [  7948,  14367,  14060,  12397],
       [    40,  -2035,   1028,   1712],
       [ -3123,    102,     61,  -1351]], dtype=int64)

In [32]:
xgbr.predict(df2.iloc[:, -d:].values)

array([  -36.179047, -9928.036   , 13821.163   , 13678.448   ,
         294.6476  ,  -168.99007 ], dtype=float32)

In [33]:
df2['108'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107           108  
million                               
New Taipei City   -605    -36.179047  
Taipei City     -20022  -9928.036133  
Taoyuan City     29518  13821.163086  
Taichung City    12397  13678.448242  
Tainan City       1712    294.647614  
Kaohsiung City   -1351   -168.990067

In [34]:
df2['109'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107           108           109  
million                                             
New Taipei City   -605    -36.179047    -87.174423  
Taipei City     -20022  -9928.036133  -4461.607910  
Taoyuan City     29518  13821.163086  12393.291992  
Taichung City    12397  13678.448242  13698.328125  
Tainan City       1712    294.647614   -147.490387  
Kaohsiung City   -1351   -168.990067   -581.301941

In [35]:
df2['110'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107           108           109           110  
million                                                           
New Taipei City   -605    -36.179047    -87.174423   -132.553101  
Taipei City     -20022  -9928.036133  -4461.607910  -4461.607910  
Taoyuan City     29518  13821.163086  12393.291992  12238.194336  
Taichung City    12397  13678.448242  13698.328125  13688.812500  
Tainan City       1712    294.647614   -147.490387   -186.221817  
Kaohsiung City   -1351   -168.990067   -581.301941  -1551.069336

In [36]:
df2['111'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107           108           109           110           111  
million                                                                         
New Taipei City   -605    -36.179047    -87.174423   -132.553101   -717.631470  
Taipei City     -20022  -9928.036133  -4461.607910  -4461.607910  -4461.607910  
Taoyuan City     29518  13821.163086  12393.291992  12238.194336  12263.336914  
Taichung City    12397  13678.448242  13698.328125  13688.812500  13686.093750  
Tainan City       1712    294.647614   -147.490387   -186.221817  -2008.781128  
Kaohsiung City   -1351   -168.990067   -581.301941  -1551.069336   -116.058777

In [37]:
df2['112'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107           108           109           110  \
million                                                            
New Taipei City   -605    -36.179047    -87.174423   -132.553101   
Taipei City     -20022  -9928.036133  -4461.607910  -4461.607910   
Taoyuan City     29518  13821.163086  12393.291992  12238.194336   
Taichung City    12397  13678.448242  13698.328125  13688.812500   
Tainan City       1712    294.647614   -147.490387   -186.221817   
Kaohsiung City   -1351   -168.990067   -581.301941  -1551.069336   

                          111           112  
million                                      
New Taipei City   -717.631470  -1579.457642  
Taipei City      -4461.607910  -4461.607910  
Taoyuan City     12263.336914  13688.812500  
Taichung City    13686.093750  13698.328125  
Tainan City      -2008.781128  -1585.031128  
Kaohsiung City    -116.058777   -603.825195

In [38]:
df2['113'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107           108           109           110  \
million                                                            
New Taipei City   -605    -36.179047    -87.174423   -132.553101   
Taipei City     -20022  -9928.036133  -4461.607910  -4461.607910   
Taoyuan City     29518  13821.163086  12393.291992  12238.194336   
Taichung City    12397  13678.448242  13698.328125  13688.812500   
Tainan City       1712    294.647614   -147.490387   -186.221817   
Kaohsiung City   -1351   -168.990067   -581.301941  -1551.069336   

                          111           112           113  
million                                                    
New Taipei City   -717.631470  -1579.457642  -1469.708008  
Taipei City      -4461.607910  -4461.607910  -4461.607910  
Taoyuan City     12263.336914  13688.812500  13676.578125  
Taichung City    13686.093750  13698.328125  13698.328125  
Tainan City      -2008.781128  -1585.031128  -1594.194092  
Kaohsiung City    -116.058777   -603.825195  -1687.398926

In [39]:
df2['114'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98     99    100    101   102   103   104    105    106  \
million                                                                       
New Taipei City  21342  25789  14501   4535  2287   455 -4780 -10312  -2511   
Taipei City     -11431 -19638   8212  23052  9339  2959  3952  -9386 -19116   
Taoyuan City     14215  11371  17623   4082  7967  8077  8799  36668  30834   
Taichung City     7457   2893   7461   6863  7192  7351  7948  14367  14060   
Tainan City       1211   1195    -18   2899   804   796    40  -2035   1028   
Kaohsiung City    -479  -1055   1913  -1579 -1829 -1131 -3123    102     61   

                   107           108           109           110  \
million                                                            
New Taipei City   -605    -36.179047    -87.174423   -132.553101   
Taipei City     -20022  -9928.036133  -4461.607910  -4461.607910   
Taoyuan City     29518  13821.163086  12393.291992  12238.194336   
Taichung City    12397  13678.448242  13698.328125  13688.812500   
Tainan City       1712    294.647614   -147.490387   -186.221817   
Kaohsiung City   -1351   -168.990067   -581.301941  -1551.069336   

                          111           112           113           114  
million                                                                  
New Taipei City   -717.631470  -1579.457642  -1469.708008  -1492.231323  
Taipei City      -4461.607910  -4461.607910  -4461.607910  -4461.607910  
Taoyuan City     12263.336914  13688.812500  13676.578125  13676.578125  
Taichung City    13686.093750  13698.328125  13698.328125  13698.328125  
Tainan City      -2008.781128  -1585.031128  -1594.194092  -1267.372314  
Kaohsiung City    -116.058777   -603.825195  -1687.398926   -116.058777

In [40]:
outputpath='C:/Users/Steven/Desktop/新增資料夾/immigration_update.xlsx'
df2.to_excel(outputpath,index=True,header=True)