In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottle

In [3]:
df1 = pd.read_excel('per_capital_income_df.xlsx')
df1

Unnamed: 0             98      99     100     101     102     103  \
0  New Taipei City  265140.804598  273351  279239  278023  284783  291591   
1      Taipei City  387052.795031  402056  381561  398217  408688  412973   
2     Taoyuan City  268840.571429  272470  273295  287727  288668  314701   
3    Taichung City  263142.638037  279324  265316  271157  282352  303365   
4      Tainan City  263413.109756  252184  245524  242163  261153  266012   
5   Kaohsiung City  291891.194969  311566  270996  283843  295244  300872   
6           Taiwan  473259.000000  524234  527186  537021  565198  607264   

      104     105     106     107     108  
0  305575  326152  337605  350606  371156  
1  426633  440278  436538  436489  458839  
2  311248  325471  327133  346623  357432  
3  311948  322806  337637  343713  352633  
4  269302  286254  293031  293762  305444  
5  319905  304104  321015  328911  331657  
6  633367  650854  667945  678233  687140

In [4]:
df1.columns

Index(['Unnamed: 0', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [5]:
df1.index = df1['Unnamed: 0']

In [6]:
df1.columns

Index(['Unnamed: 0', 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='object')

In [7]:
df1

Unnamed: 0             98      99     100     101  \
Unnamed: 0                                                                
New Taipei City  New Taipei City  265140.804598  273351  279239  278023   
Taipei City          Taipei City  387052.795031  402056  381561  398217   
Taoyuan City        Taoyuan City  268840.571429  272470  273295  287727   
Taichung City      Taichung City  263142.638037  279324  265316  271157   
Tainan City          Tainan City  263413.109756  252184  245524  242163   
Kaohsiung City    Kaohsiung City  291891.194969  311566  270996  283843   
Taiwan                    Taiwan  473259.000000  524234  527186  537021   

                    102     103     104     105     106     107     108  
Unnamed: 0                                                               
New Taipei City  284783  291591  305575  326152  337605  350606  371156  
Taipei City      408688  412973  426633  440278  436538  436489  458839  
Taoyuan City     288668  314701  311248  325471  327133  346623  357432  
Taichung City    282352  303365  311948  322806  337637  343713  352633  
Tainan City      261153  266012  269302  286254  293031  293762  305444  
Kaohsiung City   295244  300872  319905  304104  321015  328911  331657  
Taiwan           565198  607264  633367  650854  667945  678233  687140

In [8]:
df1 = df1.iloc[:-1, 1:-1]
df1

98      99      100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107  
Unnamed: 0                                       
New Taipei City  305575  326152  337605  350606  
Taipei City      426633  440278  436538  436489  
Taoyuan City     311248  325471  327133  346623  
Taichung City    311948  322806  337637  343713  
Tainan City      269302  286254  293031  293762  
Kaohsiung City   319905  304104  321015  328911

In [9]:
col = []
for i in df1.columns:
    col.append(str(i))
col

['98', '99', '100', '101', '102', '103', '104', '105', '106', '107']

In [10]:
df1.columns = col
df1

98      99     100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107  
Unnamed: 0                                       
New Taipei City  305575  326152  337605  350606  
Taipei City      426633  440278  436538  436489  
Taoyuan City     311248  325471  327133  346623  
Taichung City    311948  322806  337637  343713  
Tainan City      269302  286254  293031  293762  
Kaohsiung City   319905  304104  321015  328911

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, New Taipei City to Kaohsiung City
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   98      6 non-null      float64
 1   99      6 non-null      int64  
 2   100     6 non-null      int64  
 3   101     6 non-null      int64  
 4   102     6 non-null      int64  
 5   103     6 non-null      int64  
 6   104     6 non-null      int64  
 7   105     6 non-null      int64  
 8   106     6 non-null      int64  
 9   107     6 non-null      int64  
dtypes: float64(1), int64(9)
memory usage: 528.0+ bytes


### input為n維

In [13]:
d = int(input('輸入的維度：'))
x_train = []
y_train = []
x_test = []
y_test = []

for a in range(2):
    x_test.append([])
    y_test.append([])

for b in range(8-d):
    x_train.append([])
    y_train.append([])
    
for i in range(2):
    x_test[i] = (df1.iloc[:, -2-d+i:-2+i].values)
    y_test[i] = (df1.iloc[:, -2+i].values)

for j in range(8-d):
    x_train[j] = (df1.iloc[:, j:d+j].values)
    y_train[j] = (df1.iloc[:, d+j].values)

輸入的維度：2


In [14]:
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)

In [15]:
x_train

array([[[265140.8045977 , 273351.        ],
        [387052.79503106, 402056.        ],
        [268840.57142857, 272470.        ],
        [263142.63803681, 279324.        ],
        [263413.1097561 , 252184.        ],
        [291891.19496855, 311566.        ]],

       [[273351.        , 279239.        ],
        [402056.        , 381561.        ],
        [272470.        , 273295.        ],
        [279324.        , 265316.        ],
        [252184.        , 245524.        ],
        [311566.        , 270996.        ]],

       [[279239.        , 278023.        ],
        [381561.        , 398217.        ],
        [273295.        , 287727.        ],
        [265316.        , 271157.        ],
        [245524.        , 242163.        ],
        [270996.        , 283843.        ]],

       [[278023.        , 284783.        ],
        [398217.        , 408688.        ],
        [287727.        , 288668.        ],
        [271157.        , 282352.        ],
        [242163.        , 

In [16]:
x_train.shape

(6, 6, 2)

In [17]:
y_train

array([[279239, 381561, 273295, 265316, 245524, 270996],
       [278023, 398217, 287727, 271157, 242163, 283843],
       [284783, 408688, 288668, 282352, 261153, 295244],
       [291591, 412973, 314701, 303365, 266012, 300872],
       [305575, 426633, 311248, 311948, 269302, 319905],
       [326152, 440278, 325471, 322806, 286254, 304104]], dtype=int64)

In [18]:
y_train.shape

(6, 6)

In [19]:
x_test

array([[[305575, 326152],
        [426633, 440278],
        [311248, 325471],
        [311948, 322806],
        [269302, 286254],
        [319905, 304104]],

       [[326152, 337605],
        [440278, 436538],
        [325471, 327133],
        [322806, 337637],
        [286254, 293031],
        [304104, 321015]]], dtype=int64)

In [20]:
y_test

array([[337605, 436538, 327133, 337637, 293031, 321015],
       [350606, 436489, 346623, 343713, 293762, 328911]], dtype=int64)

In [21]:
x_train = x_train.reshape(-1, d)
y_train = y_train.ravel()
x_test = x_test.reshape(-1, d)
y_test = y_test.ravel()

In [22]:
x_train

array([[265140.8045977 , 273351.        ],
       [387052.79503106, 402056.        ],
       [268840.57142857, 272470.        ],
       [263142.63803681, 279324.        ],
       [263413.1097561 , 252184.        ],
       [291891.19496855, 311566.        ],
       [273351.        , 279239.        ],
       [402056.        , 381561.        ],
       [272470.        , 273295.        ],
       [279324.        , 265316.        ],
       [252184.        , 245524.        ],
       [311566.        , 270996.        ],
       [279239.        , 278023.        ],
       [381561.        , 398217.        ],
       [273295.        , 287727.        ],
       [265316.        , 271157.        ],
       [245524.        , 242163.        ],
       [270996.        , 283843.        ],
       [278023.        , 284783.        ],
       [398217.        , 408688.        ],
       [287727.        , 288668.        ],
       [271157.        , 282352.        ],
       [242163.        , 261153.        ],
       [283

In [23]:
y_train

array([279239, 381561, 273295, 265316, 245524, 270996, 278023, 398217,
       287727, 271157, 242163, 283843, 284783, 408688, 288668, 282352,
       261153, 295244, 291591, 412973, 314701, 303365, 266012, 300872,
       305575, 426633, 311248, 311948, 269302, 319905, 326152, 440278,
       325471, 322806, 286254, 304104], dtype=int64)

In [24]:
from xgboost import XGBRegressor
xgbr = XGBRegressor(n_estimators=100 , max_depth=3 , learning_rate=0.1, subsample=1, colsample_bynode=0.8, reg_lambda=1e-05)
xgbr.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.8, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1e-05, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [25]:
xgbr.predict(x_test)

array([319269.88, 439715.38, 314659.4 , 314659.4 , 290551.  , 327438.78,
       326955.9 , 439715.38, 326955.9 , 326955.9 , 305734.5 , 319269.88],
      dtype=float32)

In [26]:
y_test

array([337605, 436538, 327133, 337637, 293031, 321015, 350606, 436489,
       346623, 343713, 293762, 328911], dtype=int64)

In [27]:
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    print('MAPE為', MAPE)

MAPE為 0.060882151560299344
MAPE為 0.0073351142294274425
MAPE為 0.04743459312039962
MAPE為 0.05840364551259203
MAPE為 0.02460952514143101
MAPE為 0.024661552636186797


In [28]:
number = 0 
for i in range(6):
    MAPE = abs((xgbr.predict(x_test)[i]- y_test[i])/y_test[i])+abs((xgbr.predict(x_test)[i+6]- y_test[i+6])/y_test[i+6])
    MAPE /= 2
    number += MAPE
number /= 6
print('平均MAPE為', number)

平均MAPE為 0.037221097033389376


In [29]:
number = 0
for i in range(len(xgbr.predict(x_test) - y_test)):
    number += ((xgbr.predict(x_test) - y_test)[i])**2
    
number /= len(xgbr.predict(x_test) - y_test)
print('平均MSE為', number)

平均MSE為 212572623.90348306


```
輸入為1D的平均MAPE為0.061073712083930524
         平均MSE為 633095527.979899
輸入為2D的平均MAPE為0.037221097033389376
         平均MSE為 212572623.90348306
輸入為3D的平均MAPE為0.054778624357550765
         平均MSE為 490480931.38517255
輸入為4D的平均MAPE為0.054707829690290734
         平均MSE為 521006446.75561523
輸入為5D的平均MAPE為0.05614738356079274
         平均MSE為 505980214.0609538
```

## 選擇2D！！！

In [30]:
df1

98      99     100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107  
Unnamed: 0                                       
New Taipei City  305575  326152  337605  350606  
Taipei City      426633  440278  436538  436489  
Taoyuan City     311248  325471  327133  346623  
Taichung City    311948  322806  337637  343713  
Tainan City      269302  286254  293031  293762  
Kaohsiung City   319905  304104  321015  328911

In [31]:
df2 = df1.copy()
df2

98      99     100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107  
Unnamed: 0                                       
New Taipei City  305575  326152  337605  350606  
Taipei City      426633  440278  436538  436489  
Taoyuan City     311248  325471  327133  346623  
Taichung City    311948  322806  337637  343713  
Tainan City      269302  286254  293031  293762  
Kaohsiung City   319905  304104  321015  328911

In [32]:
df2.iloc[:, -d:].values

array([[337605, 350606],
       [436538, 436489],
       [327133, 346623],
       [337637, 343713],
       [293031, 293762],
       [321015, 328911]], dtype=int64)

In [33]:
xgbr.predict(df2.iloc[:, -d:].values)

array([327910.72, 439715.38, 327910.72, 326955.9 , 298768.56, 326955.9 ],
      dtype=float32)

In [34]:
df2['108'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98      99     100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107           108  
Unnamed: 0                                                     
New Taipei City  305575  326152  337605  350606  327910.71875  
Taipei City      426633  440278  436538  436489  439715.37500  
Taoyuan City     311248  325471  327133  346623  327910.71875  
Taichung City    311948  322806  337637  343713  326955.90625  
Tainan City      269302  286254  293031  293762  298768.56250  
Kaohsiung City   319905  304104  321015  328911  326955.90625

In [35]:
df2['109'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98      99     100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107           108           109  
Unnamed: 0                                                                   
New Taipei City  305575  326152  337605  350606  327910.71875  363840.09375  
Taipei City      426633  440278  436538  436489  439715.37500  439715.37500  
Taoyuan City     311248  325471  327133  346623  327910.71875  326955.90625  
Taichung City    311948  322806  337637  343713  326955.90625  326955.90625  
Tainan City      269302  286254  293031  293762  298768.56250  319166.50000  
Kaohsiung City   319905  304104  321015  328911  326955.90625  326955.90625

In [36]:
df2['110'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98      99     100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107           108           109  \
Unnamed: 0                                                                    
New Taipei City  305575  326152  337605  350606  327910.71875  363840.09375   
Taipei City      426633  440278  436538  436489  439715.37500  439715.37500   
Taoyuan City     311248  325471  327133  346623  327910.71875  326955.90625   
Taichung City    311948  322806  337637  343713  326955.90625  326955.90625   
Tainan City      269302  286254  293031  293762  298768.56250  319166.50000   
Kaohsiung City   319905  304104  321015  328911  326955.90625  326955.90625   

                          110  
Unnamed: 0                     
New Taipei City  370040.68750  
Taipei City      439715.37500  
Taoyuan City     326955.90625  
Taichung City    326955.90625  
Tainan City      304770.53125  
Kaohsiung City   326955.90625

In [37]:
df2['111'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98      99     100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107           108           109  \
Unnamed: 0                                                                    
New Taipei City  305575  326152  337605  350606  327910.71875  363840.09375   
Taipei City      426633  440278  436538  436489  439715.37500  439715.37500   
Taoyuan City     311248  325471  327133  346623  327910.71875  326955.90625   
Taichung City    311948  322806  337637  343713  326955.90625  326955.90625   
Tainan City      269302  286254  293031  293762  298768.56250  319166.50000   
Kaohsiung City   319905  304104  321015  328911  326955.90625  326955.90625   

                          110           111  
Unnamed: 0                                   
New Taipei City  370040.68750  406924.87500  
Taipei City      439715.37500  439715.37500  
Taoyuan City     326955.90625  326955.90625  
Taichung City    326955.90625  326955.90625  
Tainan City      304770.53125  327438.78125  
Kaohsiung City   326955.90625  326955.90625

In [38]:
df2['112'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98      99     100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107           108           109  \
Unnamed: 0                                                                    
New Taipei City  305575  326152  337605  350606  327910.71875  363840.09375   
Taipei City      426633  440278  436538  436489  439715.37500  439715.37500   
Taoyuan City     311248  325471  327133  346623  327910.71875  326955.90625   
Taichung City    311948  322806  337637  343713  326955.90625  326955.90625   
Tainan City      269302  286254  293031  293762  298768.56250  319166.50000   
Kaohsiung City   319905  304104  321015  328911  326955.90625  326955.90625   

                          110           111           112  
Unnamed: 0                                                 
New Taipei City  370040.68750  406924.87500  411991.78125  
Taipei City      439715.37500  439715.37500  439715.37500  
Taoyuan City     326955.90625  326955.90625  326955.90625  
Taichung City    326955.90625  326955.90625  326955.90625  
Tainan City      304770.53125  327438.78125  319269.87500  
Kaohsiung City   326955.90625  326955.90625  326955.90625

In [39]:
df2['113'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98      99     100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107           108           109  \
Unnamed: 0                                                                    
New Taipei City  305575  326152  337605  350606  327910.71875  363840.09375   
Taipei City      426633  440278  436538  436489  439715.37500  439715.37500   
Taoyuan City     311248  325471  327133  346623  327910.71875  326955.90625   
Taichung City    311948  322806  337637  343713  326955.90625  326955.90625   
Tainan City      269302  286254  293031  293762  298768.56250  319166.50000   
Kaohsiung City   319905  304104  321015  328911  326955.90625  326955.90625   

                          110           111           112           113  
Unnamed: 0                                                               
New Taipei City  370040.68750  406924.87500  411991.78125  426509.15625  
Taipei City      439715.37500  439715.37500  439715.37500  439715.37500  
Taoyuan City     326955.90625  326955.90625  326955.90625  326955.90625  
Taichung City    326955.90625  326955.90625  326955.90625  326955.90625  
Tainan City      304770.53125  327438.78125  319269.87500  326955.90625  
Kaohsiung City   326955.90625  326955.90625  326955.90625  326955.90625

In [40]:
df2['114'] = xgbr.predict(df2.iloc[:, -d:].values)
df2

98      99     100     101     102     103  \
Unnamed: 0                                                               
New Taipei City  265140.804598  273351  279239  278023  284783  291591   
Taipei City      387052.795031  402056  381561  398217  408688  412973   
Taoyuan City     268840.571429  272470  273295  287727  288668  314701   
Taichung City    263142.638037  279324  265316  271157  282352  303365   
Tainan City      263413.109756  252184  245524  242163  261153  266012   
Kaohsiung City   291891.194969  311566  270996  283843  295244  300872   

                    104     105     106     107           108           109  \
Unnamed: 0                                                                    
New Taipei City  305575  326152  337605  350606  327910.71875  363840.09375   
Taipei City      426633  440278  436538  436489  439715.37500  439715.37500   
Taoyuan City     311248  325471  327133  346623  327910.71875  326955.90625   
Taichung City    311948  322806  337637  343713  326955.90625  326955.90625   
Tainan City      269302  286254  293031  293762  298768.56250  319166.50000   
Kaohsiung City   319905  304104  321015  328911  326955.90625  326955.90625   

                          110           111           112           113  \
Unnamed: 0                                                                
New Taipei City  370040.68750  406924.87500  411991.78125  426509.15625   
Taipei City      439715.37500  439715.37500  439715.37500  439715.37500   
Taoyuan City     326955.90625  326955.90625  326955.90625  326955.90625   
Taichung City    326955.90625  326955.90625  326955.90625  326955.90625   
Tainan City      304770.53125  327438.78125  319269.87500  326955.90625   
Kaohsiung City   326955.90625  326955.90625  326955.90625  326955.90625   

                          114  
Unnamed: 0                     
New Taipei City  439715.37500  
Taipei City      439715.37500  
Taoyuan City     326955.90625  
Taichung City    326955.90625  
Tainan City      326955.90625  
Kaohsiung City   326955.90625

In [41]:
outputpath='C:/Users/Steven/Desktop/新增資料夾/income_update.xlsx'
df2.to_excel(outputpath,index=True,header=True)